MegaMek/megameklab

- src/megameklab/com/ui/Aero/StatusBar.java
- src/megameklab/com/ui/Aero/views/SummaryView.java
- src/megameklab/com/ui/BattleArmor/StatusBar.java
- src/megameklab/com/ui/BattleArmor/views/CriticalView.java
- src/megameklab/com/ui/Mek/StatusBar.java
- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/Mek/views/SummaryView.java
- src/megameklab/com/ui/Vehicle/StatusBar.java
- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
- src/megameklab/com/ui/Vehicle/views/SummaryView.java
- src/megameklab/com/util/UnitUtil.java
Related to https://github.com/MegaMek/megamek/pull/57 - the constructor for EntityVerifier is now private, however, there is a new static method to call to get an instance.
> updated calls for creating a new instance of EntityVerifier

- src/megameklab/com/ui/Aero/StatusBar.java
- src/megameklab/com/ui/Aero/tabs/StructureTab.java
- src/megameklab/com/ui/Aero/views/SummaryView.java
- src/megameklab/com/ui/BattleArmor/StatusBar.java
- src/megameklab/com/ui/Infantry/StatusBar.java
- src/megameklab/com/ui/Mek/Printing/PrintAdvancedMech.java
- src/megameklab/com/ui/Mek/Printing/PrintAdvancedQuad.java
- src/megameklab/com/ui/Mek/StatusBar.java
- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/Mek/views/SummaryView.java
- src/megameklab/com/ui/Vehicle/StatusBar.java
- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
- src/megameklab/com/ui/Vehicle/views/SummaryView.java
- src/megameklab/com/util/ImageHelperAero.java
- src/megameklab/com/util/ImageHelperVehicle.java
This is required for MML to continue to working after https://github.com/MegaMek/megamek/pull/154 was applied.
> Replacing mass/tonnage related internal data with doubles

- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
That was surprisingly easy. I haven't tested it much, but it loads naval units from the cache. Printing is broken.
> Added naval movement modes.

- docs/history.txt
- mmconf/log4j.xml
- src/megameklab/com/MegaMekLab.java
- src/megameklab/com/ui/Mek/Printing/PrintMech.java
- src/megameklab/com/ui/Mek/Printing/PrintTripod.java
- src/megameklab/com/util/UnitUtil.java
> Added log4j support.

- docs/history.txt
- src/megameklab/com/util/MenuBarCreator.java
Corrected the project URL in the about dialog.
> Fix for issue #70.

- build.xml
Modified build.xml to auto-generate the jar manifest and dynamically populate its class-path.
> Updated megamek.jar

- src/megameklab/com/util/MenuBarCreator.java
This fixes issue 102, where the file extension when exporting to a text file was incorrectly being set as .html instead of .txt.
> Fix for issue #102.

- src/megameklab/com/ui/Infantry/views/SpecializationView.java
This change allows selection of XCT training when creating infantry. Completes addition of XCT infantry.
> Added XCT specialization for MML

- src/megameklab/com/ui/MegaMekLabMainUI.java
- src/megameklab/com/util/CConfig.java
- src/megameklab/com/util/MenuBarCreator.java
Added a "themes" menu that allows user to select the look and feel. Preserves user selection when exiting.
> Fix for #32: UI elements do not allow enough area for text on Linux (Gnome 3/Fedora)

- src/megameklab/com/ui/Infantry/MainUI.java
- src/megameklab/com/ui/Infantry/tabs/StructureTab.java
Updates filename in title bar when infantry model name changes.
> Fix for #170: Infantry Window Title Not Updating

- src/megameklab/com/util/StringUtils.java
> Fix compilation issue introduced by zweihander spa

- src/megameklab/com/util/UnitUtil.java
When a bay is removed using the build tab ui, the weapons and ammo are unallocated. If removed using `UnitUtil.removeMounted(Entity, Mounted)`, the weapons and ammo get dumped directly into the location. This would not normally happen, but was discovered due to an error in tech advancement data that caused a bay to be removed but not the weapon. See #199 
I added code that would unallocate any weapons in the bay without removing them from the unit. This is not likely to be encountered outside some similar bug, but it handles it more gracefully.
> Remove contents with weapon bay

- resources/megameklab/resources/Views.properties
- src/megameklab/com/ui/Aero/tabs/BuildTab.java
- src/megameklab/com/ui/Aero/tabs/EquipmentTab.java
- src/megameklab/com/ui/Aero/views/BuildView.java
- src/megameklab/com/ui/Aero/views/CriticalView.java
- src/megameklab/com/ui/aerospace/AerospaceBuildView.java
- src/megameklab/com/ui/aerospace/LargeCraftCriticalView.java
- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
- src/megameklab/com/util/UnitUtil.java
Depends on MM system_wide_equipment. Adds a fuselage/hull location for aerospace units. Fighters automatically have ammo placed there when added. No weapon can be placed there, and non-fighters cannot place ammo there either.
> System wide equipment

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/view/MekChassisView.java
Fixes #287: Cannot remove gyro from interface equipped mech
> Allow option of no gyro with interface cockpit

- src/megameklab/com/ui/Infantry/MainUI.java
- src/megameklab/com/ui/Infantry/tabs/StructureTab.java
- src/megameklab/com/ui/Mek/MainUI.java
- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/view/BAEnhancementView.java
- src/megameklab/com/ui/view/MekChassisView.java
- src/megameklab/com/util/UnitUtil.java
MML companion to MegaMek/megamek#1432
Plus some javadoc fixes.
Requires MM equipment_type_key branch.
> EquipmentType constants

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/view/MekChassisView.java
For implement Superheavy/Small Command Console. It is related with [a pull request of MegaMek.](https://github.com/MegaMek/megamek/pull/1477)
> Allow command console with superheavy/small cockpit

- src/megameklab/com/ui/Aero/tabs/EquipmentTab.java
Pretty straightforward
Fixes #390
> Filter weapons and ammo out of "other equipment" for aerospace units

- .gitignore
- src/megameklab/com/ui/Aero/tabs/StructureTab.java
- src/megameklab/com/ui/view/FighterChassisView.java
This is a minor refactor that I did while looking at the code relating to VSTOL. The .gitignore change is needed for those of us who use the Idea IDE
> FighterChassis and Aero StructureTab refactoring

- src/megameklab/com/ui/Infantry/tabs/StructureTab.java
> Refresh infantry status bar and preview tab when motive type changes.

- src/megameklab/com/util/UnitUtil.java
Spreadable equipment that always occupies a fixed set of locations do not use Mount#getSecondaryLocation, since some of them can span three or more locations (such as tracks on a quad mech). Instead they are placed in one location and occupy critical slots in the other(s). When toggling armored component, only the critical slots in the primary location are being considered. I factored out the code that checks a location, and in the case of split location fixed equipment, check all locations on the unit. This also removes duplicated code in the case of normal split equipment using Mount#getSecondaryLocation.
Besided the partial wing mentioned in the reported bug, this also affects mech tracks and talons, at least.
I verified that this does not affect a unit being loaded from a file, but …
> Include all slots for armored fixed location spreadable equipment.

- src/megameklab/com/util/Mech/CriticalTransferHandler.java
> Populate secondary locations combo for right torso.

- src/megameklab/com/MegaMekLab.java
Causes quirks to show up on the preview panel. Also needed for the option to show quirks on the record sheet.
Closes #419
> Initialize quirks on startup

- src/megameklab/com/ui/Aero/tabs/StructureTab.java
- src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java
- src/megameklab/com/ui/aerospace/DropshipStructureTab.java
> Update both current and original heat sinks when count changes.

- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
> Round combat vehicle engine rating to the next 5.

- src/megameklab/com/ui/BattleArmor/tabs/BuildTab.java
> Take installed equipment into account when auto-filling BA crits.

- src/megameklab/com/ui/Vehicle/tabs/EquipmentTab.java
Requires MegaMek/megameklab#1707 (Note to self: update maven artifact dependencies)
Fixes #474
> Automatically place CV chassis mods, ammo, and CASE in body location.

- src/megameklab/com/ui/Mek/views/SummaryView.java
- src/megameklab/com/ui/Vehicle/views/SummaryView.java
- src/megameklab/com/ui/protomek/ProtomekCriticalView.java
- src/megameklab/com/ui/protomek/ProtomekSummaryView.java
- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
- src/megameklab/com/util/CriticalTableModel.java
- src/megameklab/com/util/UnitUtil.java
This is the MML companion to MegaMek/megamek#1718
> Move primary determination of equipment weight to Mounted.

- src/megameklab/com/ui/view/CVTransportView.java
I hope this was an unintended side-effect of something that I changed rather than something I wrote this way to begin with, because that would be really bone-headed.
Fixes #489
> Check for omni before clearing pod space.

- .github/build-scan-init.gradle
- .github/workflows/ci.yml
This adds a basic CI task to MML using GitHub Actions. I'm going to try plumbing SpotBugs into the mix this week.
See: https://github.com/sixlettervariables/megameklab/pull/117/checks?check_run_id=544250485
> Add basic GitHub Actions CI

- .github/workflows/ci.yml
This removes the usage of settings_local and properties_local, and removes the on push trigger.
> Improve GitHub Actions CI/CD

- src/megameklab/com/util/MenuBarCreator.java
> Add space between chassis and model when building the default file name.

- .github/build-scan-init.gradle
- .github/workflows/ci.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/nightly-maven-ci.yml
This brings over the enhancements to our GitHub Actions CI from the MM and MHQ repos. It features:
1. Looking up a "sister" branch in the pull request submitter's MM repo, and using it if one is found.
2. Improved comments so others can make modifications with more confidence.
> Improve GitHub Actions CI

- .gitignore
This makes it easier to test for MML
> Improving the gitignore relating to Mechfile data

- .github/workflows/update-maven-repo.yml
This works like the one on the MM repository with some changes in paths.
> Update the Maven Repo on source change

- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
An ammunition Mounted on a large craft can hold multiple slots of ammunition, and the capacity is tracked as well as the number of shots. This is largely irrelevant in construction, but failure to update it when the capacity changes causes the TRO summary to display an incorrect value.
Partial fix for #593.
> Update ammo bin capacity

- src/megameklab/com/printing/StandardInventoryEntry.java
> Show water range for torpedoes on record sheets

- src/megameklab/com/ui/tabs/TransportTab.java
Allows adding infantry and BA transport bays with no doors. Fixes #661.
Requires MegaMek/megamek#2068
> No doors are required for infantry bays

- src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java
- src/megameklab/com/ui/aerospace/DropshipStructureTab.java
Added code to update the heat, fuel, and summary panels and the status bar when the military/civilian checkbox is toggled.
Fixes #670
> Military toggle update

- src/megameklab/com/printing/PrintInfantry.java
- src/megameklab/com/ui/Infantry/views/ArmorView.java
- src/megameklab/com/util/UnitUtil.java
Update method names due to MegaMek/megamek#2079
> Update infantry damage divisor setter and getter names

- src/megameklab/com/ui/dialog/MegaMekLabUnitSelectorDialog.java
> actually close when clicking select and close

- src/megameklab/com/ui/supportvehicle/SVArmorTab.java
- src/megameklab/com/ui/supportvehicle/SVStructureTab.java
See MegaMek/megamek#2121
Completes fix for #713
> Refresh SV tech advancement when engine, structure, or armor tech rating changes.

- src/megameklab/com/util/Mech/DropTargetCriticalList.java
Currently only the shotsLeft is updated.
Fixes #714
> Update both original and current shots when BA missile ammo is changed.

- src/megameklab/com/ui/dialog/LoadingDialog.java
Any exceptions encountered when loading an Entity by the SwingWorker are ignored unless specifically checked for.
> Log any exceptions encountered when loading an Entity

- src/megameklab/com/util/UnitUtil.java
Companion to MegaMek/megamek#2294. Adds checks for illegal MiscType equipment for small SVs to equipment table filtering.
> Additional equipment filtering for small SVs.

- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
This adds some logging to help track down #755, which I've not been able to reproduce. I'm pretty sure this is not the first time it's come up and I don't have any ideas on what could be causing it.
> Bay weapon ClassCastException debugging logging

- src/megameklab/com/ui/Aero/tabs/EquipmentTab.java
This fell through the cracks in some equipment filtering streamlining.
Fixes #754
> Include coolant pod in asf other equipment.

- src/megameklab/com/util/StringUtils.java
> Show correct cluster damage on record sheet for torpedoes and prototype rocket launchers

- src/megameklab/com/printing/StandardInventoryEntry.java
> Show both locations on record sheet for split equipment.

- resources/megameklab/com/printing/reference/MekHitLocation.properties
> Update Hit Location Table title, fixes #826

- src/megameklab/com/ui/Aero/tabs/StructureTab.java
- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
- src/megameklab/com/ui/Vehicle/views/SummaryView.java
- src/megameklab/com/ui/supportvehicle/SVArmorTab.java
Allocate required patchwork armor slots for dark age armors from IO.
Fixes #858
> Patchwork slot cost for dark age armors

- src/megameklab/com/ui/view/MekChassisView.java
> 905: Preventing Full Head Ejection NPE

- src/megameklab/com/printing/StandardInventoryEntry.java
- src/megameklab/com/util/StringUtils.java
> 912: Changing AMS, A-Pod, and B-Pod display text from PD to PB

- resources/megameklab/resources/Views.properties
- src/megameklab/com/ui/Aero/tabs/EquipmentTab.java
- src/megameklab/com/ui/BattleArmor/tabs/EquipmentTab.java
- src/megameklab/com/ui/Mek/tabs/EquipmentTab.java
- src/megameklab/com/ui/Vehicle/tabs/EquipmentTab.java
- src/megameklab/com/ui/tabs/EquipmentTab.java
> 913: Preventing infinite loops in remove heat sink

- src/megameklab/com/util/MenuBarCreator.java
- src/megameklab/com/util/UnitUtil.java
This applies https://github.com/MegaMek/megamek/pull/2782 to MML, standardizing the code.
> MM 2281: Creating a standard BV Display Dialog

- src/megameklab/com/ui/Infantry/views/FieldGunView.java
Well, this one was pretty straightforward, those infantry are going to be a lot cooler now.
> enable HVAC for infantry field guns

- src/megameklab/com/MMLConstants.java
- src/megameklab/com/MegaMekLab.java
- src/megameklab/com/ui/StartupGUI.java
- src/megameklab/com/util/MenuBarCreator.java
As part of https://github.com/MegaMek/megamek/pull/3162 this moves versioning to MegaMek.
I've got plans (and initial code) for using the MMLConstants file in the near future, just bringing it into existence within MML for the time being as that's how I'm planning on using the SuiteConstants internally.
> Suite Version Tracking: MegaMekLab Changes

- src/megameklab/com/ui/BattleArmor/tabs/StructureTab.java
Fixes #935
As an aside.. Why does this make it change the JJ type upon changing MP with the spinner?
> Fixes BA JJ NPE

- resources/megameklab/com/printing/reference/AeroHitLocation.properties
- src/megameklab/com/printing/reference/AeroHitLocation.java
- src/megameklab/com/printing/reference/AeroToHitMods.java
+ Corrected the Aero record sheet reference tables.
(Checked rules and errata, all valid)
Resolves #908
> Issue 908: Corrections to the Aero reference tables

- build.gradle
Apache FOP to 2.6 (some additional font support, and individual dependency reduction), Batik to 1.14 (bugfixes).
> Updating XML Graphic dependencies

- src/megameklab/com/util/CritListCellRenderer.java
fixes my own bug.
Resolves #973
> Fix Issue #973

- src/megameklab/com/MegaMekLab.java
I also added the MegaMekLab bit to make it easier when I swap the logger to LogManager
> Fixing Quirk Exception Catch

- src/megameklab/com/util/StringUtils.java
- src/megameklab/com/util/UnitUtil.java
This originates from Hammer's Tech progression changes.
> Fixing MML Build Failure

- src/megameklab/com/printing/StandardInventoryEntry.java
- src/megameklab/com/util/StringUtils.java
> 986: Fixing Hanging Bracket on Aerospace TAG Equipment

- src/megameklab/com/MegaMekLab.java
- src/megameklab/com/printing/PrintInfantry.java
- src/megameklab/com/ui/battleArmor/BABuildView.java
- src/megameklab/com/ui/combatVeh/CVSummaryView.java
- src/megameklab/com/ui/generalUnit/PreviewTab.java
- src/megameklab/com/ui/generalUnit/UnallocatedView.java
- src/megameklab/com/ui/util/ITab.java
- src/megameklab/com/ui/util/IView.java
- src/megameklab/com/util/UnitUtil.java
To review: Whitespace differences off
> Fixing the remaining tab spacing in MegaMekLab

- src/megameklab/com/ui/util/EquipmentDatabaseCategory.java
> Added Coolant Pod to Other category check in EquipmentDatabaseCategory

- src/megameklab/com/MegaMekLab.java
This is the MML implementation of https://github.com/MegaMek/megamek/pull/3427
> Standardized Suite Graphical Setup Initialization: Font and Theme Standardization

- .github/codecov.yml
- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/nightly-maven-ci.yml
- .github/workflows/update-maven-repo.yml
- megameklab/build.gradle
- megameklab/src/megameklab/MegaMekLab.java
This fixes the current maven issues and standardizes the internals with MM and MHQ build and integration changes.
> Build Script and Integration Issues: Standardization and Fixes

- .gitignore
Did this while testing on a personal branch, so using a PR to merge
> Ignore Eclipse build files

- megameklab/src/megameklab/ui/fighterAero/ASStructureTab.java
> Issue 1067: Safe turns refresh

- megameklab/resources/megameklab/resources/Menu.properties
- megameklab/src/megameklab/ui/MenuBar.java
I'm going to follow this up with a PR to reorganize MML's menu bar similar to how MHQ's is currently organized.
> Adding Cache Refresh to MML

- megameklab/src/megameklab/ui/util/AbstractEquipmentDatabaseView.java
There was a reversed condition on an assert check.
> Correct faulty assertion

- megameklab/src/megameklab/ui/battleArmor/BAChassisView.java
Should fix #1104. Allows Battle Armor squad size spinner to decrement to 1.
> Battle Armor Squad Size Spinner Adjustment

- megameklab/src/megameklab/MMLOptionsChangedEvent.java
This adds the MMLOptionsChangedEvent, fixing a mistake I made from the initial PR.
> Suite Options: Adding MML Options Changed Event

- megameklab/src/megameklab/ui/battleArmor/BAStructureTab.java
- megameklab/src/megameklab/ui/combatVehicle/CVStructureTab.java
- megameklab/src/megameklab/ui/fighterAero/ASStructureTab.java
- megameklab/src/megameklab/ui/largeAero/DSStructureTab.java
- megameklab/src/megameklab/ui/largeAero/WSStructureTab.java
- megameklab/src/megameklab/ui/mek/BMStructureTab.java
- megameklab/src/megameklab/ui/protoMek/PMStructureTab.java
- megameklab/src/megameklab/ui/supportVehicle/SVArmorTab.java
> 1099: Stop at 0 tons when Selecting "Use Remaining Tonnage" for Armour

- megameklab/src/megameklab/ui/MegaMekLabMainUI.java
- megameklab/src/megameklab/ui/MenuBar.java
> 1040: Adding Save Option to MML Exit Dialog

- megameklab/src/megameklab/printing/RecordSheetTask.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/util/CConfig.java
This covers all uses of Closeable::close and any leaks from improper use of try with resources (which MML didn't have any)
> Fixing Closeable Resource Leaks

- megameklab/src/megameklab/ui/combatVehicle/CVStructureTab.java
- megameklab/src/megameklab/ui/fighterAero/ASStructureTab.java
- megameklab/src/megameklab/ui/mek/BMStructureTab.java
- megameklab/src/megameklab/ui/supportVehicle/SVArmorTab.java
> Recalculate armor weight when patchwork location is changed.

- megameklab/data/images/recordsheets/templates_iso/warship_default.svg
- megameklab/data/images/recordsheets/templates_us/warship_default.svg
Adds the missing text field to the SVG template.
Fixes #1030
> Show broadsides heat on warship record sheet

- megameklab/src/megameklab/ui/largeAero/WSStructureTab.java
It looks like an old copy/paste error.
Partial fix for #1041
> Fix ClassCastException when toggling military checkbox.

- megameklab/src/megameklab/ui/combatVehicle/CVWeaponView.java
This requires https://github.com/MegaMek/megamek/pull/3998
> MMLConstants: Isolate Font Constants

- megameklab/src/megameklab/ui/battleArmor/BAStructureTab.java
Adds the missing AS conversion preview when constructing BA.
> Alpha Strike preview on BA

- megameklab/src/megameklab/printing/StandardInventoryEntry.java
> Issue 1223: Record Sheets: Show Artemis on MMLs

- megameklab/src/megameklab/printing/StandardInventoryEntry.java
> BA RS: Add "Trooper 1" to SSW text

- megameklab/data/images/recordsheets/templates_iso/battle_armor_squad.svg
- megameklab/data/images/recordsheets/templates_us/battle_armor_squad.svg
> BA RS: Show role

- megameklab/src/megameklab/printing/IdConstants.java
> Correct id string typo

- megameklab/src/megameklab/printing/PrintBattleArmor.java
- megameklab/src/megameklab/printing/PrintInfantry.java
- megameklab/src/megameklab/printing/PrintMech.java
- megameklab/src/megameklab/ui/combatVehicle/CVStatusBar.java
- megameklab/src/megameklab/ui/supportVehicle/SVStatusBar.java
This adapts MML to MegaMek/megamek#4474
> BV and MP adaptation to MM changes

- megameklab/src/megameklab/ui/fighterAero/ASStructureTab.java
- megameklab/src/megameklab/ui/generalUnit/FuelView.java
Fixes #1250 
Requires MegaMek/megamek#4570
> Issue MML-1250: Correct max turns with fuel calculation for CF

- megameklab/src/megameklab/ui/mek/BMBuildView.java
- megameklab/src/megameklab/ui/mek/BMCriticalTransferHandler.java
> Mek: Don't allow leg locations in split equipment

- megameklab/src/megameklab/ui/infantry/CIArmorView.java
- megameklab/src/megameklab/util/UnitUtil.java
Required by MegaMek/megamek#4601
> API update for ITechnology

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/nightly-maven-ci.yml
- .github/workflows/update-maven-repo.yml
Looking into Action failures and noticed a lot more actions are out of date (not the likely cause, but going to start from the beginning).
> [GitHub] Bump action versions

- megameklab/src/megameklab/ui/generalUnit/PreviewTab.java
Fixes #1240 
Requires MegaMek/megamek#4668
> Unit Preview: Generate and show Alpha Strike conversion report

- megameklab/src/megameklab/ui/dialog/MegaMekLabUnitSelectorDialog.java
Use the variable tech level setting in unit selector filtering.
Requires Megamek/megamek#4751
> Unit selector filtering

- megameklab/src/megameklab/util/UnitUtil.java
Related to fix for MM #1552: use EnumSet instead of Long Munition representation.
> Necessary for MML to work after the MM #1552 PR goes in

- megameklab/src/megameklab/ui/supportVehicle/SVEquipmentDatabaseView.java
> Have mast mounts go on the rotor on SV

- megameklab/src/megameklab/util/MekUtil.java
> On tripods, add a crit for environmental sealing to center leg

- megameklab/src/megameklab/ui/generalUnit/BasicInfoView.java
Must suspend the actionlistener during refresh
Fix #1385
> Fix for 1385

- megameklab/src/megameklab/ui/PopupMessages.java
The scrollbar is a little unwieldy so it's only added for long messages such as the weight summary then a unit is overweight.
Fixes #1384
> Use a scrollbar for long popup messages

- megameklab/src/megameklab/ui/mek/BMStructureTab.java
- megameklab/src/megameklab/util/MekUtil.java
A small refactor, removing some unused methods (I checked MHQ) and various small things. No visible effects.
> Misc code changes

- megameklab/src/megameklab/printing/InventoryWriter.java
> Show infantry bays on record sheet with platoon capacity rather than weight

- megameklab/src/megameklab/ui/generalUnit/PreviewTab.java
Adds the configuration bar with the font selector to the unit summary in MML (preview tab); MM already had this
> Use the configurable unit summary in MML

- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/util/CConfig.java
See Megamek/megamek#5209
Tests fail as the MM PR is required for this one
> Java LookAndFeels restriction and default

- megameklab/src/megameklab/ui/battleArmor/BAStructureTab.java
Refactored and simplified the code.
Fixes #1306
> Fix BA manipulator assignments

- megameklab/src/megameklab/ui/generalUnit/QuirksTab.java
This PR is required to add the new listener from PR MegaMek/megamek#5369.   It needs to be merged at the same time to deal with interrepo project dependencies.
> Add new required method for DialogOptionListener

- megameklab/src/megameklab/ui/MegaMekLabMainUI.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/MenuBarOwner.java
- megameklab/src/megameklab/ui/StartupGUI.java
> Trigger savefile selection when unit name changes

- build.gradle
- megameklab/build.gradle
- megameklab/docs/history.txt
- megameklab/src/megameklab/ui/generalUnit/MovementView.java
Includes the following fixes back-ported from 0.49.20:
#1498
Plus an update to MM's Version.java to support a 4th field in the version number (without this, bug reports would be quite difficult to keep track of).
Version is reported as 0.49.19.1
Testing:
- Ran all unit tests
- Verified Partial Wing handling in MML
> MegaMekLab 0.49.19.1 dot release

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/update-maven-repo.yml
First attempt to add 0.49.19.1-specific workflows.
> Update workflows for 0.49.19.1 (attempt 1)

- megameklab/docs/history.txt
> Updated history.txt

- megameklab/src/megameklab/printing/PrintRecordSheet.java
- megameklab/src/megameklab/ui/generalUnit/PreviewTab.java
- megameklab/src/megameklab/ui/generalUnit/RecordSheetPreviewPanel.java
- megameklab/src/megameklab/util/UnitPrintManager.java
Closes #1552.
Looks like this:
> Add record sheet display to preview tab

- .gitignore
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
- megameklab/build.gradle
- megameklab/mmconf/log4j2.xml
- megameklab/src/megameklab/printing/CGLMassPrinter.java
Updated Build Scripts
Updated Log4J Configuration
> Updated Gradle

- .gitignore
I believe we should ignore some more files.
> Gitgnore update

- megameklab/src/megameklab/util/AeroUtil.java
Fixes #1501
I don't see that BA Tube Arty should be allowed on fighters, but the other arty.
Requires MegaMek/megamek#6007
> #1501: Allow artillery on aeros according to TO:AUE

- megameklab/src/megameklab/printing/PrintMek.java
> Record sheets should say MECH

- megameklab/src/megameklab/printing/PrintRecordSheet.java
> Fix incorrect pilot info box drawing

- megameklab/src/megameklab/ui/mek/BMStructureTab.java
> Remove item in head when switching to small cockpit

- megameklab/src/megameklab/printing/PrintAero.java
- megameklab/src/megameklab/printing/PrintTank.java
- megameklab/src/megameklab/ui/combatVehicle/CVStructureTab.java
- megameklab/src/megameklab/ui/generalUnit/TransportTab.java
merge together with MegaMek/megamek#6181
> Rename TroopSpace to InfantryCompartment

- megameklab/src/megameklab/ui/generalUnit/QuirksTab.java
This Pull request is part of an overarching change on Megamek to extract an options interface.
This pull request depends on the PR of the same name on Megamek, which adds the inverted call for this function. 
https://github.com/MegaMek/megamek/pull/6265
> feat: inverted function call

- megameklab/src/megameklab/MegaMekLab.java
> Log jvm parameters

- megameklab/src/megameklab/printing/StandardInventoryEntry.java
- megameklab/src/megameklab/printing/WeaponBayText.java
- megameklab/src/megameklab/ui/generalUnit/BAProtoArmorView.java
- megameklab/src/megameklab/util/UnitUtil.java
Refactor flags to not use BigInteger anymore
[https://github.com/MegaMek/megamek/pull/6475](https://github.com/MegaMek/megamek/pull/6475)
> feat: changed flags from big integer to equipment flag

- megameklab/build.gradle
- megameklab/src/megameklab/printing/CGLMassPrinter.java
> Gradle clean up and depdency updates

- megameklab/unittests/megameklab/ui/generalUnit/BasicInfoViewTest.java
In my defence... I totally forgot -_-;
> Add missing copyright notice

- megameklab/src/megameklab/printing/PrintRecordSheet.java
- megameklab/src/megameklab/ui/battleArmor/BAMainUI.java
- megameklab/src/megameklab/ui/battleArmor/BAStructureTab.java
- megameklab/src/megameklab/ui/generalUnit/PreviewTab.java
- megameklab/src/megameklab/ui/generalUnit/RecordSheetPreviewPanel.java
- run.bat
Implemented FR #1638 
- Zoom+Panning in the Record Sheet Preview tab
- Reset zoom/pan with double click or right click menu option
- GPU acceleration for rendering
> Sheet preview with zoom+pan

- megameklab/src/megameklab/ui/util/DropTargetCriticalList.java
fixes #1758 
this requires the accompanying MM PR.
> #1758: Allow mounting to sponson turrets regardless of turret placement

- megameklab/src/megameklab/ui/generalUnit/summary/OtherSummaryItem.java
> Show component armoring weight in "other" in the Mek weight summary

- megameklab/src/megameklab/ui/util/EnhancedTabbedPane.java
Fixes JavaDoc not compiling.
Replaced some casting to be more inline with Instance of.
> JavaDoc fixes and instance variable shorthand.

- megameklab/src/megameklab/util/MMLFileDropTransferHandler.java
> Removed Deprecated methods from MMLogger and updated impacted calls.

- .github/codecov.yml
- .github/dependabot.yml
- .github/workflows/auto-label-issues.yml
- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependency-scan.yml
- .github/workflows/java-doc-on-pr.yml
- .github/workflows/java-doc.yml
- .github/workflows/nightly-ci.yml
Formatter Saves
- Trying to see if I can get rid of the warnings about bad runs.
> Adjustments to CodeQL run

- megameklab/src/megameklab/ui/battleArmor/BAMainUI.java
- megameklab/src/megameklab/ui/combatVehicle/CVMainUI.java
- megameklab/src/megameklab/ui/fighterAero/ASMainUI.java
- megameklab/src/megameklab/ui/generalUnit/QuirksTab.java
- megameklab/src/megameklab/ui/largeAero/DSMainUI.java
- megameklab/src/megameklab/ui/largeAero/WSMainUI.java
- megameklab/src/megameklab/ui/mek/BMMainUI.java
- megameklab/src/megameklab/ui/protoMek/PMMainUI.java
- megameklab/src/megameklab/ui/supportVehicle/SVMainUI.java
Distributed horizontally in columns and stacked vertically by group
> quirks tab reworked

- megameklab/src/megameklab/ui/handheldWeapon/HHWMainUI.java
So you can set a fluff image or whatever if you want.
> Add fluff tab to the Handheld Weapon editor

- .github/workflows/ci.yml
- build.gradle
- megameklab/build.gradle
Removed more gradle deprecations.
Adjusted CI scripts to run tests separate.
> Cleaned up gradle scripts.

- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
> fixed unit switch

- megameklab/src/megameklab/ui/dialog/MegaMekLabUnitSelectorDialog.java
- megameklab/src/megameklab/ui/dialog/PrintQueueDialog.java
- megameklab/src/megameklab/ui/generalUnit/RecordSheetPreviewPanel.java
Variant of the Async RS render approach, this one is per-page, more efficient.
This PR includes also print dialog preview.
> Async RS Rendering (per page) + Print Dialog Preview

- megameklab/src/megameklab/ui/handheldWeapon/HHWMainUI.java
> fix for hhw preview

- megameklab/src/megameklab/ui/combatVehicle/CVMainUI.java
- megameklab/src/megameklab/ui/generalUnit/QuirksTab.java
> fixed refresh listener for combat vehicle quirks

- megameklab/src/megameklab/ui/infantry/CIPlatoonTypeView.java
> max number of squads

- megameklab/resources/megameklab/resources/Dialogs.properties
- megameklab/src/megameklab/printing/InventoryWriter.java
- megameklab/src/megameklab/printing/RecordSheetOptions.java
- megameklab/src/megameklab/ui/dialog/settings/ExportSettingsPanel.java
- megameklab/src/megameklab/util/CConfig.java
configurable weapons sort order (backport from #1836 )
closes https://github.com/MegaMek/megameklab/issues/1060
> weapons sort order

- megameklab/src/megameklab/ui/generalUnit/RecordSheetPreviewPanel.java
- faster rendering
- less repaint calls
- maintains padding/zoom
- smart autopadding when changing amount of previewed sheets and end up out of bounds from viewport
Closes #1854
> faster rendering, less repaints, maintain padding/zoom, smart autopadding

- megameklab/src/megameklab/ui/dialog/FloatingEquipmentDatabaseDialog.java
This fixes a memory leak caused by the floatingequipment dialog never releasing
> floatingequipment dialog memory leak

- megameklab/data/images/recordsheets/templates_iso/protomek_quad.svg
- megameklab/data/images/recordsheets/templates_us/protomek_quad.svg
This PR fixes the alignment of the structure pips on the gun
> fixed structure gun pips on quad protomek

- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
- megameklab/src/megameklab/util/UnitUtil.java
Primary fix is the 2 JavaDoc errors reported in CI.
Secondary are minor items for readability and EC changes.
No bug fixes.
> Fix JavaDoc issues and very few CodeQL changes.

- megameklab/src/megameklab/printing/InventoryWriter.java
- megameklab/src/megameklab/util/UnitUtil.java
This PR fixes the text fitting calculation to fill the inventory area in the record sheet.
It properly calculates the number or lines required and it uses a smarter approach for calculation of line spacing reduction and font reduction.
> Fixed large inventory text fitting

- .github/workflows/ci.yml
- megameklab/build.gradle
> Fix Gradle warning due to a deprecation

- megameklab/build.gradle
- megameklab/src/megameklab/MegaMekLab.java
- megameklab/src/megameklab/ui/ForceBuildUI.java
- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
This is the post-release Deprecation Pass and Removal. Includes removal of post-Milestone compatibility code as well.
> Deprecation Removal from 0.50.05 and before, and legacy code.

- megameklab/src/megameklab/ui/listeners/SVBuildListener.java
That's it. Just fixes the JavaDoc issues.
> Fix: JavaDoc issues related to the ENUMs PR

- megameklab/src/megameklab/ui/generalUnit/QuirksTab.java
> sort the quirks top to bottom, left to right

- megameklab/docs/UserDirHelp.html
> FIX: Documentation

- megameklab/src/megameklab/ui/generalUnit/QuirksTab.java
this PR uses the VerticalGridLayout from https://github.com/MegaMek/megamek/pull/7149 to display the quirks.
> Quirks using VerticalGridLayout

- gradle/wrapper/gradle-wrapper.properties
- megameklab/build.gradle
Updated Gradle.
Updated Libraries.
Fixed issues with Copy License command.
> FIX: Issue with Copy License Command.

- megameklab/mmconf/log4j2.xml
> fix: logs for megamek lab now in line with most modern implementation

- megameklab/src/megameklab/ui/dialog/MegaMekLabUnitSelectorDialog.java
> Fix NPE from unit selector

- megameklab/src/megameklab/printing/InventoryWriter.java
- megameklab/src/megameklab/ui/generalUnit/TransportTab.java
> Fix ProtoMek bays for construction

- megameklab/resources/megameklab/resources/Dialogs.properties
- megameklab/src/megameklab/printing/IntrinsicPhysicalInventoryEntry.java
- megameklab/src/megameklab/printing/InventoryWriter.java
- megameklab/src/megameklab/printing/RecordSheetOptions.java
- megameklab/src/megameklab/ui/dialog/settings/ExportSettingsPanel.java
- megameklab/src/megameklab/util/CConfig.java
Adds an option to remove charge/dfa/push/etc and keep only kick, punch, and (ProtoMek) frenzy.
> Make extra physical attacks optional

- megameklab/build.gradle
Fixes for bad data
Fixes for Too much data in each project.
> Fixes for Build.

- megameklab/src/megameklab/ui/StartupGUI.java
Fixes #2018
Must be merged with MegaMek/megamek#7423 and MegaMek/mm-data#60.
> Fix MML splash

- megameklab/src/megameklab/printing/InventoryWriter.java
fixes issue with weapon quirks not being properly aligned in the inventory.
> weapon quirks alignment

- megameklab/src/megameklab/printing/PrintMek.java
Required to restore operation to mekbay
> Include MekBay attributes in fancy pips

- megameklab/src/megameklab/printing/PrintEntity.java
- megameklab/src/megameklab/printing/SVGMassPrinter.java
Added armor type in the export
Implemented parallel export
> MekBay stuffs

- megameklab/src/megameklab/printing/PrintMek.java
> Add proper attributes to head structure pips
