- docs/history.txt
- src/megameklab/com/ui/Aero/Printing/PrintAero.java
- src/megameklab/com/ui/Aero/Printing/PrintSmallCraftSpheroid.java
- src/megameklab/com/ui/Mek/Printing/PrintMech.java
- src/megameklab/com/ui/Mek/Printing/PrintQuad.java
- src/megameklab/com/ui/Mek/Printing/PrintTripod.java
Updated Coords for Pilot Name/Skills on:
- Mech
- Quad
- Tripod
> Print pilot names

- src/megameklab/com/ui/Mek/Printing/PrintMech.java
- src/megameklab/com/ui/Mek/Printing/PrintTripod.java
This will fix the printing issues on OS X reported in issue #23. There was an issue where trying to print from OS X was causing MML to crash. The problem seems to be that the Graphics2D.drawImage() calls in printMekImage() in both the PrintMech and PrintTripod classes were implemented incorrectly.  They included a parameter for color which was causing issues.  Updating these methods to use the correct method call fixes the issue.
> Fix for printing issue in issue #23.

- src/megameklab/com/ui/Mek/Printing/PrintMech.java
These comparisons will fail on case-sensitive filesystems.
I tested with both a Quad and regular Biped mech, and they both generated record sheets on Linux.
> Fix #35 by normalizing references to files to use the names of the data files

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/util/UnitUtil.java
The problem with jump jets and modular armor is that MML is reading the value in the `jumpMP` spinner as if it's the full unmodified number of JJs and setting the value on refresh to the reduced value. Every time it refreshes (twice every time something is added to the critical table) it removes a jump jet.
Rather that decide which it should be I added an additional set of text fields that shows the modified values, so the spinners only have to represent the base value. I also added tooltips to the modified MP text fields that show all modifiers (modular armor, hardened armor, shield, partial wing, MASC, supercharger).
> Jj and modular armor

- src/megameklab/com/ui/view/PlatoonTypeView.java
Apparently, java 9 can't cast an `int` to a `Comparable<?>`. The fix is to cast these as `Integer` instead.
> Fixes #96. Simple fix to allow MML to compile under Java 9.

- src/megameklab/com/ui/Dropship/tabs/TransportTab.java
- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
- src/megameklab/com/ui/view/BuildView.java
- src/megameklab/com/ui/view/CVChassisView.java
- src/megameklab/com/ui/view/CVTransportView.java
- src/megameklab/com/ui/view/listeners/CVBuildListener.java
- src/megameklab/resources/Views.properties
Added panel to vehicle structure tab for designating amount of cargo space, broken down by different cargo bay types. Omni vehicles can split space between fixed and pod-mounted. Moved troop space to transport panel.
This depends on the bay_construction_data branch of MM, in which the transport bay construction data that was part of TestAero was refactored into a separate class and modified for use by non-aerospace units.
> Fix for #136: 'Cargo Space' cannot be removed from canon units

- src/megameklab/com/util/ImageHelper.java
Check for fluff file relative to the installation directory first, then
relative to the fluff image directory, only defaulting to HUD image if
not found in either location.
Fixes #152: Mech Image not printing
> Fix for #152: Mech Image not printing

- src/megameklab/com/ui/Vehicle/views/CriticalView.java
Add a critical panel for assigning equipment to VTOL chin turret. VTOLs use the turret panel for rotor; VTOLs with a chin turret are treated like dual-turret tanks with the chin turret using the second turret position.
It seems to me this used to work, but I didn't see anything in the history that looks like it would have broken it.
> Fix for #153: Turret disappered

- src/megameklab/com/ui/Infantry/tabs/StructureTab.java
- src/megameklab/com/ui/view/BasicInfoView.java
Refreshes equipment tabs when tech parameters change (year, tech level, faction).
I also noticed by accident that loading foot rifle or mg platoons causes problems because the units have intro dates of 1900 and 1940 respectively, and the earliest date given by IO for equipment introduction is early spaceflight (ES), which it defines as 1950. This leaves the units with no available equipment, including no possible movement mode (which results in a thrown exception). I decided that in light of incompatible rules the least meddlesome hack is to set ES as the earliest possible date.
> Infantry fixes

- docs/history.txt
- src/megameklab/com/util/ImageHelper.java
If no fluff image is found for the model, check for generic chassis image for record sheet.
Issue reported here: https://bg.battletech.com/forums/index.php?topic=61783.msg1418023#msg1418023
> Use generic chassis image on RS if specific model not found.

- src/megameklab/com/ui/view/MekChassisView.java
Fixes #160: Industrial Mechs ICE engine Tech Progression Wrong.
> Include non-fusion in list of available engines for industrialmechs.

- src/megameklab/com/ui/view/MekChassisView.java
Reviewing the exception details from #142 it appears that `cbCockpit.setSelectedItem` was being called when there were no items left in the cockpit combo box.
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: setSelectedIndex: 0 out of bounds
at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
at megameklab.com.ui.view.MekChassisView.refreshCockpit(MekChassisView.java:533)
at megameklab.com.ui.view.MekChassisView.refresh(MekChassisView.java:392)
at megameklab.com.ui.view.MekChassisView.setFromEntity(MekChassisView.java:299)
at megameklab.com.ui.Mek.tabs.StructureTab.refresh(StructureTab.java:168)
at megameklab.com.ui.Mek.MainUI.refreshAll(MainUI.java:214)
at megameklab.com.ui.Mek.tabs.BuildTab.compactCrits(BuildTab.java:167)
at …
```
> Do not set selected item if there are no valid items in refreshCockpit

- src/megameklab/com/ui/Aero/tabs/EquipmentTab.java
- src/megameklab/com/ui/BattleArmor/tabs/EquipmentTab.java
- src/megameklab/com/ui/Infantry/views/WeaponView.java
- src/megameklab/com/ui/Mek/tabs/EquipmentTab.java
- src/megameklab/com/ui/Vehicle/tabs/EquipmentTab.java
The table sorter converts the string value for weapon damage to an int value (floating point for infantry) but does not account for all the available formats of the damage string. It can handle a numeric value or a set of damages by range separated by a slash.
This change truncates the string when the first non-digit value is reached before parsing. If there is no leading digit, it treats it as damage 0.
> Fix for sorting by damage in equipment tables

- src/megameklab/com/ui/Aero/views/BuildView.java
- src/megameklab/com/ui/Dropship/views/AerospaceBuildView.java
- src/megameklab/com/ui/Mek/views/BuildView.java
- src/megameklab/com/ui/Vehicle/views/BuildView.java
- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
Fix for #182 
When displaying unallocated equipment, any ammo that is unallocated and has a single shot is considered one-shot ammo and not displayed. This fails with Davy Crockett Arrow IV and cruise missile ammo, which have a single shot for a slot. Previously reported in #156 and fixed for fighters, meks, and vees by noting those specific exceptions, but I missed Dropships at the time. This includes Dropships/small craft and generalizes the solution to any ammo with 1 shot/slot rather than trying to make exceptions for all affected ammo types.
I also noticed that the weapons were not counting against the limit of 700 damage points per weapon bay and fixed that.
> Unallocated single shot ammo

- src/megameklab/com/util/UnitUtil.java
Unallocated ammo for large craft is grouped into single Mounteds for manageability, and it was being calculated as a single slot when computing the current construction weight.
> Fix for #195: Multiple Items of One Ammo Type Don't Add to Available Tonnage for Large Craft

- src/megameklab/com/ui/view/MekChassisView.java
It's not really clear what a Clan or IS tech base means in a mixed tech unit. There are entries in TROs that specify IS/mixed or Clan/mixed, but  the mixed tech rules (TacOps, p. 377) don't really make it clear whether that means anything, or whether they amount to the same thing. For the sake of simplifying the code and the available options, MML uses the IS/Clan tech base to filter the available structure types, but this causes problems when it comes to early Clan units by making IS endo steel unavailable when they should be able to use it. (For that matter, the Clans should be able to construct a mixed tech unit with IS endo steel at any point in their history.)
Given the choice between a hack to deal specifically with IS Endo-Steel and a more general solution that basically ignores …
> Make IS and Clan structure available to mixed tech units.

- src/megameklab/com/printing/PrintMech.java
In printed sheets produced by MegaMekLab, the weapon statistic lines below "Weapons & Equipment Inventory" (on the upper left of the sheet) are too close together, as it negatively impacts readability.
Significantly increasing line spacing would make the table much more legible, and it seems there is ample empty white space to allow for it.
> PrintMech: Weapons & Equipment Inventory table linespacing (fixes #186)

- src/megameklab/com/ui/Aero/views/BuildView.java
- src/megameklab/com/ui/Mek/views/BuildView.java
- src/megameklab/com/ui/Vehicle/views/BuildView.java
- src/megameklab/com/ui/aerospace/AerospaceBuildView.java
- src/megameklab/com/util/UnitUtil.java
I think this is at least the third fix in as many months for issues surrounding one-shot launcher ammo. Previously the check for whether an ammo slot is one-shot is that is located in Entity.LOC_NONE and has a single shot. This ran into problems with ammo that has a single shot when full not showing up because it hasn't been allocated. This fix is prompted by BA popup mines, which fail the one-shot test because they have one shot for each trooper.
This should be the final fix, which avoids all the edge case exceptions by testing whether the ammo mount is linked by a one-shot launcher. 
Fixes #213
> One shot reprise

- src/megameklab/com/ui/Aero/tabs/EquipmentTab.java
- src/megameklab/com/ui/BattleArmor/tabs/EquipmentTab.java
- src/megameklab/com/ui/Mek/tabs/EquipmentTab.java
- src/megameklab/com/ui/Vehicle/tabs/EquipmentTab.java
- src/megameklab/com/util/EquipmentTableModel.java
The weight of equipment for BA is shown as tons unless it's below 0.1 in which case it's shown as kg with the units as part of the value. So getValue was returning either a Double or a String, which was causing a ClassCastException when trying to find a natural comparator. I coerced all the values to Strings so that they could be compared, then set explicit sorters for all the unit types so they would sort by numeric value. For the BA equipment tab I added a custom comparator that would convert kg values to tons before comparing.
Fixes #214: Battle Armour Sorting Equipment by Weight
> Set comparator for sorting BA equipment tab by weight.

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
Fixes #215: Quadvees have issues with Quadvee cockpits and XL/XXL
engines.
> Restore qv cockpit when resetting system crits.

- src/megameklab/com/ui/Mek/views/BuildView.java
- src/megameklab/com/util/Mech/CriticalTransferHandler.java
When assigning splittable equipment using drag and drop it was comparing the number of slots available to the slots normally taken by the equipment instead of the slot taken by the equipment on that unit (which half as many for superheavies).
While troublshooting I also noticed that using the popup menu to place splittable equipment was only allocating a single slot when putting it in a single location and fixed that as well, along with some code cleanup.
Fixes #218
> Superheavy split equipment

- src/megameklab/com/ui/protomek/ProtomekStructureTab.java
Protomech engine rating is tonnage x running MP for bipeds, tonnage x (running MP - 2） for quads and gliders. The engine rating is recalculated after a change in tonnage or MP, but not chassis configuration.
Fixes #223: Quad Protomech engine weight
> Recalculate protomech engine rating after chassis configuration change.

- src/megameklab/com/util/RecordSheetEquipmentLine.java
Sets the long range for ATM Standard on printed record sheets to be 15, fixes #240
> Bug: Long range for ATM Standard incorrect on printed record sheets

- src/megameklab/com/ui/util/IntRangeTextField.java
- src/megameklab/com/ui/view/BasicInfoView.java
Copy-paste error results in setting the entity intro year instead of the manual BV.
Also fixes the inability to clear the manual BV other than explicitly setting it to < 0, which is non-obvious.
> Fix setting of manual BV.

- src/megameklab/com/ui/Aero/Printing/PrintAero.java
Fix for #238 
Band-aid rather than long term fix, but still an improvement. Armor layout is done by calculating all available pip positions and spreading the armor among them. When the amount of armor exceeds the number of available pip positions, the number of positions to advance between pips is calculated as zero and all the pips are drawn on top of each other. What I did is rework the layout code to use more space and simplify it. This doesn't remove the underlying problem that there is a maximum number of pips that can be drawn, but it increases the limit. The long-term solution is to move all units to the dynamic layout methods used when printing mech sheets, which can resize the pips as necessary to make them fit. But I haven't gotten to it yet.
> Asf armor pips

- src/megameklab/com/util/UnitUtil.java
It was checking whether there was a secondary location then iterating through the slots in the primary location again. This also fixes the potential for  an ArrayIndexOutOfBoundsException, if the secondary location has fewer slots than the primary.
Fixes #250: Armouring Split Components Shows and Counts Incorrect
Tonnage
> Fixed toggling of armored component slots for split equipment.

- src/megameklab/com/ui/Vehicle/Printing/PrintDualTurretVehicle.java
- src/megameklab/com/ui/Vehicle/Printing/PrintVehicle.java
- src/megameklab/com/ui/Vehicle/Printing/PrintWiGE.java
When printing two sheets per page the second one was being displayed in
all caps.
Fixes #254: Second Printed Vee Name in All Caps
> Consistent name display for vehicle record sheets.

- src/megameklab/com/printing/PrintMech.java
The new size was being assigned the intended ratio of new : old rather
than being multiplied by it.
Fixes #252: Heat Sink pips not printing properly
> Fixed rescaling of heat sink pips to fit in available space.

- src/megameklab/com/ui/Mek/views/BuildView.java
- src/megameklab/com/util/UnitUtil.java
Fixes bug that only allow LAMs to place ammo in left arm. This comes from it being identified as a fighter and restricting the ammo to the fuselage (Aero.LOC_FUSELAGE == Mech.LOC_LARM).
Also fixes a bug in assigning splittable equipment on LAMs, which I noticed while troubleshooting. Because LAMs are not allowed to split equipment between locations, the assignment follows a different path and misses the logic for assigning additional slots past the first one.
Fixes #260: Some issue to allocate the components of LAM
> LAM ammo assignments

- src/megameklab/com/ui/Aero/Printing/PrintAero.java
Fixes some unusual pip patterns from the changes in asf printing a few weeks ago that increases the maximum.
The algorithm that selects which of the possible pips to print spaces them somewhat proportionally along each row, assuming that the pips are ordered from one side to another. My recent change alternated them left and right from the centerline out,. If the selection algorithm determines that every other pip should be used (or every fourth, sixth, etc), all the pips are on the same side of the fighter. This reworks the layout to keep the larger maximum but lays each row out in a single direction.
> Adjustment to fighter nose armor pip layout.

- src/megameklab/com/ui/Aero/Printing/PrintAero.java
- src/megameklab/com/ui/Aero/Printing/PrintConventionalFighter.java
- src/megameklab/com/ui/Aero/Printing/PrintFixedWingSupport.java
- src/megameklab/com/ui/Aero/Printing/PrintSmallCraftAerodyne.java
- src/megameklab/com/ui/Aero/Printing/PrintSmallCraftSpheroid.java
- src/megameklab/com/ui/Dropship/Printing/PrintAerodyne.java
- src/megameklab/com/ui/Dropship/Printing/PrintSpheroid.java
Fixes #7: Pilot name printing on RSs
Aerospace record sheets (dropships, small craft, aerospace/conventional fighters, fixed wing support) all had the code that prints the pilot/crew name and skills copied from the old mech printing code, which has the wrong coordinates:
Fixed the coordinates to write the text in the correct location:
> Aero pilot/crew data on record sheets

- src/megameklab/com/ui/Aero/views/CriticalView.java
- src/megameklab/com/ui/aerospace/LargeCraftCriticalView.java
- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
- src/megameklab/com/util/UnitUtil.java
Adds button to side locations on aerospace units to copy the equipment loadout from the other side. Any equipment already in the side is removed if not needed. Any equipment not already present is created.
Partial implementation of #192
> Aero symmetry

- src/megameklab/com/ui/view/MovementView.java
Fixes #272: Modular Armor effectively prevents to put Jump Jet
> Ignore modular armor for base jump MP calculation.

- docs/history.txt
- src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java
- src/megameklab/com/ui/aerospace/AdvancedAeroUI.java
- src/megameklab/com/ui/aerospace/DropshipMainUI.java
- src/megameklab/com/ui/aerospace/DropshipStructureTab.java
- src/megameklab/com/util/UnitUtil.java
Fixes three closely-related issues:
1. Dropships and small craft get bonus armor from their SI to each location. This was including the non-armored system-wide location.
2. The above units as well as advanced aerospace units were having the number of bonus armor points added in twice when apportioning armor points using auto-allocate.
3. The auto-allocate code for JS/WS/SS was copied from SC/DS without being modified for the two extra armor locations, so side rear locations were not getting any armor beyond the bonus from SI.
Bonus issue, previously unreported: added logic to make sure that auto-allocate does not assign any values less than the minimum, which is the bonus provided by SI.
Fixes #267 
Fixes #276
> Large craft auto-allocate

- src/megameklab/com/printing/PrintEntity.java
When printing record sheets, ignoring pilot data should also extend to
calculating BV.
> Fix for #281

- src/megameklab/com/ui/Aero/tabs/StructureTab.java
- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
- src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java
- src/megameklab/com/ui/aerospace/DropshipStructureTab.java
- src/megameklab/com/ui/view/MovementView.java
When a change in unit type requires instantiating a new `Entity` the equipment tab does not refresh, so any equipment that might previously have been installed is not cleared from the table.
Fixes #299: Equipment tab does not refresh when unit type changes.
> Refresh equipment tab when new Entity is instantiated.

- src/megameklab/com/ui/BattleArmor/tabs/StructureTab.java
The armor type lookup method used by `BattleArmor#setArmorType(String)` prepends "IS" or
"Clan" to the armor name if not already present based on the armor tech
level. This makes it impossible to switch between IS and Clan armor, and
results in all kinds of problems if the selected armor type does not
exist for the previous tech base. Assigning the tech level first
resolves it.
Fixes #305: Mixed IS techbase & Clan BA Fire Resistant
> Set BA armor tech level before armor type.

- src/megameklab/com/ui/aerospace/TransportTab.java
Large craft parts changes removed a constructor used by MML.
> Fix transport tab broken by changes in DockingCollar.

- src/megameklab/com/ui/Aero/StatusBar.java
- src/megameklab/com/ui/Mek/StatusBar.java
- src/megameklab/com/ui/aerospace/AdvancedAeroStatusBar.java
- src/megameklab/com/ui/aerospace/DropshipStatusBar.java
- src/megameklab/com/util/EquipmentInfo.java
- src/megameklab/com/util/EquipmentTableModel.java
- src/megameklab/com/util/RecordSheetEquipmentLine.java
Requires MegaMek/megamek#1390.
1. Adds heat values for non-weapon equipment to the master equipment table.
2. Includes non-weapon equipment in the heat calculation in the status bar.
3. Adds heat value for non-weapon equipment to the equipment table on the record sheet.
Fixes #311
Best viewed with whitespace changes hidden.
> Report heat generation for non-weapon equipment.

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
When the number of weight-free heat sinks increases due to an engine change, add the additional heat sinks to the mech. This only affects mechs because aerospace fighters are all required to have fusion engines and the weight-free value doesn't change.
The reported bug stems from the value in the spinner being below the minimum.
Fixes #319: Cannot add heat sinks after changing engine type
> Adjust heat sink count when required by engine change.

- src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java
The max number of docking hardpoints may have changed and needs to be updated.
> Refresh transport tab after tonnage or type change.

- src/megameklab/com/ui/Mek/views/BuildView.java
- src/megameklab/com/util/Mech/CriticalTransferHandler.java
- src/megameklab/com/util/UnitUtil.java
Heavy Gauss and Improved Heavy Gauss rifles can only be mounted in torso locations on 'Mechs (unless superheavy), front/rear on vehicles, and nose/aft on fighters. I've added these checks to UnitUtil#isValidLocation and added calls to check location validity when placing equipment both via popup menu and via drag and drop.
Fix for #324
> Prevent placing heavy gauss in arm locations

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
The number of heat sinks in an omni's base chassis that don't have to be assigned critical slots is stored in the engine. This has to be tracked because pod-mounted heat sinks always have to be assigned critical slots, even if the engine rating is large enough they wouldn't have to in a non-omni.
When the engine changes due to engine type change (e.g. standard -> XL) or change in MP, the base chassis heat sink value is copied over. This has not been happening when the tonnage changes.
Fixes #325
> Maintain base chassis heat sink count when tonnage changes.

- src/megameklab/com/ui/Aero/Printing/PrintAero.java
Only a fraction of pips are printing.
The logic is that all the possible pip positions are determined, then the actual pips that are drawn are spaced proportionally among them. What is happening is that only a number of pips equal to the wing armor are being laid out, but the number of those that are shown is still determined by the proportion of the armor points to the total that fit in the space.
Fixes #333
> Fix logic error in aero wing armor pip layout.

- src/megameklab/com/util/UnitUtil.java
The location test for physical weapons is checking whether the mech is industrial instead of checking the equipment.
Fixes #336:  Quad Battlemechs are unable to allocate industrial physical
weapons to their side torsos
> Allow quad mech to mount industrial equipment.

- resources/megameklab/resources/Menu.properties
- src/megameklab/com/util/MenuBarCreator.java
Replaces use of Swing's cross-platform JFileChooser with the AWT FileDialog, which uses the OS-native dialog. This was already being used for saving and for opening fluff images.
This might best be reviewed one commit at a time. The first was a code cleanup. The next (after the upstream merge) involved tokenizing all the string literals. The third replaced the dialog.
I looked at replacing the cross-platform print dialog with a native one but that is a bit more involved and best left as a separate change.
Fixes #174
> Native dialogs

- src/megameklab/com/ui/Aero/tabs/EquipmentTab.java
- src/megameklab/com/ui/BattleArmor/tabs/EquipmentTab.java
- src/megameklab/com/ui/Mek/tabs/EquipmentTab.java
- src/megameklab/com/ui/Vehicle/tabs/EquipmentTab.java
- src/megameklab/com/ui/tabs/EquipmentTab.java
Fix for #341
The comparator used for sorting equipment by weight and BV is converting the formatted Strings to int rather than floating point.
I considered factoring out the comparators that are duplicated in equipment tab views for several unit types, but that should be taken care of by eventually replacing the individual EquipmentTab classes with the EquipmentTab that's used for the past 3-4 unit types that have been implemented. It just needs to be updated to include special considerations for the remaining unit types. That's a separate issue.
> Fix for sorting equipment table by tonnage/BV

- src/megameklab/com/ui/view/MekChassisView.java
Enables construction of superheavy industrialmechs.
I just missed this one when I was redesigning the mech structure tab.
Fixes #347
> Allow superheavy industrial mechs

- src/megameklab/com/ui/view/MekChassisView.java
What I have missed on #346.
Although Small Command Console was implemented, without it mechs are not able to choose Small Command Console. The others are fine - #346 already did for Superheavy and industrial mech, but most mechs are have the consoles defined in GENERAL_COCKPITS and Small Command Console was not included.
> Add Small Command Console to the general cockpits

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/view/MekChassisView.java
Fixes #352 
Large engines (rating > 400) occupy more critical slots and may need to punt equipment that has previously been installed there. The call to resetSystemCrits was missing in the method that recalculates engine rating. There was also a bug that assumed the large engine flag was set correctly in the engine combo box, but this was not always true. Also, superheavy mechs were reserving four slots for the gryo, when then should only be requiring two double slots.
> Large engine crits

- src/megameklab/com/MegaMekLab.java
- src/megameklab/com/ui/MegaMekLabMainUI.java
The code moved only needs to run once, when the application is first launched. Having it in MegaMekLabMainUI caused it to run every time the unit type is changed. This doesn't hurt anything, but CConfig does need to initialize before calling setLookAndFeel().
> Move some initialization code earlier in the sequence.

- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
- src/megameklab/com/ui/supportvehicle/SVArmorTab.java
- src/megameklab/com/ui/supportvehicle/SVBuildTab.java
- src/megameklab/com/ui/supportvehicle/SVStructureTab.java
- src/megameklab/com/ui/view/CVChassisView.java
- src/megameklab/com/ui/view/SVChassisView.java
I made some changes that allows SV customizations in the MekLab tab of MekHQ. This mostly involves changing visibility modifiers to public, but also adds a setAsCustomization() method that MekHQ uses to signal that certain options such as tonnage and motive type cannot be changed. I did this for combat vehicles as well, but other unit types have it implemented.
> SV MekHQ compatibility

- src/megameklab/com/ui/MegaMekLabMainUI.java
Write MM preferences when exiting. This has the effect of saving the choices in the unit selector dialog between sessions.
> Keep unit selector dialog settings between sessions.

- src/megameklab/com/ui/protomek/ProtomekMainUI.java
- src/megameklab/com/ui/tabs/FluffTab.java
Adds a fluff tab for protomechs, which somehow got left out. Also removes some unused code in FluffTab - since the system text fields are identified by the component name there's no reason to track them in a map.
Fixes #365
> Protomek fluff

- src/megameklab/com/printing/PrintMech.java
- src/megameklab/com/printing/PrintRecordSheet.java
- src/megameklab/com/util/StringUtils.java
There are some variations in the way text appears on record sheets which may be due to PDF print driver or differences in OS sizing the text differently. What works fine on my system is too large to fit in the available space when @HammerGS prints.
I've made the following changes to address this:
1. When positioning the "(CASE)" indicator, take into account that the location name is bold and takes up more space.
2. After calculating the size of font to use for the critical slots (as a proportion of the space available for the section), round it down. This seems to fix the differences in font sizes, which I suspect comes from a system call.
3. Fix a similar issue in the equipment table by making sure there is space between the Dmg and Min columns.
4. Trim leading and trailing spaces in the …
> 'Mech record sheet layout tweaks

- src/megameklab/com/ui/supportvehicle/SVStructureTab.java
- src/megameklab/com/ui/view/ChassisModView.java
Fixes #367
When checkboxes for SV chassis mods are selected programatically to fulfill construction rules the mod is not actually being added to the vehicle. This is because JCheckbox::setSelected does not fire an ActionEvent. It does fire an ItemEvent whether toggled by the user or programatically, so I changed the listener type.
I also noticed that changing between MagLev and other engine types, the movement mode does not get changed. The same goes for hydrofoil or submersible chassis mods for naval support vehicles.
> Install automatic SV chassis mods

- src/megameklab/com/util/UnitUtil.java
When copying equipment from one side of an aerospace unit to the other, check that the critical slot exists and contains equipment before trying to copy it.
Fixes #369
> Fix for NPE in aero mirroring

- src/megameklab/com/ui/dialog/LoadingDialog.java
The LoadingDialog constructor ignores the primitive and industrial parameters, preventing the user from switching the unit type to primitive.
Fixes #376
> Restore ability to switch to primitive

- src/megameklab/com/ui/view/PatchworkArmorView.java
When using patchwork armor on a mixed tech unit, armor types that differ by tech base (e.g. IS vs. Clan Ferro-fibrous) aren't showing the tech base in the combobox for the armor type for the location.
Also include aero fuselage in locations to be skipped when assigning patchwork.
> Show patchwork armor tech base when unit is mixed tech.

- src/megameklab/com/ui/Vehicle/tabs/EquipmentTab.java
The check for armored chassis that I removed is not needed, since it gets filtered out by UnitUtil#isTankEquipment anyway. It has the side effect of filtering out MPods also, since MiscType.F_ARMORED_CHASSIS and WeaponType.F_M_POD have the same value and it doesn't check whether the equipment is MiscType.
Fixes #388
> Remove unused block that was incorrectly filtering out mpod.

- src/megameklab/com/ui/BattleArmor/views/BuildView.java
- src/megameklab/com/util/UnitUtil.java
The table for unallocated BA equipment prevents showing the zero-slot BA Standard armor by filtering out any equipment with a name that contains the String "BA Standard" instead of just checking for criticals == 0. This also filters out the 4-slot BA Standard (Prototype). During testing I noticed that the table was showing that each slot of BA stealth armor requires two slots. I tracked this to handling of 'Mech stealth armor, which requires two slots per location. This has no effect on how the slots were actually allocated, but is confusing.
Best viewed with whitespace changes hidden.
Fixes #391
> Show BA Standard (Prototype) slots for allocation.

- src/megameklab/com/util/UnitUtil.java
As clarified in the errata to IO, the armor points for a primitive jumpship are calculated as for standard armor, then rounded down, then the primitive multiplier of 0.66 is applied, then rounded down again. The free armor points gained from SI are rounded normally as for standard advanced aero, but the 0.66 mulitplier is applied to that value as well and rounded down. The way MML currently does it is by applying the primitive factor to the standard points per ton then rounding once, but this can carry over enough accumulation of fractional amounts to result in an extra point or two. The double rounding required special handling.
Neither IO nor the errata address the method used for dropships, but since IS standard armor is always an even whole number per ton, each half ton lot is a whole …
> Fix primitive jumpship armor rounding per errata.

- resources/megameklab/resources/Views.properties
- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
- src/megameklab/com/ui/view/CVChassisView.java
- src/megameklab/com/ui/view/MovementView.java
- src/megameklab/com/ui/view/listeners/CVBuildListener.java
Adds two checkboxes to the chassis section of the combat vehicle structure tab. One designates the vehicle as a trailer (only enabled when motive type is wheeled or tracked) and the other allows the trailer to be built without control systems to save weight (only enabled if trailer is checked). Trailers have a minimum of 0 MP and can be built with no engine.
Closes #316
> Cv trailers

- .gitignore
- resources/megameklab/resources/Dialogs.properties
- src/megameklab/com/MegaMekLab.java
- src/megameklab/com/util/ConfigurationDialog.java
@HammerGS discovered that on Windows the font selection combo box does not necessarily show all fonts installed on the system. I was not able to determine the reason (hampered by not having a Windows system to experiment with) but I found a solution involving recursively searching the data/fonts directory for any *.ttf files and registering them with the graphics environment. This also allows use of a font for printing record sheets without installing it on the system (for whatever reason someone might want to do that). I also took the precaution of adding data/fonts to .gitignore to prevent accidentally committing proprietary font files.
> External fonts

- src/megameklab/com/util/UnitUtil.java
Per TacOps, p. 282: "Any component on a unit’s Critical Hit Table can be armored except for ammunition bins, CASE and other items that have a “roll again” effect (such as Ferro-Fibrous Armor slots)."
I simplified the check to follow this rule. The current implementation leaves some things out and also includes some equipment, such as shields and spikes, which are not excluded by either the armored component rules or by their own.
Fixes #418.
> Simplified check for armored component eligibility.

- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
The superheavy checkbox is cleared whenever it is set because the VTOL tonnage is not being adjusted to within the superheavy range.
Fixes #420
> Adjust VTOL weight when toggling superheavy

- src/megameklab/com/ui/BattleArmor/tabs/StructureTab.java
If a change in the tech base, tech level, or construction year means the previously selected armor type is not available, the armor type is updated to whatever is first in the new list.
Fixes #421.
> Check for BA armor mismatch when tech base/level/year changes.

- .gitignore
- build.gradle
- src/megameklab/com/MegaMekLab.java
- src/megameklab/com/ui/Aero/StatusBar.java
- src/megameklab/com/ui/BattleArmor/MainUI.java
- src/megameklab/com/ui/BattleArmor/StatusBar.java
- src/megameklab/com/ui/Infantry/views/ArmorView.java
- src/megameklab/com/ui/Infantry/views/SpecializationView.java
- src/megameklab/com/ui/Mek/MainUI.java
- src/megameklab/com/ui/Mek/StatusBar.java
- src/megameklab/com/ui/StartupGUI.java
- src/megameklab/com/ui/Vehicle/MainUI.java
- src/megameklab/com/ui/Vehicle/StatusBar.java
- src/megameklab/com/ui/Vehicle/views/WeaponView.java
- src/megameklab/com/ui/aerospace/AdvancedAeroStatusBar.java
- src/megameklab/com/ui/aerospace/DropshipStatusBar.java
- src/megameklab/com/ui/protomek/ProtomekStatusBar.java
- src/megameklab/com/ui/supportvehicle/SVMainUI.java
- src/megameklab/com/ui/supportvehicle/SVStatusBar.java
- src/megameklab/com/ui/tabs/EquipmentTab.java
- src/megameklab/com/ui/tabs/PreviewTab.java
- src/megameklab/com/ui/view/ArmorAllocationView.java
- src/megameklab/com/util/CriticalTableModel.java
- src/megameklab/com/util/EquipmentTableModel.java
This expands the theme support in MML to support dark themes and reworks most of the underlying controls to be look-less to ensure they display correctly under each theme. This isn't 100% perfect, but pretty close for an hour of work.
> Expand theme support and include dark themes

- resources/megameklab/resources/Views.properties
- src/megameklab/com/printing/PrintMech.java
- src/megameklab/com/ui/Aero/tabs/StructureTab.java
- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/Mek/views/BuildView.java
- src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java
- src/megameklab/com/ui/aerospace/DropshipStructureTab.java
- src/megameklab/com/ui/view/HeatSinkView.java
- src/megameklab/com/ui/view/listeners/BuildListener.java
- src/megameklab/com/util/UnitUtil.java
For Mechs: adds a spinner to the heat sink view, visible when either prototype double heat sink option is selected, to indicate how many of the installed heat sinks are prototype doubles. The function of the main spinner remains the same, to select the total number of heat sinks. Prototype doubles must always be assigned to critical slots, regardless of the capacity of the engine for slot-free heat sinks.
For aerospace units that use heat sinks: MM does not have a way as this time to split heat sinks between singles and prototype doubles. Unless or until such support is added, the heat sink view does performs a parlor trick to make prototype doubles available when the year and tech level allows them but not true doubles, but the Aero itself treats them like any other double heat sink. …
> Prototype double heat sinks

- src/megameklab/com/util/UnitUtil.java
It took me over an hour to hunt this down. When a mech is loaded into MML the spreadable mounts (endo-steel, TSM, etc) get reworked from a single mount linked from multiple slots to multiple single-slot mounts so they can be reallocated. The loop that does this assumes that the left leg is the last location, so any spreadable equipment in the center leg gets removed from the equipment list, leaving the critical slot in the leg pointing to an orphaned mount.
Fixes #430
> Include tripod center leg when expanding spreadable equipment mounts.

- src/megameklab/com/ui/tabs/EquipmentTab.java
The exclusion of MASC from the equipment list was also excluding the VTOL jet booster. I added an exclusion for both the master equipment list and the installed equipment table.
Fixes #450
> Include VTOL jet booster on SV equipment tab.

- src/megameklab/com/ui/BattleArmor/tabs/EquipmentTab.java
- src/megameklab/com/ui/BattleArmor/views/EquipmentView.java
- src/megameklab/com/ui/Vehicle/tabs/EquipmentTab.java
- src/megameklab/com/ui/Vehicle/views/EquipmentView.java
- src/megameklab/com/util/UnitUtil.java
Improves filtering in the combat and support vehicle equipment tables to remove equipment that is ineligible based on motive type. Also removes deprecated, redundant, and/or conflicting methods from UnitUtil. Two of the files updated have line ending changes are best viewed with whitespace changes hidden.
Fixes #440
> Filter vehicle equipment tables by motive type

- src/megameklab/com/ui/Aero/tabs/BuildTab.java
The reset button on the aerospace fighter build tab is removing all equipment, including squadron weapon groups, which creates phantom weapons that can't be reinstalled. Equipment with a fixed location, such as ammo, should also not be removed when resetting.
This file was apparently CR/LF before.
Fixes #461
> Skip weapon groups and fixed location equipment when resetting crits

- src/megameklab/com/util/DropTargetCriticalList.java
The rules for pintle mounts (TM, 234) say they can be used for any side-mounted equipment, and only forbid heavy weapons. Since pintle mounts are only available to small support vehicles and small SVs can't use heavy weapons, that restriction is applied implicitly. Less clear is what can be placed in a sponson turret mount (TO, 346, 348). The description says they are larger versions of the pintle mount, but the construction rules only refer to weapons. I thought it better to be less retrictive, since there are a few examples of weapon-like that are not implemented as weapons in MM, such as sprayers and spot welders.
Fixes #463
> Non-weapon equipment in pintle and sponson mounts

- src/megameklab/com/ui/BattleArmor/tabs/StructureTab.java
- src/megameklab/com/ui/Infantry/tabs/StructureTab.java
- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
- src/megameklab/com/ui/protomek/ProtomekStructureTab.java
- src/megameklab/com/ui/supportvehicle/SVStructureTab.java
- src/megameklab/com/ui/tabs/PreviewTab.java
- src/megameklab/com/util/RefreshListener.java
Recalculate the composite tech advancement and availability codes for the unit based on parts and construction options. Add a preview refresh when tech base/tech level/year changes for those unit types that don't already do it.
Fixes #466
> Update unit tech advancement when preview refreshes.

- src/megameklab/com/ui/Aero/StatusBar.java
- src/megameklab/com/ui/BattleArmor/MainUI.java
- src/megameklab/com/ui/BattleArmor/StatusBar.java
- src/megameklab/com/ui/Infantry/StatusBar.java
- src/megameklab/com/ui/Mek/StatusBar.java
- src/megameklab/com/ui/Vehicle/MainUI.java
- src/megameklab/com/ui/Vehicle/StatusBar.java
- src/megameklab/com/ui/aerospace/AdvancedAeroStatusBar.java
- src/megameklab/com/ui/aerospace/DropshipStatusBar.java
- src/megameklab/com/ui/protomek/ProtomekStatusBar.java
- src/megameklab/com/ui/supportvehicle/SVMainUI.java
- src/megameklab/com/ui/supportvehicle/SVStatusBar.java
Currently the title bar shows "(invalid)" after the file name in the title bar, but only for some unit types and only updates when the chassis or model name changes. Rather than implement it with the remaining unit types and adding `refresh.refreshHeader()` calls all over the place, I moved it to the status bar where I think it more naturally belongs. It will also set the tooltip to indicate why it's flagged as invalid.
Then I did some removing of redundant casts and converting member fields to local variables.
Fixes #471
> Add "invalid" indicator to status bar

- src/megameklab/com/ui/Aero/tabs/EquipmentTab.java
- src/megameklab/com/ui/BattleArmor/tabs/EquipmentTab.java
- src/megameklab/com/ui/Mek/tabs/EquipmentTab.java
- src/megameklab/com/ui/Vehicle/tabs/EquipmentTab.java
- src/megameklab/com/util/UnitUtil.java
There's even an argument to ignore oneshot. It just wasn't being used for most unit types.
Fixes #479
> Ignore OS launchers when filtering ammo on equipment tab.

- src/megameklab/com/ui/Vehicle/tabs/EquipmentTab.java
- src/megameklab/com/util/UnitUtil.java
The VTOL jet booster disappears from the installed equipment on the equipment tab during refresh because it's falsely being flagged as MASC. But the most of the equipment that gets filtered out in that block is only relevant to mechs, and this class only handles vehicles, so those checks are redundant. 
This is the second time recently I've found the check for MASC including a jet booster when it shouldn't so I went looking for other places that superchargers are excluded but jet boosters aren't and I found another case in the method that removes equipment that is invalid for the year/tech base/tech level. This time the check is letting jet boosters slip through.
Fixes #483
> Disappearing jet booster

- build.gradle
When I replaced deprecated field names I didn't realize that they also changed from strings to properties, which require the `get()` method to access the string value. Expressions that evaluated to MegaMekLab.jar and MegaMek.jar under 4.9 are now evaluating as MegaMekLab.property(class java.lang.String, fixed(class java.lang.String, jar), which is causing problems in the start script and the classpath in the jar manifests. I also got carried away and added one too many megamek subdirectories. My previous testing only went as far as making sure the distribution packages built. This time I extracted the package and made sure it runs.
Fixes #482
> Gradle properties

- src/megameklab/com/ui/BattleArmor/tabs/EquipmentTab.java
- src/megameklab/com/util/EquipmentTableModel.java
- src/megameklab/com/util/UnitUtil.java
Depends on MegaMek/megamek#1715
1. Makes a distinction between equipment that has a weight/cost/BV/critical slots requirement of zero and equipment that is variable.
2. BA, ProtoMechs, and small support vehicles show equipment weight by kg for everything rather than just what is < 0.1 tons. Anything >= 5 tons is filtered out for small support vehicles.
3. Equipment shown as kg is shown as a whole number, with the exception of BA ammo, has official weights of partial kg.
4. Fixed a bug introduced in my last equipment tab fix that had ammo, weapons, and structural components showing on the BA equipment tab in the "other" category.
Fixes #487
> Indicate variable equipment stats

- src/megameklab/com/util/CriticalTableModel.java
- src/megameklab/com/util/EquipmentTableModel.java
MegaMek/megamek#1720 changed the name of the getTankSlots method to standard camelCase.
> Method name change

- src/megameklab/com/util/DropTargetCriticalList.java
Armored components are only available to BattleMechs and IndustrialMechs, per TO, p. 283.
I also changed the tech level check to verify intro year and use variable tech levels if enabled.
Fixes #498
> Restrict armored components to mechs.

- src/megameklab/com/ui/view/CVChassisView.java
- src/megameklab/com/ui/view/SVChassisView.java
Per TacOps, p. 347 (2018 printing), WiGE vehicles cannot mount dual turrets. This is a change from previous printing.
Fixes #505
> No dual turrets for WiGE vehicles.

- src/megameklab/com/ui/supportvehicle/SVStructureTab.java
- src/megameklab/com/util/UnitUtil.java
Remove supercharger from equipment list for support vehicles with solar or external engines. Restrict rail external power pickup to vehicles with external engine.
Along with MegaMek/megamek#1725 fixes #497
> Supercharger restrictions

- src/megameklab/com/ui/tabs/TransportTab.java
The transport tab currently only allows setting the size of the bay by capacity. This is in keeping with the way unit bays are set (2 mech bays rather than 300 tons of mech bays), but less useful for cargo bays, where you're probably more likely to add a liquid cargo bay, for instance, that weighs 10 tons rather than a bay with 9.1 tons capacity. I made the tonnage column editable for cargo bays so you can choose either capacity or total weight.
Closes #465
> Set cargo bay size by weight or capacity

- src/megameklab/com/ui/tabs/EquipmentTab.java
- src/megameklab/com/util/EquipmentTableModel.java
The generic equipment tab, which is used for protomechs and support vehicles (and my intention is to consolidate all units into the same tab instead of duplicating the same code all over the place)...where was I?
Right. The generic tab didn't have a specific Comparator for the weight column, which resulted in sorting by string value. I added the Comparator for formatted numbers and added the ability to recognize the difference between weights in tons and kg, as well as treating all variable weight equipment as zero.
Fixes #502
> Add sorting by weight to generic equipment tab

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
- src/megameklab/com/util/UnitUtil.java
Companion of MegaMek/megamek#1734
Helpfully filters external fuel tanks from the equipment list for non-industrial mechs or any unit without a combustion or fuel cell engine. Limits placement in IndustrialMechs to the torso locations.
I discovered a misplaced closing brace in UnitUtil#isValidLocation and fixed it. That is likely at least part of the cause of #500.
> External fuel tank filtering

- src/megameklab/com/util/Mech/DropTargetCriticalList.java
- src/megameklab/com/util/UnitUtil.java
The number of heat sinks and jump jets is set on the structure tab. Letting them be deleted on the build tab causes problems. I also discovered quite by accident during testing that UnitUtil#isJumpJet does not check for instanceof MiscType, which causes a false positive on lasers, because MiscType.F_JUMP_JET == WeaponType.F_LASER.
I also found another file that had CR/LF endings.
Fixes #501
> Don't allow deleting heat sinks or jump jets on the build tab.

- src/megameklab/com/util/MenuBarCreator.java
Also replace potentially illegal filename characters when constructing the default file name. The Windows set is a superset of illegal filesystem characters on EXT3 and APFS, so it should cover Linux and OSX as well and create filenames that are interchangeable.
Fixes #517
> Use correct extension for unit type when loading from a zip file.

- src/megameklab/com/ui/Aero/StatusBar.java
- src/megameklab/com/ui/BattleArmor/StatusBar.java
- src/megameklab/com/ui/Infantry/StatusBar.java
- src/megameklab/com/ui/Mek/StatusBar.java
- src/megameklab/com/ui/Vehicle/StatusBar.java
- src/megameklab/com/ui/aerospace/AdvancedAeroStatusBar.java
- src/megameklab/com/ui/aerospace/DropshipStatusBar.java
- src/megameklab/com/ui/protomek/ProtomekStatusBar.java
- src/megameklab/com/ui/supportvehicle/SVStatusBar.java
This little indicator that now shows up in the status bar also has a tooltip that lists all the reasons the unit is flagged as invalid. But they are currently shown on a single line. So I added line breaks to make it more useful.
> Add line breaks to invalid indicator tooltip.

- src/megameklab/com/util/UnitUtil.java
When the combo box for mech myomer/MASC is changed, the previous enhancement is supposed to be removed. It is not removing MASC because the check for MASC expects the MiscType to have a subtype of S_STANDARD, but that flag is intended for jump jets and has the same value as S_SUPERCHARGER.
Fixes #545
> Fix check for MASC

- src/megameklab/com/util/UnitUtil.java
I touched this a month or so ago to deal with inability to remove spreadable equipment slots from a tripod center leg and didn't notice that it had <= instead of <. This doesn't usually cause a problem because Entity#getNumberOfCriticals returns 0 for non-existent locations and the inner loop is skipped with the invalid index. But LAMs have virtual locations for weapon groups that allow them to be included in capital fighter squadrons, and they enter the inner loop and throw an exception.
Fixes #553
> Fix bounds on location iteration when expanding equipment mounts.

- build.gradle
Removes the explicit declaration of the log4j dependency, which is inherited from the MM dependency. This avoids potential library conflicts if the version is changed in one but not the other.
Also adds `test` as a dependency of the `assembleDist` Gradle task to ensure unit tests must pass before the `release` task can run. MML.
> Dependency update

- src/megameklab/com/util/UnitUtil.java
All the work I did filtering the equipment table was focused on MiscType and WeaponType and I didn't pay attention to AmmoType. Since the filtering method is based on white-listing approved equipment, AmmoType gets filtered out. I changed it to white-list ammo automatically at this stage, since the actual ammo filtering is done later in the process.
Fixes #555
> Don't flag ammo as invalid for support vehicles.

- src/megameklab/com/util/UnitUtil.java
VTOLs with more than two points of armor on the rotors already fail validation, but this enforces the maximum in the armor points spinner.
Closes #581.
> Limit VTOL rotor armor to two points.

- src/megameklab/com/ui/tabs/TransportTab.java
Fixes two bugs introduced by adding the option to set cargo bay size by capacity or overall bay tonnage.
1. The size spinner uses a step size of 1,000 kg instead of 1 kg.
2. The minimum size is also set to 1,000 kg, which throws an exception if the bay size is less than that.
3. Unit transport bays have the same 0.5 step size as cargo bays, allowing you to add half a cubicle.
I also filtered out all non-cargo bays for units using the kg standard (i.e. small support vehicles) since they exceed the maximum tonnage for those units.
Fixes #583
Fixes #587
> Transport tab fixes

- src/megameklab/com/util/UnitUtil.java
Companion of MegaMek/megamek#1881.
Treats fixed wing support vehicles as support vehicles rather than aerospace units when determining which equipment is eligible, per construction rules.
Fixes #539.
> Fixed wing support vehicle equipment filtering

- src/megameklab/com/ui/supportvehicle/SVArmorTab.java
Some of the armor is getting allocated to the LOC_WINGS, which makes it vanish. I didn't account for fixed wing support vehicles having a wings since they can't be part of a capital fighter squadron. It may make it easier to load and initialize them to treat them like fighters. In any case my experience with adding a fuselage/hull location to aerospace units tells me it's better to leave it alone and work around it.
Fixes #538.
> Fix automatic armor allocation on fixed wing support vehicles

- src/megameklab/com/ui/view/ArmorAllocationView.java
If the minimum armor changes (e.g. for automatic armor from SI) the values for allocated, unallocated, and total armor can change. These aren't needed when updating the individual armor location spinners, so they can be moved until after the loop and reflect any changes.
Fixes #541.
> Update total allocated and unallocated armor after updating locations

- src/megameklab/com/ui/tabs/TransportTab.java
The listener is currently only being added for support vehicles, which means that small craft do not get updated.
Fixes #542
> Add listener to infantry compartment spinner for all units.

- src/megameklab/com/ui/tabs/TransportTab.java
This fixes an odd interaction on the transport tab that has the menu showing behind the infantry compartment labels (may depend on screen size).
> Replace AWT Label with Swing JLabel

- src/megameklab/com/ui/tabs/TransportTab.java
This is done for small craft and dropships, but not advanced aerospace units. Though bay personnel are not considered in minimum crew or accomodations calculations, they are included in Aero#getNCrew.
Fixes #552
> Update crew size when adding or removing a bay

- src/megameklab/com/printing/InventoryWriter.java
Somehow I never noticed it was doing this.
Fixes #598
> Don't show capital fighter weapon groups on record sheet

- src/megameklab/com/ui/aerospace/AdvancedAeroStructureTab.java
- src/megameklab/com/ui/aerospace/DropshipStructureTab.java
- src/megameklab/com/ui/view/MVFArmorView.java
The maximum armor tonnage on non-fighter aerospace units is determined by the SI. When the SI changes (either directly or through increasing the thrust value) the armor tonnage spinner isn't being updated. This PR adds an update to the armor panel when the SI changes (works whether direct or indirect), and also reducing the armor tonnage when an SI reduction drops the maximum below the current value.
Fixes #543
> Update armor panel when SI changes

- src/megameklab/com/ui/view/MVFArmorView.java
- src/megameklab/com/ui/view/PatchworkArmorView.java
Companion to MegaMek/megamek#1895, reflecting the API changes.
> Remove standard armor from primitive jumpship options.

- src/megameklab/com/ui/tabs/EquipmentTab.java
- src/megameklab/com/ui/util/CustomComboBox.java
This fixes one combo box rendering issue that I observed and probably another that has been reported that I was not able to duplicate. On my machine using the GTK+ theme, the category selection ComboBox does on the equipment tab used by protomechs and support vehicles does not display the selected item in the list when it is visible. I fixed this by setting the opaque field of the cell renderer to the same value as the List component. A similar issue of disappearing text has been reported for many of the ComboBoxes on the structure tab, which I was not able to reproduce. But I assume that setting the opacity and the foreground and background colors will resolve that as well.
(Presumably) fixes #546
> Fix appearance of custom combo box list renderers.

- data/images/recordsheets/naval_dualturret_standard.svg
- data/images/recordsheets/naval_dualturret_superheavy.svg
- data/images/recordsheets/naval_noturret_standard.svg
- data/images/recordsheets/naval_noturret_superheavy.svg
- data/images/recordsheets/naval_turret_standard.svg
- data/images/recordsheets/naval_turret_superheavy.svg
- data/images/recordsheets/submarine_dualturret_standard.svg
- data/images/recordsheets/submarine_dualturret_superheavy.svg
- data/images/recordsheets/submarine_noturret_standard.svg
- data/images/recordsheets/submarine_noturret_superheavy.svg
- data/images/recordsheets/submarine_turret_standard.svg
- data/images/recordsheets/submarine_turret_superheavy.svg
- data/images/recordsheets/tables_tank.svg
- data/images/recordsheets/tables_vtol.svg
I couldn't reproduce the issue, but going over the template generation code I found a bug that does not include fixed lengths for the segments of text in the last line of a paragraph when it includes normal and italic text. I am confident that this resolves the issue.
I also discovered several places where "inflict[ed]" is missing the L and "modifier" is missing the second I. I suspect that this is due to the way the TM PDF handles fl and fi ligatures, since I copied the text from the PDF (ironically) to avoid typos.
I'm not sure how to advise reviewing machine-generated files. There are some additional changes due to modifications of the generation code in the process of making the templates for conventional infantry and BA.
Fixes #616
> Fix text overlap in vehicle record sheet tables

- src/megameklab/com/printing/PrintRecordSheet.java
When the equipment name has consecutive spaces, the method that breaks long names into multiple lines never ends. The method also needed some better internal documentation.
Fixes #622
> Fix endless loop in record sheet printing

- src/megameklab/com/printing/PrintAero.java
I don't see a good way to add places to record the second pilot's name, stats, and damage track for a command console. The mech sheet makes room for additional crew by shrinking the fluff image, but the fighter sheet has a different layout. I think it's enough to indicate on the sheet that it has a command console (or small cockpit). There's enough white space to make the additional notes.
Fixes #625
> Show cockpit type on fighter record sheet if non-standard

- resources/megameklab/resources/Dialogs.properties
- src/megameklab/com/printing/InventoryWriter.java
- src/megameklab/com/printing/PrintEntity.java
- src/megameklab/com/printing/RecordSheetOptions.java
- src/megameklab/com/util/CConfig.java
- src/megameklab/com/util/ConfigurationDialog.java
Adds an option to the printing tab of the configuration dialog that will show total weapon heat and dissipation below the equipment list on mech and asf record sheets. Also removes the outdated message that the printing options only apply to mechs.
Examples:
[Kintaro KTO-18P.pdf](https://github.com/MegaMek/megameklab/files/4679864/Kintaro.KTO-18P.pdf)
[Chippewa CHP-W8.pdf](https://github.com/MegaMek/megameklab/files/4679865/Chippewa.CHP-W8.pdf)
Closes #227
> Option to show total heat and dissipation on record sheet

- src/megameklab/com/printing/PrintMech.java
This fixes two edge cases on the brackets that group multiple slots of a single piece of equipment on mech record sheets.
The first is an edge case that only shows up when the following conditions are met:
1. There is a piece of equipment that takes a fixed number of slots in multiple locations (such as partial wing or mech tracks)
2. It takes up one slot per location
3. It is hittable
3. It doesn't occupy the last slot
The bug stems from using the total number of slots to determine whether it needs to be bracketed, which isn't necessarily the number of slots in the current location. Instead I'm using the offset from the index of the first slot.
The second occurs when the last slot is occupied by a single-slot item that has another in the same location. This is because it counts the …
> Fixes for grouping slots on mech record sheets

- src/megameklab/com/ui/util/FactionComboBox.java
- src/megameklab/com/ui/view/BasicInfoView.java
This changes the way tech base and mixed tech options are presented to reflect the early Clan years better. Currently the options work off the assumption that Clan factions build Clan units and IS factions build IS units, so IS mixed is not an option prior to 3050. This PR changes the behavior to allow Clan, Clan mixed, and IS mixed as long as they are available at any point in the game universe by default. When using tech-specific intro dates, Clan tech is unavailable to IS and periphery factions until the IS intro date of mixed tech.
Specific non-fluff differences this makes:
1. Using Clan mixed instead of IS mixed for the early Clan units causes MM to add Clan CASE automatically.
2. For BA, a Clan mixed chassis is heavier than an IS mixed chassis to account for the automatic HarJel. …
> Early Clans and IS tech

- src/megameklab/com/printing/PrintCompositeTankSheet.java
- src/megameklab/com/printing/PrintEntity.java
- src/megameklab/com/printing/PrintRecordSheet.java
My recent update allowing the user to set the paper size broke vehicle record sheets with a single unit on them. It throws an exception when trying to position the tables due to an illegal attribute, (transform where it should be translate) but it also doesn't take any custom margins into account. In the process of fixing it I simplified it by using the code already in PrintRecordSheet to handle the loading and sizing.
> Fix scaling and positioning of tables on vehicle record sheet.

- src/megameklab/com/ui/BattleArmor/CriticalSuit.java
- src/megameklab/com/ui/Mek/views/BuildView.java
- src/megameklab/com/ui/Mek/views/SummaryView.java
- src/megameklab/com/util/CriticalTableModel.java
- src/megameklab/com/util/UnitUtil.java
Companion of MegaMek/megamek#2007. This handles adjusting the critical slots when equipment is resized, and also moves the slot calculation from EquipmentType to Mounted.
>  Variable equipment size, part 2

- src/megameklab/com/printing/InventoryWriter.java
- src/megameklab/com/printing/StandardInventoryEntry.java
Fixes a text overlap issue in the inventory section of a record sheet. When the name or damage entry is too long to fit in the space it is split over multiple lines. There is a logic error that only moves the starting y coordinate of the next row of the text the necessary extra amount if the multi-line row is the last one in the entry.
Example:
In additional to correcting the logic error, I reduced the need for multiline text by limiting the (IS) and (Clan) indicators used on mixed tech units to equipment that has both IS and Clan variants. So in this example the AMS shows as (IS), but there is no need to specify the improved gauss rifle, which has no Clan version, or the prototype ER small lasers or improved LRM, which have no IS version.
> Inventory overlap

- src/megameklab/com/printing/PrintEntity.java
- src/megameklab/com/printing/RecordSheetOptions.java
- src/megameklab/com/ui/view/BasicInfoView.java
Applies the era-based tech progression system from IO in a few places it was missing.
1. The tech level combo box. It treats mixed tech and superheavies as always advanced, but using the IO system mixed tech is standard after 3115 and superheavies are experimental before 3076.
2. The record sheet always shows the basic (static) tech level.
> Era based tech fixes

- src/megameklab/com/ui/aerospace/DropshipStructureTab.java
Small craft/dropship hull shape affects the number of weight-free heat sinks.
Fixes #644
> Refresh heat panel when switching between aerodyne and spheroid

- src/megameklab/com/util/UnitUtil.java
Capital weapon groups are created when an aerospace fighter is loaded but serve no purpose in MML. They're ignored in most places, but ammo will still show up on the equipment tab after the weapon has been removed because it matches the weapon group. When the unit is loaded into MM the weapon groups will be built normally.
Fixes #642.
> Remove capital fighter weapon groups on load.

- src/megameklab/com/util/CriticalTransferHandler.java
- src/megameklab/com/util/DropTargetCriticalList.java
- src/megameklab/com/util/Mech/CriticalTransferHandler.java
- src/megameklab/com/util/Mech/DropTargetCriticalList.java
- src/megameklab/com/util/UnitUtil.java
Linked equipment such as missile launchers and Artemis or PPCs and capacitors have little direct effect on construction but can affect BV calculations. Currently the links are rechecked by calling MechFileParser::postLoadInit whenever equipment location changes via drag and drop, but not when placed by popup menu. Links are also not removed once set unless the equipment is removed, so links can span locations. In the issue that prompted this change, adding a PPC to a mech resulted in linking an unallocated PPC to an unallocated capacitor (they are considered to be in the same location, because both are in LOC_NONE). Then depending on the order they are placed you can end up with one of the capacitors linked to a PPC in another location and the other not linked at all. This affects the …
> Reset equipment links

- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
Mass drivers take ten slots for purposes of extra weight for fire control. The extra slots are being accounted for in the weight calculation, but not displayed in the current slot count.
Fixes #655.
> Account for mass drivers when displaying slot count on build tab

- src/megameklab/com/printing/PrintEntity.java
The record sheet is supposed to indicate the type of armor when it has a particular game effect (e.g. reflective, heat-dissipating, etc). Commercial armor for IndustrialMechs should be included, since it has a lower BAR.
> Indicate commercial armor on mech record sheet

- src/megameklab/com/ui/view/BasicInfoView.java
The source of this issue is the use of a named constant without the correct class reference. The local constants are used to distinguish unit tech base (IS, Clan, IS mixed, Clan mixed) and what was intended was the constant from ITechnology, which is used for equipment tech base (IS, Clan, all). I fixed the reference and renamed the local constants to make confusion less likely.
Fixes #657
> Fix for tripod and superheavy mech tech base

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/view/MovementView.java
A change in the year or tech level can cause jump jets (IJJs in particular) or UMU to become invalid, but they are not being removed like other equipment.
Fixes #659
> Remove jump jets/umu when required by year/tech level changes

- src/megameklab/com/ui/Aero/tabs/StructureTab.java
- src/megameklab/com/ui/Vehicle/tabs/StructureTab.java
- src/megameklab/com/ui/Vehicle/views/CriticalView.java
- src/megameklab/com/util/DropTargetCriticalList.java
- src/megameklab/com/util/UnitUtil.java
This fixes a couple problems I noticed while working on MegaMek/megamek#2069. The first is that when stealth armor is removed from a vehicle due to changing armor type, the critical slots on the unit don't match up to the critical slot names in the JList model for the location on the build tab. I resolved this by compressing the criticals after removing armor mounts on vehicles and fighters. The second issue is that you can remove or delete the stealth armor critical on the build tab. This doesn't have any practical effect but it's sloppy.
> Fixes for build tab issues with stealth armor

- src/megameklab/com/printing/StandardInventoryEntry.java
The range calculations for ECMs and probes are embedded in various places throughout MM, so there was not a nice library function to use to get this data.
Fixes #677
> Show range for electronic warfare equipment on the record sheet

- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
The total AV for a bay does not reflect the adjustment for linked equipment, nor does the tooltip for the bay or the individual weapon. The AV limit of 700 for a standard scale bay also doesn't take this into account.
Fixes #679
> Account for Artemis, PPC capacitor, etc. on large craft build tab

- src/megameklab/com/ui/Infantry/tabs/StructureTab.java
- src/megameklab/com/ui/Infantry/views/SpecializationView.java
- src/megameklab/com/ui/Infantry/views/WeaponView.java
When adding or changing an infantry unit's secondary weapon, MML makes sure it the secondary weapon count is at least one. But it also does that when changing the primary weapon. This causes validation problems with specializations that don't allow any secondary weapons, such as combat engineers. I also added some code to handle removing the secondary weapon when such a specialization is chosen and disabling the button to add a secondary weapon.
Fixes #695
> Don't change secondary weapon count when setting primary weapon

- src/megameklab/com/printing/StandardInventoryEntry.java
- src/megameklab/com/util/StringUtils.java
Fixes three issues with the weapon stats in the record sheet inventory section.
1. Heavy machine guns have no long range, and the ranges should be shown as 1/2/- instead of 1/2/2.
2. Small and medium VSP lasers show 0 for damage instead of the values for short, medium, and long range. Large and BA versions were correct.
3. Small support vehicle weapons need special handling to show their damage based on infantry weapon stats.
Fixes #703
> Record sheet inventory weapon fixes

- src/megameklab/com/ui/Mek/tabs/BuildTab.java
- src/megameklab/com/ui/Mek/views/BuildView.java
- src/megameklab/com/ui/Mek/views/SummaryView.java
- src/megameklab/com/util/CriticalTableModel.java
- src/megameklab/com/util/Mech/CriticalTransferHandler.java
- src/megameklab/com/util/UnitUtil.java
I changed the signature of the method that calculates the number of slots taken up by each separate allocation of equipment so that it can take the size of variable-sized mounts into account.
Fixes #699
> Show correct slot count on unallocated variable-sized equipment

- src/megameklab/com/ui/BattleArmor/tabs/StructureTab.java
- src/megameklab/com/util/UnitUtil.java
When the secondary motive type changes among jump, vtol, and underwater, remove the old MiscType and install the new one (if any).
Partial fix for #710
> Swap BA secondary motive mount when type changes

- src/megameklab/com/util/UnitUtil.java
Fixes a bug introduced by #671. When a weapon changes locations, the link should not be broken between a one-shot weapon and its ammo.
Fixes #719
> Keep link with one shot ammo when weapon is moved.

- src/megameklab/com/printing/PrintEntity.java
I missed applying the scale factor to the MP when there are two values (such as when there is MASC or a supercharger). This also fails to round up.
Fixes #720
> Fix run MP String on record sheet

- src/megameklab/com/printing/PrintMech.java
Mechs with a smart robotic control system will show "SRCS" or "Improved SRCS" in the cockpit slot. This follows the cannon example of the Revenant UMB-1A from Jihad: Final Reckoning, p. 161, where it is shown as "Robotic Cockpit." In those earlier rules the system was simply referred to as a "robotic drone control system." The system received a formal name in IO and the rules were expanded to include an improved system.
Fixes #721
> Show SRCS on mech record sheet

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
The number of active heat sinks gets reset when the heat sink count is changed directly, but not when changed indirectly by selecting an engine with more weight-free sinks.
Fixes #700
> Reset heat sinks after engine change

- src/megameklab/com/printing/PrintAero.java
Fixed wing support vehicles indicate VSTOL (or STOL) capabilities by the chassis mod that's already printed. ASFs are always VSTOL and don't need to specify.
Fixes #722
> Show VSTOL equipment on conventional fighter record sheet.

- src/megameklab/com/printing/PrintEntity.java
The default name for LAM pilots is no longer consistent with the generic crew default name.
Fixes #723
> Hide pilot info for any name that stars with "unnamed"

- src/megameklab/com/printing/PrintInfantry.java
Artillery cannons currently show -5, which is the value of WeaponType.DAMAGE_ARTILLERY.
Fixes #725
> Format artillery cannon damage on infantry record sheet

- src/megameklab/com/util/UnitPrintManager.java
Replaces the extension on the MUL file with .pdf and uses that as the suggested file for the export. I've gathered there's some issue with the way Windows handles file extensions, but setting the name with a pdf extension doesn't seem to be a problem when exporting a single unit so I presume this will be more familiar behavior.
Fixes #724
> Suggest filename when exporting to MUL

- src/megameklab/com/printing/PrintInfantry.java
- src/megameklab/com/util/EquipmentTableModel.java
Show the F indicator in the special column for flamers on the equipment table. The check for a heat mode on the record sheet was not catching all flame-based weapons.
Fixes #738
> Treat infantry flamers as flame-based weapons on equipment table and record sheets

- build.gradle
Same as [#1919](https://github.com/MegaMek/mekhq/pull/1919). Adding the jitpack maven repo to build the SerialKiller object deserialization library added to MegaMek.
> Add jitpack repo for mm serialkiller dep

- data/images/recordsheets/templates_iso/conventional_infantry_platoon.svg
- data/images/recordsheets/templates_us/conventional_infantry_platoon.svg
- src/megameklab/com/printing/IdConstants.java
- src/megameklab/com/printing/PrintInfantry.java
When generated on Windows, the dash is printed as â€”, using Windows 1252 instead of Unicode. The escape sequence \u2014 is known to work on other sheets, so I replaced the literal with that.
I also noticed in the provided sample that the damage string for field guns can overrun the minimum range field, so I added a second field below it and split the text when it's longer.
Fixes #740.
> Fix Windows encoding issue on infantry record sheets

- data/images/recordsheets/templates_iso/mech_biped_default.svg
- data/images/recordsheets/templates_iso/mech_biped_toheat.svg
- data/images/recordsheets/templates_iso/mech_lam_default.svg
- data/images/recordsheets/templates_iso/mech_lam_toheat.svg
- data/images/recordsheets/templates_iso/mech_quad_default.svg
- data/images/recordsheets/templates_iso/mech_quad_toheat.svg
- data/images/recordsheets/templates_iso/mech_quadvee_default.svg
- data/images/recordsheets/templates_iso/mech_quadvee_toheat.svg
- data/images/recordsheets/templates_iso/mech_tripod_default.svg
- data/images/recordsheets/templates_iso/mech_tripod_toheat.svg
- data/images/recordsheets/templates_us/mech_biped_default.svg
- data/images/recordsheets/templates_us/mech_biped_toheat.svg
- data/images/recordsheets/templates_us/mech_lam_default.svg
- data/images/recordsheets/templates_us/mech_lam_toheat.svg
- data/images/recordsheets/templates_us/mech_quad_default.svg
- data/images/recordsheets/templates_us/mech_quad_toheat.svg
- data/images/recordsheets/templates_us/mech_quadvee_default.svg
- data/images/recordsheets/templates_us/mech_quadvee_toheat.svg
- data/images/recordsheets/templates_us/mech_tripod_default.svg
- data/images/recordsheets/templates_us/mech_tripod_toheat.svg
- src/megameklab/com/printing/IdConstants.java
- src/megameklab/com/printing/PrintMech.java
Reinforced and composite structure affect how damage is applied and should appear on the record sheet.
Biped:
Quad:
Tripod:
Closes #749
> Show mech structure type on RS when it has an in-game effect

- src/megameklab/com/printing/PrintAero.java
- src/megameklab/com/printing/PrintEntity.java
- src/megameklab/com/printing/PrintTank.java
1. Show the unit weight in kg instead of rounding tons.
2. Show transport bay capacity in kg instead of fractional tons (following examples in House Liao and House Kurita handbooks).
3. Treat the capacity of standard/pinion/ejection seating as the number of seats rather than the capacity in tons.
Fixes #726
Fixes #756
> Use kilogram standard on small SV record sheets

- src/megameklab/com/util/UnitUtil.java
I missed this in a previous change. UnitUtil#removeOneShotAmmo used to be called only for mechs, and I changed it to run on all units. The purpose is to avoid having to deal with the one-shot ammo showing up on various equipment lists. It's safe to remove because it has no effect on construction, isn't written to the unit file, and gets reinitialized on load.
The code that I removed has no effect on mechs, since the index that gets adjusted is the index for system equipment and not the index of the mount in the equipment list. For non-mech units this can throw an indexOutOfRangeException that gets swallowed by the SwingWorker that loads the unit in the background.
Fixes #767
> Don't adjust crit indices when removing one-shot ammo.

- src/megameklab/com/ui/Aero/tabs/EquipmentTab.java
- src/megameklab/com/ui/Mek/tabs/EquipmentTab.java
- src/megameklab/com/ui/Vehicle/tabs/EquipmentTab.java
- src/megameklab/com/ui/tabs/EquipmentTab.java
More one-shot and small SV ammo cleanup. The ammo bin is automatically added when the launcher is, and it shows up on the installed equipment list on the equipment tab when it refreshes. Following the approach that has been part of MML for some time, we remove them as irrelevant to construction.
> Remove one shot bins that are automatically added with the launcher

- src/megameklab/com/printing/StandardInventoryEntry.java
- src/megameklab/com/util/EquipmentTableModel.java
- src/megameklab/com/util/StringUtils.java
This is a companion PR to MegaMek/megamek#2293. It uses aero stats instead of ground stats for small fixed wing support vehicles on the master equipment table and on the record sheet. It also shows the number of shots of ammo for each weapon in the inventory, which is needed for all small support vehicles.
> Small fixed wing SV corrections

- src/megameklab/com/ui/view/ArmorAllocationView.java
- src/megameklab/com/util/UnitUtil.java
See MegaMek/megamek#2299. This corrects the method used by the armor allocation view to display total armor points available and points remaining to be allocated. In researching this I discovered in the IO errata that the points from armor tonnage and SI should be combined before applying the primitive multiplier, rather than separately and rounded before combining, so there's a more general correction here that affects primitive jumpships as well. The fractional amount is retained here and the rounding is applied after the values have been added.
Fixes #752
> Apply primitive armor multiplier to SC/DS free armor from SI

- src/megameklab/com/ui/aerospace/DropshipStructureTab.java
- src/megameklab/com/ui/view/DropshipChassisView.java
- src/megameklab/com/ui/view/MVFArmorView.java
- src/megameklab/com/util/MenuBarCreator.java
This fixes three issues of four issues related to early primitive dropships and small craft.
1. When setting the year before the introduction of the KF drive boom, the boom is not being removed from the unit or its tech advancement.
2. When there is no armor available at the current tech settings, the armor is left as is instead of throwing an exception. This shouldn't happen, but there is an inconsistency between the published production dates of primitive DS/SC and primitive aerospace armor that makes the armor experimental for a century after the unit becomes advanced when using variable tech dates. Besides that, it's just better to handle it more gracefully.
3. Resetting the unit is currently taking you from primitive to standard.
The other issue is resolved by MegaMek/megamek#2316. …
> Early primitive dropship/small craft date fix

- src/megameklab/com/printing/PrintCompositeTankSheet.java
- src/megameklab/com/printing/PrintEntity.java
- src/megameklab/com/printing/PrintRecordSheet.java
- src/megameklab/com/printing/PrintSmallUnitSheet.java
- src/megameklab/com/printing/RecordSheetTask.java
Since we can now create large record sheet pdf documents, I thought it would be nice to add an outline to the document for quick navigation. Sheets with multiple units per page have an entry for each unique unit on the sheet.
> Add an outline to PDF output

- src/megameklab/com/printing/PaperSize.java
- src/megameklab/com/printing/PrintRecordSheet.java
- src/megameklab/com/printing/RecordSheetTask.java
Since I've only dealt with the PDF export on the computer, where the documents can be scaled arbitrarily, I never noticed that the sheets are being generated at 75% scale. After digging through the library code, I eventually figured out that the transcoder assumes the SVG document is 96 dpi, while we are using the screen display standard of 72 dpi. So I changed the conversion factor, and fixed a couple other things I noticed while trying to figure out what's going on.
Fixes #802
> Proper scaling for PDF export

- src/megameklab/com/util/UnitPrintManager.java
The documentation for `PrinterDialog#printDialog(PrintRequestAttributeSet)` says that it displays a cross-platform print dialog, but I had at one point set the option to use native instead. The native dialog does not necessarily include a page setup tab. If it doesn't the page prints with 1" margins instead of the default 0.25" margins, with no way to change it.
Fixes #746.
> Use common print dialog instead of native.

- src/megameklab/com/printing/PrintCompositeTankSheet.java
- src/megameklab/com/printing/PrintRecordSheet.java
- src/megameklab/com/printing/PrintSmallUnitSheet.java
When printing record sheets that have multiple units on them (non-naval vehicles, battlearmor, infantry, protomechs), the margins are applied to each unit and the overall sheet. To solve this I added a parameter to createDocument that controls whether the margins should be added. For tanks, which are basically two complete record sheets on one page, the margin is applied to each unit. For the other types, which have a full page template that has data on where to put each unit, the page gets the margins and the units don't. I also removed a line that was incorrectly moving each group to the top level, which made any scaling applied to the overall page not work.
Fixes #665.
> Compound sheet margins

- src/megameklab/com/util/UnitPrintManager.java
When creating an instance of PrintAero, used for aerospace and conventional fighters and small craft, the page index is not incremented. This causes an off-by-one error in the PDF index. I double checked the other unit types and this is the only one that I saw that was missing.
> Increment page count for every PrintAero

- src/megameklab/com/printing/InventoryWriter.java
- src/megameklab/com/printing/PrintMech.java
Though each ammo bin is configurable on a per-battle basis, and the munition type is not part of the construction, there are times when showing a specific munition type is helpful:
1. MML ammo has a different number of shots/ton for SRM and LRM ammo, and it's not otherwise clear on the record sheet which is being counted.
2. MekHQ can print sheets that have been configured for a specific battle.
It used to be done this way, but was changed because the munition type often made the text overflow the assigned area. With the work that has been done redoing the layout and improving the way text is positioned, that's no longer an issue -- though the text may be compressed for very long munition names.
> Show munition type on record sheet

- data/images/recordsheets/templates_iso/dropship_aerodyne_default.svg
- data/images/recordsheets/templates_iso/dropship_spheroid_default.svg
- data/images/recordsheets/templates_iso/fighter_aerospace_default.svg
- data/images/recordsheets/templates_iso/fighter_conventional_default.svg
- data/images/recordsheets/templates_iso/jumpship_default.svg
- data/images/recordsheets/templates_iso/smallcraft_aerodyne_default.svg
- data/images/recordsheets/templates_iso/smallcraft_spheroid_default.svg
- data/images/recordsheets/templates_iso/spacestation_default.svg
- data/images/recordsheets/templates_iso/warship_default.svg
- data/images/recordsheets/templates_us/dropship_aerodyne_default.svg
- data/images/recordsheets/templates_us/dropship_spheroid_default.svg
- data/images/recordsheets/templates_us/fighter_aerospace_default.svg
- data/images/recordsheets/templates_us/fighter_conventional_default.svg
- data/images/recordsheets/templates_us/jumpship_default.svg
- data/images/recordsheets/templates_us/smallcraft_aerodyne_default.svg
- data/images/recordsheets/templates_us/smallcraft_spheroid_default.svg
- data/images/recordsheets/templates_us/spacestation_default.svg
- data/images/recordsheets/templates_us/warship_default.svg
The bombs inventory on fighter record sheets and the "armor diagram" label on other aerospace sheets prints a little into the right margin. I noticed this while working on aerospace reference tables. This is a data fix that moves them to the correct position.
> Adjust elements that were in the right margin on aero sheets.

- src/megameklab/com/ui/EntitySource.java
- src/megameklab/com/ui/aerospace/DropshipMainUI.java
#796 and MegaMek/megameklab#2316 took care of most of the issues preventing construction of early dropships, but I missed the switch between dropship and small craft, which doesn't maintain the primitive status. The fix is in EntitySource. The changes in DropshipMainUI are cleanup for warnings that I saw while tracking down the problem.
Fixes #822
> Maintain primitive status when switching unit type

- src/megameklab/com/printing/PrintMech.java
- src/megameklab/com/ui/Mek/tabs/StructureTab.java
- src/megameklab/com/ui/protomek/ProtomekStructureTab.java
- src/megameklab/com/ui/tabs/EquipmentTab.java
- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
- src/megameklab/com/util/UnitUtil.java
Now that MM uses a consistent definition of EquipmentType::equals, I believe that MML should switch from reference equality to Object::equals.
> Switch to EquipmentType::equals for AmmoType, etc

- src/megameklab/com/util/UnitUtil.java
I noticed this while working on the fix for MegaMek/megamek#2195.
When a unit is loaded the one-shot ammo is removed, since in MML anything in LOC_NONE is treated as unallocated and it doesn't have any affect on construction. In mechs spreadable equipment such as endo steel and TSM  is also removed and replaced with multiple single-crit instances so they can be assigned locations separately. Since bay weapons and ammo are stored as the index in the equipment list, removing any equipment closer to the head of the list makes the values invalid. One-shot ammo is also removed as one-shot launchers are added, but since this happens at the tail of the list it has no impact.
> Fix bay weapon and ammo indices after removing equipment

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
Superheavy mechs have double-sized crits, so the number of crits taken up by patchwork armor should be divided by two, rounded up.
Fixes #841
> Reduce crit cost for superheavy patchwork armor

- src/megameklab/com/ui/Mek/tabs/EquipmentTab.java
- src/megameklab/com/util/UnitUtil.java
MML removes Clan CASE from mechs when they are loaded, presumably to keep it from showing up in the installed equipment list. This causes an unforeseen side effect from some of my recent work on BV calculations in MM, assigning an explosive equipment penalty when there shouldn't be one. MM used to base the check on an assumption that all Clan mechs have CASE installed automatically, though the rules state that Clan CASE can be omitted to reduce cost. Though we don't support that at this point, the BV calculation implementation is ready for it.
To fix it I removed the line that removes Clan CASE on load, added Clan CASE to the equipment that gets filtered out of the equipment list, and added some code that installs it as necessary when explosive equipment is added to a location. Removing …
> Retain and update Clan CASE

- src/megameklab/com/ui/Mek/tabs/StructureTab.java
This depends on Megamek/megamek#2521
Removes the gap between compact engine and superheavy gyro. I also noticed during testing that when switching from superheavy to  standard weight the gyro type remains superheavy.
Fixes #845
> Don't leave an empty slot between SH compact engine and gyro

- src/megameklab/com/util/EquipmentTableModel.java
The equipment table shows damage as 2/msl for plain vanilla and streak SRMs, but not for the torpedo version, BA advanced SRMs, early Clan improved SRMs, or primitive SRMs. I think I got them all.
Fixes #861
> Show 2/msl in damage column for all SRM types

- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
I double-checked the other missile types. ELRM and primitive missile launchers can't use Artemis. Torpedoes can't be used on large craft.
Fixes #866
> Include improved LRM and SRM in bay weapons that have have Artemis

- src/megameklab/com/util/Mech/DropTargetCriticalList.java
Include a menu item to change facing of torso-mounted modular armor. This also fixes two other issues I discovered in the process:
1. Alt-right click toggles between forward and rear facing on any equipment whether it makes sense or not.
2. The sprayer and light suction system require a firing arc (TM, p. 247) and should be eligible for rear facing.
I double checked MM and verified that a hit against a torso location with modular armor checks the facing.
Fixes #879
> Rear modular armor

- src/megameklab/com/MegaMekLab.java
- src/megameklab/com/util/CConfig.java
This refactors CConfig slightly to allow the MML configuration to be in-memory only, without any disk access. This supports headless usage of MML's printing features which may not live as part of a MM/MML distribution.
MekHQ companion: https://github.com/MegaMek/mekhq/pull/2361
> Allow MML config to be loaded in memory only

- src/megameklab/com/printing/PrintMech.java
When calculating the number of pips to display on a shield the -1 reduction for each missing arm and hand actuator is not being applied.
Partial fix for Megamek/megamek#2710
> Account for missing actuators in shield pips

- build.gradle
Fixes:
```
The package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml
```
> Exclude xml-apis on Java 11

- src/megameklab/com/ui/view/MekChassisView.java
1. Adds torso-mounted cockpit to list of available cockpits for industrialmechs (TO:AU&E, 112)
2. Makes standard primitive cockpit available to primitive industrialmechs, which is how MM indicates an industrial cockpit with advanced fire control. This is subject to a date check, since primitive industrialmechs predate battlemechs.
3. Fixes the check for command console date and tech level to match the command console itself. The current check for IM advanced fire control does nothing, since the only difference is availability and tech rating.
Fixes #638
> Industrialmech cockpits

- src/megameklab/com/util/MenuBarCreator.java
This is the MegaMekLab part of a full repository swapover from using instanceof to determine if a unit is conventional infantry to the isConventionalInfantry method, which returns true for Infantry and all inheritors outside of BattleArmor and inheritors. It does not rely on the other two branches.
Logic:
(Infantry && !BattleArmor): isConventionalInfantry 
(!Infantry || BattleArmor): !isConventionalInfantry
> Moving to fully use isConventionalInfantry

- src/megameklab/com/ui/Mek/tabs/EquipmentTab.java
- src/megameklab/com/ui/view/HeatSinkView.java
- src/megameklab/com/util/CriticalTableModel.java
Addresses three issues
1. All heat sinks are managed from the structure tab and should not be appearing on the equipment tab (cf #913).
2. CriticalTableModel duplicates its data in an array called sortedEquipment which, despite the name, does not appear to be sorted anywhere. The array is updated in refreshModel() but this is not always called between updates, and the class is not consistent in which is accessed when the data is modified. I removed the array.
3. While testing the heat sink panel on the structure tab I noticed that the spinner for the number of prototype sinks to use is sometimes inoperative. This is because the max value is being set to the integrated heat sink capacity, which can result in max < value. The correct maximum is the number of heat sinks. None of them have to …
> Remove prototype heatsinks from equipment tab

- src/megameklab/com/ui/Aero/StatusBar.java
- src/megameklab/com/ui/BattleArmor/StatusBar.java
- src/megameklab/com/ui/Mek/StatusBar.java
- src/megameklab/com/ui/Vehicle/StatusBar.java
- src/megameklab/com/ui/aerospace/AdvancedAeroStatusBar.java
- src/megameklab/com/ui/aerospace/DropshipStatusBar.java
- src/megameklab/com/ui/protomek/ProtomekStatusBar.java
- src/megameklab/com/ui/supportvehicle/SVStatusBar.java
New format:
Besides adding the remainder, BA and small support vehicles are now displayed in kg (protomechs were already displaying in kg), and large craft tonnages are commified (using locale-appropriate grouping character).
Closes #813
> Show unused tonnage in the status bar.

- src/megameklab/com/printing/StandardInventoryEntry.java
- src/megameklab/com/util/CriticalTableModel.java
Show all locations for spreadable equipment on the record sheet. Equipment with more than two locations is abbreviated. Depends on MegaMek/megamek#2912.
Fixes #869
> Show multiple equipment locations on the record sheet

- src/megameklab/com/printing/StandardInventoryEntry.java
The max range of a BAP is 4 hexes.
Fixes #873
> Fix Beagle range on record sheet

- data/images/recordsheets/templates_iso/mech_biped_default.svg
- data/images/recordsheets/templates_iso/mech_biped_toheat.svg
- data/images/recordsheets/templates_iso/mech_quad_default.svg
- data/images/recordsheets/templates_iso/mech_quad_toheat.svg
- data/images/recordsheets/templates_iso/mech_quadvee_default.svg
- data/images/recordsheets/templates_iso/mech_quadvee_toheat.svg
- data/images/recordsheets/templates_iso/mech_tripod_default.svg
- data/images/recordsheets/templates_iso/mech_tripod_toheat.svg
- data/images/recordsheets/templates_us/mech_biped_default.svg
- data/images/recordsheets/templates_us/mech_biped_toheat.svg
- data/images/recordsheets/templates_us/mech_quad_default.svg
- data/images/recordsheets/templates_us/mech_quad_toheat.svg
- data/images/recordsheets/templates_us/mech_quadvee_default.svg
- data/images/recordsheets/templates_us/mech_quadvee_toheat.svg
- data/images/recordsheets/templates_us/mech_tripod_default.svg
- data/images/recordsheets/templates_us/mech_tripod_toheat.svg
- src/megameklab/com/printing/IdConstants.java
- src/megameklab/com/printing/PrintMech.java
In addition to including the partial wing in the total heat dissipation, there is a note underneath explaining where the extra three points come from.
Screenshot:
Closes #871
> Include partial wing bonus in heat capacity on record sheet

- src/megameklab/com/util/UnitUtil.java
1. When switching to compact heat sinks on a mixed tech Clan mech, laser heat sinks are installed instead. This is a problem in `UnitUtil#getHeatSinkType`, which did not allow for mixed tech. I think the method needs to be removed, but the call chain goes several levels deep in other places and it's best left for another time. In this case the fix was simpler.
2. The number of compact heat sinks showing on the build tab to be allocated is not reduced when the engine rating increases. This is because of a requirement that engine heat sinks are always one per mount, which means that the paired mounts need to be split. Decreasing the engine rating requires that some of those singles must be allocated, which means they get paired up. I couldn't find any sign that MML ever did that properly, …
> Compact heat sink fixes

- src/megameklab/com/util/UnitUtil.java
This affects Clan machine guns.
Fixes #897
> Don't show protomech-only ammo on equipment tab for non-protomechs

- src/megameklab/com/printing/PrintInfantry.java
On infantry recordsheets, indicate the +1d6 "burst fire" modifier if the infantry is using a weapon that has been nerfed.
> update recordsheet printing

- src/megameklab/com/printing/InventoryWriter.java
- Adds CASE info for **all non-mech units** that have a **CASE in their equipment list**. 
- Does not check for CASEII as this is explicitly listed in the equipment list (as per official RS)
- Shows CASE even for Clan units  (as per official RS)
Resolves #943
> Add CASE info to ammo on non-Mech Record Sheets

- src/megameklab/com/util/CritListCellRenderer.java
- src/megameklab/com/util/UnitUtil.java
- Issue 953: For ammo, shows the shots in the tooltip
- Issue 646: For weapons, shows a maximum damage value in the tooltip. Obviously there's weapons for which this is difficult, so this should be taken with a grain of salt.
- corrects a small bug that would show the last hovered weapon tooltip when hovering something like the Engine or an actuator or empty slot. Now removes the tooltip instead when hovering these.
- a few code format improvements
Resolves #953 
Resolves #646
> Tooltip info

- src/megameklab/com/ui/Aero/MainUI.java
- src/megameklab/com/ui/Aero/tabs/EquipmentTab.java
- src/megameklab/com/ui/BattleArmor/MainUI.java
- src/megameklab/com/ui/BattleArmor/tabs/EquipmentTab.java
- src/megameklab/com/ui/Mek/MainUI.java
- src/megameklab/com/ui/Mek/tabs/EquipmentTab.java
- src/megameklab/com/ui/Vehicle/MainUI.java
- src/megameklab/com/ui/Vehicle/tabs/EquipmentTab.java
- src/megameklab/com/ui/aerospace/AdvancedAeroUI.java
- src/megameklab/com/ui/aerospace/DropshipMainUI.java
- src/megameklab/com/ui/protomek/ProtomekMainUI.java
- src/megameklab/com/ui/supportvehicle/SVMainUI.java
- src/megameklab/com/ui/tabs/EquipmentTab.java
An addendum to #957: 
Removes the "master" scrollpane from the equipment tabs, as those consist mainly of two lists that have their own internal scrollbars and dont need one for the whole tab. This makes the equipment tab behave gracefully when being sized down. 
Also gives the equipment database list a minimum size that will allow the splitpane divider to be reasonably moved.
(I must say that this has limits. When someone sizes the window down to 600x400 pixels a master scrollpane will prevent horizontal squishing of the lists. But on normal window sizes any horizontal scrollbar is annoying and useless. Id opt to assume that people can work MML at 1000x700 pixels at least, anything smaller is at user's risk)
> Remove main scrollbar from the equipment tabs

- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
Preserves the expanded/collapsed states of the weapon bays in the large Aero crit view when loadout changes happen (moving stuff in/out/between bays)
> Preserve expanded state of Large Aero Weapon Bays

- src/megameklab/com/ui/Aero/tabs/EquipmentTab.java
- src/megameklab/com/ui/util/AeroBayTransferHandler.java
- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
- src/megameklab/com/util/UnitUtil.java
In the Large Aero Crit View:
- No longer throws exceptions when dragging an "--Empty--" slot
- No longer sometimes adds duplicate equipment when using the Copy from other side buttons
- Weapons dragged from one location to another will no longer sometimes not disappear from the source arc
I thought I would need removeEmptyBays() as a utility at another class but in the end I didnt. It still seemed like a valid change to move this method to the UnitUtils so I left it in.
> Large Aero Crit View Bug Fixes

- build.gradle
This fixes multiple critical issues with PDF Box 2.0.22, including infinity loop and out of memory exceptions.
> Updating PDFBox to 2.0.24

- src/megameklab/com/ui/Aero/tabs/BuildTab.java
- src/megameklab/com/ui/Aero/views/CriticalView.java
- src/megameklab/com/ui/BattleArmor/tabs/BuildTab.java
- src/megameklab/com/ui/BattleArmor/views/CriticalView.java
- src/megameklab/com/ui/Mek/tabs/BuildTab.java
- src/megameklab/com/ui/Mek/views/CriticalView.java
- src/megameklab/com/ui/Vehicle/tabs/BuildTab.java
- src/megameklab/com/ui/Vehicle/views/CriticalView.java
- src/megameklab/com/ui/aerospace/LargeCraftCriticalView.java
- src/megameklab/com/ui/protomek/ProtomekCriticalView.java
- src/megameklab/com/ui/supportvehicle/SVBuildTab.java
- src/megameklab/com/ui/supportvehicle/SVCriticalView.java
- src/megameklab/com/ui/util/BayWeaponCriticalTree.java
- src/megameklab/com/ui/util/CritCellUtil.java
- src/megameklab/com/ui/util/ProtomekMountList.java
- src/megameklab/com/util/CritListCellRenderer.java
- src/megameklab/com/util/IView.java
- src/megameklab/com/util/UnitUtil.java
+ Crit Cells on various units now use a more unified style and use a standard size font instead of a reduced size font. The width of crit cells adapts to the number of columns used by the unit (5 for meks, 3 for BA)
+ The number of shots for ammo is now displayed at the start of the cell text to (finally) always keep it in sight no matter the name of the ammo
+ Adds experimental mouse click functionality on Crit Cells (add & remove weapons & ammo on Ctrl-Click) to ProtoMeks (for now)
Adds a CritCellUtil class that combines general Crit Cell display functionality. Lots of code cleanup without much visual effect. Especially in the various CriticalView classes loads of code is removed that had little or no effect or was just (to my eye) in need of some updated organization.
> Crit unification

- build.gradle
There was a major bugfix release to further improve security when using Log4j. This updates MML to that release, while MM and MHQ have it as part of their individual update PRs.
> Updating to Log4j2 2.16.0

- src/megameklab/com/ui/battleArmor/BAStructureTab.java
- src/megameklab/com/ui/combatVeh/CVStructureTab.java
- src/megameklab/com/ui/convInfantry/CIStructureTab.java
- src/megameklab/com/ui/fighterAero/ASStructureTab.java
- src/megameklab/com/ui/generalUnit/BasicInfoView.java
- src/megameklab/com/ui/largeAero/DSStructureTab.java
- src/megameklab/com/ui/largeAero/WSStructureTab.java
- src/megameklab/com/ui/listeners/BuildListener.java
- src/megameklab/com/ui/mek/BMStructureTab.java
- src/megameklab/com/ui/protoMek/PMStructureTab.java
- src/megameklab/com/ui/supportVeh/SVStructureTab.java
- src/megameklab/com/util/UnitUtil.java
Manual BV will now work and be saved to the file and update in the status bar (with the exception of CI where the fault is on the MM side).
Resolves #901 
The code is sadly repetitive but with the BuildListener and EntitySource structure I couldn't think of a better way of doing it. It really wants a default interface method in BuildListener but there's no access to the entity nor the refresh system there. Maybe an AbstractStructureTab but that's far outside the scope of this PR.
> Issue901 Manual BV

- src/megameklab/com/MegaMekLab.java
MegaMekLab side of https://github.com/MegaMek/megamek/pull/3346
> Logging: Default Global Exception Handler and Standardized Legacy Logging

- src/megameklab/com/ui/dialog/ConfigurationDialog.java
- src/megameklab/com/ui/util/CritCellUtil.java
- src/megameklab/com/ui/util/CritListCellRenderer.java
- src/megameklab/com/ui/util/CriticalTableModel.java
- src/megameklab/com/util/CConfig.java
Makes a new color config available for unhittable crit slots such as Endo Steel or Ferro Armor and I think a handful of systems that are unhittable. Since most unit types don't use unhittable crit slots this will almost exclusively affect Meks.
Also corrects an indentation issue in the crit slots that was caused by a missing border.
> Add a color config for unhittables (Endo etc.)

- .gitignore
- src/megameklab/com/MMLOptions.java
- src/megameklab/com/MegaMekLab.java
- src/megameklab/com/ui/MegaMekLabMainUI.java
- src/megameklab/com/ui/dialog/AbstractMMLDialog.java
This is part of a suite-wide PR to create a standardized SuiteOptions, SuiteConstants, and SuitePreferences setup. This requires https://github.com/MegaMek/megamek/pull/3391 and https://github.com/MegaMek/mekhq/pull/3087.
For Review: The changes are in MegaMekLab and MMLOptions. Everything else is just renames.
> SuiteOptions: Naming standardization and finishing initial setup

- src/megameklab/com/printing/PrintMech.java
- src/megameklab/com/ui/combatVeh/CVEquipmentDatabaseView.java
- src/megameklab/com/ui/fighterAero/ASChassisView.java
- src/megameklab/com/ui/fighterAero/ASEquipmentDatabaseView.java
- src/megameklab/com/ui/largeAero/LAEquipmentDatabaseView.java
- src/megameklab/com/ui/mek/BMEquipmentDatabaseView.java
- src/megameklab/com/ui/supportVeh/SVEquipmentDatabaseView.java
- src/megameklab/com/util/UnitUtil.java
Fixes #1016 (as per request, the CASE / CASE II note is now printed with the header of all locations that have either system, as equipment or automatically for both Clan and IS)
Fixes #1012 (only allows Std Fusion and ICE engines on CF, not TO Large Engines as we don't seem to have them nor XXL engines which will receive errata to not be available for CF)
Fixes #1008 (now sets the correct minimum size value for all variable size equipment)
1016 and 1008 are in their own commits. But it's not that much code either way.
> Fixes for 1016, 1012, 1008

- .gitignore
- build.gradle
- src/megameklab/com/MMLConstants.java
- src/megameklab/com/MegaMekLab.java
This is the MML implementation for https://github.com/MegaMek/megamek/pull/3412
> Improved Initial Log Message

- build.gradle
- src/megameklab/com/printing/InventoryEntry.java
- src/megameklab/com/printing/InventoryWriter.java
- src/megameklab/com/printing/WeaponBayText.java
- src/megameklab/com/ui/EntitySource.java
- src/megameklab/com/ui/dialog/AbstractMMLButtonDialog.java
- src/megameklab/com/ui/dialog/settings/ColorSettingsPanel.java
- src/megameklab/com/ui/generalUnit/ArmorAllocationView.java
- src/megameklab/com/ui/generalUnit/BasicInfoView.java
- src/megameklab/com/ui/listeners/SVBuildListener.java
- src/megameklab/com/ui/util/AbstractEquipmentDatabaseView.java
- src/megameklab/com/ui/util/CritCellUtil.java
- src/megameklab/com/ui/util/EquipmentDatabaseCategory.java
- src/megameklab/com/ui/util/EquipmentTableModel.java
- src/megameklab/com/ui/util/IView.java
- src/megameklab/com/ui/util/IntRangeTextField.java
- src/megameklab/com/ui/util/ProtomekMountList.java
- src/megameklab/com/ui/util/SpringLayoutHelper.java
- src/megameklab/com/ui/util/SpringUtilities.java
- src/megameklab/com/util/CConfig.java
- src/megameklab/com/util/UnitUtil.java
This continues on from https://github.com/MegaMek/megamek/pull/3445 to fix the Javadoc build for MegaMekLab.
Akin to the previous one, there are still huge gaps in our Javadoc coverages, and tons of warnings.
> Fixing MegaMekLab's Javadoc Build

- megameklab/src/megameklab/printing/PrintMech.java
Writes the exact type of TSM to record sheet crit slots (Triple Strength Myomer / Industrial Triple Strength Myomer / Prototype Triple Strength Myomer).
Fixes #1042
> Issue 1042: Print the exact type of TSM to RS

- megameklab/src/megameklab/printing/PrintMech.java
- megameklab/src/megameklab/printing/PrintRecordSheet.java
- megameklab/src/megameklab/ui/fighterAero/ASBuildView.java
- megameklab/src/megameklab/ui/generalUnit/AbstractEquipmentTab.java
- megameklab/src/megameklab/ui/mek/BMBuildView.java
- megameklab/src/megameklab/ui/mek/BMStructureTab.java
- megameklab/src/megameklab/ui/protoMek/PMStructureTab.java
- megameklab/src/megameklab/ui/supportVehicle/SVCrewView.java
- megameklab/src/megameklab/ui/util/BAASBMDropTargetCriticalList.java
- megameklab/src/megameklab/ui/util/BAASCriticalTransferHandler.java
- megameklab/src/megameklab/ui/util/CriticalTableModel.java
- megameklab/src/megameklab/ui/util/SpringUtilities.java
- megameklab/src/megameklab/util/UnitUtil.java
This fixes all but four of the current LGTM issues for MML, including multiple resource leaks.
Once this is merged I'll fix the final four issues.
To Review:
Whitespace differences off, as I also fixed some whitespace problems.
> LGTM: Fixing the vast majority of open issues

- megameklab/src/megameklab/ui/util/AbstractEquipmentDatabaseView.java
- megameklab/src/megameklab/ui/util/EquipmentDatabaseCategory.java
Fixes #1045 
Requires MM #3474
Generally speaking, this adapts the equipment filtering somewhat to restore some missing equipment after the more extensive equipment table changes.
- Adds an "Industrial" filter toggle to CV and SV (since they have no "Physical" filter). Industrial will show Backhoe, Dumper etc. Industrial eqp no longer appears in "Other"
- Aero dont have access to industrial equipment except for the refueling drogue, which now appears in "Other"
- On Meks, industrial eqp is shown under "Physical" to relieve the "Other" category a bit and since the game effects are often similar
- Sponson turrets will appear again in "Other" for CV (SV handle them in the Structure tab)
- CV chassis mods again appear as they should in "Other"
- AMS and Laser AMS will now appear in "Other" in …
> Issue #1045: Equipment filters

- megameklab/src/megameklab/MegaMekLab.java
- megameklab/src/megameklab/ui/MegaMekLabMainUI.java
- megameklab/src/megameklab/ui/StartupGUI.java
- megameklab/src/megameklab/ui/dialog/LoadingDialog.java
DRAFT
Use shared methods across MM, MHQ and MML for display scaling and splash screens. 
depends on: https://github.com/MegaMek/megamek/pull/3473
> Displayscaling

- megameklab/src/megameklab/printing/InventoryWriter.java
- megameklab/src/megameklab/printing/PrintMech.java
- megameklab/src/megameklab/util/UnitUtil.java
As the title says...
Fixes #1022 
Also works on BA. BA have a bit of a formatting problem in that the equipment list often collides with the ammo list but that's not directly related to this issue.
> Issue 1022: Add RS ammo display to Mine/Sensor dispensers

- megameklab/src/megameklab/ui/battleArmor/BAStatusBar.java
- megameklab/src/megameklab/ui/combatVehicle/CVStatusBar.java
- megameklab/src/megameklab/ui/fighterAero/ASStatusBar.java
- megameklab/src/megameklab/ui/infantry/CIStatusBar.java
- megameklab/src/megameklab/ui/largeAero/DSStatusBar.java
- megameklab/src/megameklab/ui/largeAero/WSStatusBar.java
- megameklab/src/megameklab/ui/mek/BMStatusBar.java
- megameklab/src/megameklab/ui/protoMek/PMStatusBar.java
- megameklab/src/megameklab/ui/supportVehicle/SVStatusBar.java
Updates MML's status bars to display the dry unit cost (without ammo) instead of the full cost as "Dry cost: 123,346 C-bills". The full cost is now shown in the tooltip. The dry cost is already shown in the cost breakdown.
Im not sure if there can be a difference between dry and full for conventional infantry and there's a bug with BA costs (or at least the cost breakdown text). So I've just made that change for all unit types. The worst that can happen is that there's no difference.
> Show dry cost in Status bar and full cost in tooltip

- megameklab/src/megameklab/printing/PrintAero.java
- megameklab/src/megameklab/printing/PrintBattleArmor.java
- megameklab/src/megameklab/printing/PrintCompositeTankSheet.java
- megameklab/src/megameklab/printing/PrintEntity.java
- megameklab/src/megameklab/printing/PrintInfantry.java
- megameklab/src/megameklab/printing/PrintMech.java
- megameklab/src/megameklab/printing/PrintProtomech.java
- megameklab/src/megameklab/printing/PrintRecordSheet.java
- megameklab/src/megameklab/printing/PrintSmallUnitSheet.java
- megameklab/src/megameklab/printing/PrintTank.java
- megameklab/src/megameklab/printing/RecordSheetTask.java
- megameklab/src/megameklab/util/UnitPrintManager.java
This fixes #1068.
First two commits are a bunch of code cleanup, the third is the actual functionality changes to protect from multiple exceptions if there's no source image for some reason.
> 1068: Handling null source image document creation issues

- megameklab/resources/megameklab/resources/Views.properties
- megameklab/src/megameklab/ui/mek/BMEquipmentTab.java
- megameklab/src/megameklab/ui/mek/BMLAMFuelView.java
- megameklab/src/megameklab/ui/mek/BMStructureTab.java
- megameklab/src/megameklab/ui/util/EquipmentDatabaseCategory.java
- megameklab/src/megameklab/util/UnitUtil.java
Fixes #927 
Requires MM 3492
Adds an entry box for the amount of additional fuel a LAM carries. Changing the amount adds or removes 1 crit/1 ton Fuel equipment entries in the Equipment view that have to be placed in crit slots.
> MML Issue 927: Add LAM FuelTank input

- megameklab/src/megameklab/ui/generalUnit/TransportTab.java
- megameklab/src/megameklab/ui/mek/BMCriticalView.java
- megameklab/src/megameklab/ui/mek/BMUtils.java
- megameklab/src/megameklab/util/UnitUtil.java
This came out of fixing MM #3257 (Clan automatic CASE for PPC Capacitors):
- On Meks, the crit view now shows for each location if it has CASE. The Record Sheets do that already and it shows clearly if there is a Clan CASE present which is otherwise invisible. This was very useful for looking at this issue and I expect it would be useful for mixed units where Clan CASE is not automatic but can (theoretically) be added.
- Adds an MML-side method that adds and removes Clan auto-CASE as necessary. The MM side method that was previously called adds CASE but doesn't remove it (and MML has the better utility methods for doing so).
> MM #3257: Show CASE in the crit block title for Meks

- megameklab/src/megameklab/printing/PrintBattleArmor.java
Also includes a small update to readability.
SOURCES:
Field Manual: Periphery
Wars of Reaving Supplemental
> Update BA record sheet squad naming

- megameklab/src/megameklab/printing/reference/PhysicalAttacks.java
There was a UTF-8 literal causing an output encoding issue with the Push attack line in the Physical Attack table.  This changes the raw UTF-8 character to a Java Unicode literal. Fixes #1111
> Fixes an encoding issue for PDF record sheets with reference tables enabled.

- megameklab/src/megameklab/ui/protoMek/PMStructureTab.java
Using remaining tonnage for armor needs to be rounded down to whole armor points.
Fixes #933.
> Limit "use remaining tonnage" to total points for protomechs.

- megameklab/src/megameklab/ui/mek/BMCriticalTransferHandler.java
When dragging splittable equipment into a location, a secondary location is assigned whether used or not. Since the block that follows the modified line handles selecting the secondary location when needed, the initial value should be LOC_NONE.
Fixes #1125
> Don't assign secondary location to non-split equipment

- megameklab/resources/megameklab/resources/Dialogs.properties
- megameklab/src/megameklab/ui/MegaMekLabMainUI.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/dialog/settings/MiscSettingsPanel.java
- megameklab/src/megameklab/ui/util/IntRangeTextField.java
- megameklab/src/megameklab/util/CConfig.java
Fixes #1133 
This adds a safety prompt to all actions that cause loss of the current unit, i.e. Reset, Switch Unit Type, Load Unit, Quit (quit already had this prompt, it is now unified with the other actions).
For devs or others who like a little suspense there is a Misc Setting in the Settings menu to disable those prompts completely (all of them!)
> MML Issue 1133: more save prompts

- megameklab/src/megameklab/ui/util/IntRangeTextField.java
Fixes #1127 
JFormattedTextField says in its description that setting a DocumentFilter to it will result in unexpected behavior, which was visible in the MUL ID and year fields. This therefore:
- changes the IntRangeTextField to a JTextField and removes the Integer-Formatter. I could see no difference to before except that now the DocumentFilter works. 
- updates the document filter to allow entering "-" when the IntRangeTextField has no minimum or a negative minimum.
> MML Issue 1127: IntRangeTextField changes

- megameklab/data/images/recordsheets/templates_iso/mech_biped_default.svg
- megameklab/data/images/recordsheets/templates_iso/mech_biped_toheat.svg
- megameklab/data/images/recordsheets/templates_iso/mech_quad_default.svg
- megameklab/data/images/recordsheets/templates_iso/mech_quad_toheat.svg
- megameklab/data/images/recordsheets/templates_iso/mech_quadvee_default.svg
- megameklab/data/images/recordsheets/templates_iso/mech_quadvee_toheat.svg
- megameklab/data/images/recordsheets/templates_iso/mech_tripod_default.svg
- megameklab/data/images/recordsheets/templates_iso/mech_tripod_toheat.svg
- megameklab/data/images/recordsheets/templates_us/mech_biped_default.svg
- megameklab/data/images/recordsheets/templates_us/mech_biped_toheat.svg
- megameklab/data/images/recordsheets/templates_us/mech_quad_default.svg
- megameklab/data/images/recordsheets/templates_us/mech_quad_toheat.svg
- megameklab/data/images/recordsheets/templates_us/mech_quadvee_default.svg
- megameklab/data/images/recordsheets/templates_us/mech_quadvee_toheat.svg
- megameklab/data/images/recordsheets/templates_us/mech_tripod_default.svg
- megameklab/data/images/recordsheets/templates_us/mech_tripod_toheat.svg
MML has the code that changes the text from "Jumping:" to "Underwater:" but the labels are missing in the SVG templates.
Fixes #1147
> Fix label for UMU MP on mech record sheets

- megameklab/src/megameklab/ui/largeAero/LAEquipmentDatabaseView.java
Small craft use the large craft construction rules but differ in that they do not use weapons bays. Ammo should be added in single-ton lots rather than grouped together. The ammo is being added but not shown because the equipment panel doesn't account for multi-ton ammo for units without weapon bays.
Fixes #1166
> Add ammo to small craft in single-ton lots

- megameklab/src/megameklab/printing/reference/MekHitLocation.java
- megameklab/src/megameklab/printing/reference/PhysicalAttacks.java
This swaps it from using the dagger character (which does not properly load) to using the unicode character for it, which will load properly.
> Fixing Tripod Leg and Mech Spike Dagger Character Uses

- megameklab/data/images/recordsheets/templates_iso/fighter_aerospace_default.svg
- megameklab/data/images/recordsheets/templates_iso/fighter_conventional_default.svg
- megameklab/data/images/recordsheets/templates_iso/mech_biped_default.svg
- megameklab/data/images/recordsheets/templates_iso/mech_biped_toheat.svg
- megameklab/data/images/recordsheets/templates_iso/mech_lam_default.svg
- megameklab/data/images/recordsheets/templates_iso/mech_lam_toheat.svg
- megameklab/data/images/recordsheets/templates_iso/mech_quad_default.svg
- megameklab/data/images/recordsheets/templates_iso/mech_quad_toheat.svg
- megameklab/data/images/recordsheets/templates_iso/mech_quadvee_default.svg
- megameklab/data/images/recordsheets/templates_iso/mech_quadvee_toheat.svg
- megameklab/data/images/recordsheets/templates_iso/mech_tripod_default.svg
- megameklab/data/images/recordsheets/templates_iso/mech_tripod_toheat.svg
- megameklab/data/images/recordsheets/templates_us/fighter_aerospace_default.svg
- megameklab/data/images/recordsheets/templates_us/fighter_conventional_default.svg
- megameklab/data/images/recordsheets/templates_us/mech_biped_default.svg
- megameklab/data/images/recordsheets/templates_us/mech_biped_toheat.svg
- megameklab/data/images/recordsheets/templates_us/mech_lam_default.svg
- megameklab/data/images/recordsheets/templates_us/mech_lam_toheat.svg
- megameklab/data/images/recordsheets/templates_us/mech_quad_default.svg
- megameklab/data/images/recordsheets/templates_us/mech_quad_toheat.svg
- megameklab/data/images/recordsheets/templates_us/mech_quadvee_default.svg
- megameklab/data/images/recordsheets/templates_us/mech_quadvee_toheat.svg
- megameklab/data/images/recordsheets/templates_us/mech_tripod_default.svg
- megameklab/data/images/recordsheets/templates_us/mech_tripod_toheat.svg
- megameklab/src/megameklab/printing/PrintAero.java
- megameklab/src/megameklab/printing/PrintMech.java
- megameklab/src/megameklab/printing/PrintTank.java
Fixes #1169 
* Adds the engine rating to the engine type line on Combat Vees
* Adds a similar engine type line to Meks & Fighters
> Add the engine type to Mek, Fighter and Vee RS

- megameklab/src/megameklab/printing/StandardInventoryEntry.java
Fixes #1179 
This removes any unofficial weapons such as the C-Plasma Rifle from consideration in the method that finds if an (IS) or (C) label is to be added on a mixed tech unit.
(The method tries finding the equivalent of the weapon in question in the other tech base - now unofficials are ignored in this search meaning that it finds no C-Plasma Rifle and therefore does not need to add (IS) to the IS-Plasma Rifle).
> Issue 1179 (Plasma Rifle (IS) label)

- megameklab/src/megameklab/ui/mek/BMBuildView.java
- megameklab/src/megameklab/ui/mek/BMCriticalTransferHandler.java
Fixes #1197 
MM's #4007 is useful for this to be able to load mtfs correctly when such a split is used but the PRs are not dependent.
As an aside this also makes the right-click placement of equipment not show weapon spreads that aren't possible (like "CT/RT 8/1" when CT doesnt have 8 free slots)
> Issue1197 Allow split weapons between CT and H

- megameklab/build.gradle
This fixes #1188 and fixes #1218. MML uses MM's jar located in libs, not in same folder.
> Issues #1188, #1218: Fixing MML-only UNIX Jar Release

- megameklab/build.gradle
Resolves the following Eclipse IDE errors:
"The package org.w3c.dom is accessible from more than one module: , java.xml" and
"The package javax.xml.parsers is accessible from more than one module: , java.xml"
These packages are included as part of the Java Runtime Environment after Java 11?
I appears IntelliJ was fixed in the past but Eclipse was still having an issue due to transient dependencies due to the inclusion of the xml-apis from several included xml libraries.
This exclude in the gradle build file prevents Eclipse from tripping over this multiple dependency.
This was tested by building from both Eclipse and from the gradle wrapper.
Eclipse Version:
Version: 2023-03 (4.27.0)
Build id: 20230309-1520
> Fix: package org.w3c.dom is accessible from more than one module - Eclipse IDE

- megameklab/src/megameklab/ui/util/EquipmentDatabaseCategory.java
BA popup mines didn't fall into any filter category.
Fixes #1247
> Issue 1247: Show BA Popup Mine as Other Equipment

- megameklab/data/mechfiles/dropships/TRO3085/Cutting Edge/Clan/Vanir Assault Dropship (Standard).blk
- megameklab/data/mechfiles/warship/XTR/Republic III/Leviathan III Battleship.blk
Fix: MegaMek#4424 Spelling error in .blk files. Stringray->Stingray.
> Fix: MegaMek#4424 Spelling error in .blk files. Stringray->Stingray.

- megameklab/build.gradle
Reverting Gradle Build file change to enable Eclipse Multiple Dependency IDE errors.  Excluding xml-apis fixes Eclipse build errors, but it needed by megameklab to print unit sheets.  The print error was reported in #1263 for build 0.49.13
> Revert Eclipse Gradle Multiple Dependency fix. #1263

- megameklab/src/megameklab/printing/reference/PhysicalAttacks.java
- megameklab/src/megameklab/util/StringUtils.java
Fixes #1262 
Fixes #1258 
Fixes #1245 
Also now shows TSM damage for kick and punch attacks in brackets (note the kick damage for this Caesar 5D with Talons and TSM)
> Record Sheets: Update physical attack damage values in ref tables

- megameklab/src/megameklab/printing/InventoryWriter.java
- megameklab/src/megameklab/util/StringUtils.java
- megameklab/src/megameklab/util/UnitUtil.java
Fixes #1273 
@HammerGS I checked the Goth D in RS Golden Century (Coolant Pods not shown) and the Awesome 11R in XTRO Republic II (also not shown). But showing them makes sense, right?
> Record Sheets: Show Coolant Pods in the inventory

- megameklab/build.gradle
Second take at fixing the Eclipse IDE Multiple Module error in a way that doesn't also break Scaled Vector Graphics printing.  This attempt excludes the offending `xml-apis` group but then adds the `xml-apis-ext` as runtime only which ensures it is included in the final build but doesn't trip up Eclipse IDE.
With this fix I'm able successfully import the megameklab gradle project into the Eclipse IDE while still able to print and export-to-pdf.  Further test is needed to ensure no other edge cases trigger "class not found" errors.
> Eclipse IDE multiple Module error fix - take 2

- megameklab/src/megameklab/ui/util/AbstractEquipmentDatabaseView.java
- megameklab/src/megameklab/ui/util/EquipmentDatabaseCategory.java
This PR adds a filter toggle to the equipment database that will show all ammo instead of only ammo for weapons present on the unit. This is to facilitate creating ammo carrier units. (For technical reasons this toggle is present for all unit types even though most don't make good ammo trailers)
Fixes #1216
> Ammo w/o weapon filter

- megameklab/src/megameklab/ui/MegaMekLabMainUI.java
- megameklab/src/megameklab/ui/battleArmor/BABuildView.java
- megameklab/src/megameklab/ui/fighterAero/ASBuildTab.java
- megameklab/src/megameklab/ui/fighterAero/ASBuildView.java
- megameklab/src/megameklab/ui/fighterAero/ASCriticalView.java
- megameklab/src/megameklab/ui/fighterAero/ASMainUI.java
- megameklab/src/megameklab/ui/fighterAero/ASStructureTab.java
- megameklab/src/megameklab/ui/generalUnit/PreviewTab.java
- megameklab/src/megameklab/ui/largeAero/LABuildView.java
- megameklab/src/megameklab/ui/mek/BMBuildView.java
- megameklab/src/megameklab/ui/mek/BMCriticalTransferHandler.java
- megameklab/src/megameklab/ui/protoMek/PMBuildView.java
- megameklab/src/megameklab/ui/util/AbstractCriticalTransferHandler.java
- megameklab/src/megameklab/ui/util/BAASBMDropTargetCriticalList.java
- megameklab/src/megameklab/ui/util/BAASCriticalTransferHandler.java
- megameklab/src/megameklab/ui/util/CriticalTransferHandler.java
- megameklab/src/megameklab/ui/util/RefreshListener.java
- megameklab/src/megameklab/util/UnitUtil.java
Fighter units use the crit slot system. Equipment is always shown in the crit view as if there were no gaps but removing e.g. equipment no. 2 in a location will currently leave the second slot empty. This leads to the right-click menu not working for some equipment after removing another equipment.
This PR compacts the crit slots on fighters when equipment is removed (deleted or removed by menu or dragged out) from a location, so that there don't remain empty crit slots between equipment. The change is not visible except for the popup menu now working more consistently.
Edit:
This proved a bit of a rabbit hole. So this PR now also:
- Removes the ability to rear-mount weapons on fighters(!) according to TM p.195 (only AFT-mounted weapons can be rear-facing)
- Makes the preview tab update …
> AS Crit View: Compact criticals after removing equipment

- megameklab/src/megameklab/ui/util/EquipmentDatabaseCategory.java
This adds prototype filtering for MiscTypes. In other words, when prototype equipment is hidden, things like Proto Artemis or CASE-P are also hidden.
> Equipment Database: Also check MiscType for the prototype flag

- megameklab/src/megameklab/ui/battleArmor/BABuildView.java
- megameklab/src/megameklab/ui/battleArmor/BAEquipmentDatabaseView.java
This relaxes how DWPs can be installed on BA in that DWP is no longer hidden in equipment and blocked from being used (install weapons to it) by the BA having not enough MP (which could be difficult to see for the users). Instead, in the accompanying PR for MM, BA tests are added to make BA invalid in that case among others.
Although it doesnt automatically set MP, I think it Fixes #275
> BA construction: Allow easier installation of DWP

- megameklab/src/megameklab/ui/MenuBar.java
Adds a conditional exit function to wrap the existing event handler that never actually exits.
Close #1292
> Let File -> Exit item actually call System.exit()

- megameklab/resources/megameklab/resources/Tabs.properties
- megameklab/src/megameklab/ui/generalUnit/TransportTab.java
- megameklab/src/megameklab/ui/supportVehicle/SVMainUI.java
- megameklab/src/megameklab/ui/supportVehicle/SVStructureTab.java
This fix adds support for maximum door counts for Fixed-Wing Support Vehicles, as well as a count of minimum doors required for all transport bays, based on TM errata 6.0.
This fix changes the Transport Tab refresh behavior: now, when the chassis type is changed in the Structure Tab, the Transport Tab will be completely re-initialized.  This is so that new Fixed Wing Support Vehicles properly display the door count information (currently it only displays when loaded from a file or the chache).
NOTE: depends on the same-name PR for MegaMek, which adds the 'minDoors' field for every Bay type and corrects the Max Door check in TestAero.java.  Do not pull prior to that PR being pulled.  PR is: https://github.com/MegaMek/megamek/pull/4691
> Fix #1230: 0 Max Bay Doors on Large Fixed-Wing Sup

- megameklab/src/megameklab/ui/battleArmor/BACriticalSuit.java
- megameklab/src/megameklab/ui/util/BAASBMDropTargetCriticalList.java
- megameklab/src/megameklab/ui/util/CritListCellRenderer.java
Problem:
Deleting multi-slot equipment, or indeed deleting _any_ equipment
while multi-slot equipment is installed in a suit, causes a Null
Pointer Exception.
This is due to the way CritListCellRenderer() creates new slot entries
when refreshing; multi-slot items appear to return multiple indexes
despite only occupying one equipment entry on the BA itself, which
causes `unit.getEquipment(eqId);` to return a null Mounted entry.
Solution:
Since A) this is specific to the MML BA criticals table and nothing
else, B) incredibly annoying to debug, and C) of no impact whatsoever
if we just ignore this problem, I've added a check to see if the eq
check returns null or not.  This solves the NPE problem and I don't
really see any reason to delve deeper into the multi-slots issue
when they are …
> Fix #1287: NPE when deleting multi-slot BA equip.

- megameklab/build.gradle
From the manifest currently:
```Class-Path: MegaMek.jar lib/megamek-0.49.15-SNAPSHOT.jar  lib/jaxb-runtime-4.0.1.jar```
The MegaMek.jar is in the lib directory rather than the top-level directory as expected by the manifest. There is no lib/megamek-0.49.15-SNAPSHOT.jar file. This is included from the list of dependencies. It used to be filtered out but the filter was removed by #1219, which did nothing to fix the actual issue.
I have restored the filter to remove the useless entry and fixed the path to the MegaMek.jar path, and tested it to be certain it works. After the change the manifest starts like this:
```Class-Path: lib/MegaMek.jar lib/jaxb-runtime-4.0.1.jar```
Fixes #1268
> Fix class path in manifest

- megameklab/src/megameklab/util/UnitUtil.java
This will fix a subtle error where `.contains()` can be _called_ on one EnumSet from another but will always return false;
the proper method is `.containsAll()` or, in this case, `.equals()`.
See related PRs in MekHQ and MegaMek as well.
> Fix MML #3761: update munitions equality tests

- megameklab/src/megameklab/ui/mek/BMChassisView.java
When I added torso-mounted cockpits for IMs a couple years ago I inadvertently dropped the standard cockpit from the available options.While technically not the same part, MegaMek uses COCKPIT_STANDARD to indicate advanced fire control for IMs, and similarly a primitive cockpit for primitive IMs with advanced fire control.
Fixes #1330.
> Restore option of advanced fire control for IndustrialMechs

- megameklab/resources/megameklab/resources/Views.properties
- megameklab/src/megameklab/printing/PrintEntity.java
- megameklab/src/megameklab/ui/battleArmor/BAStructureTab.java
- megameklab/src/megameklab/ui/combatVehicle/CVStructureTab.java
- megameklab/src/megameklab/ui/fighterAero/ASStructureTab.java
- megameklab/src/megameklab/ui/generalUnit/BasicInfoView.java
- megameklab/src/megameklab/ui/infantry/CIStructureTab.java
- megameklab/src/megameklab/ui/largeAero/DSStructureTab.java
- megameklab/src/megameklab/ui/largeAero/WSStructureTab.java
- megameklab/src/megameklab/ui/listeners/BuildListener.java
- megameklab/src/megameklab/ui/mek/BMStructureTab.java
- megameklab/src/megameklab/ui/protoMek/PMStructureTab.java
- megameklab/src/megameklab/ui/supportVehicle/SVStructureTab.java
Requires MegaMek/megamek#4903
This adds a unit role dropdown to the basic unit info
Fixes #1332
> Allow unit role selection in MML

- megameklab/src/megameklab/ui/battleArmor/BAStructureTab.java
Adds a spinner for each BA manipulator that allows setting the size. This is needed for setting the capacity of the cargo lifter manipulator. The cargo lifter requires two matching manipulators, so only one spinner is necessary, but the code is written to allow for the possibility of another type of manipulator existing that does not require matching. There are two spinners, but when matched only one of them is enabled. This also gives a visual indicator that the value is the capacity of one manipulator rather than the combined capacity.
Closes MegaMek/megamek#4833.
> BA Manipulator size controls

- megameklab/src/megameklab/ui/infantry/CIStructureTab.java
1. Refreshes the status bar and preview tab when the size of the unit changes.
2. When the number of secondary weapons is set to zero, the secondary weapon is removed but the secondary weapon count field is not being set. This results in one or more unarmed troopers in a squad.
Fixes #1005
> Conventional infantry fixes

- megameklab/src/megameklab/ui/combatVehicle/CVEquipmentDatabaseView.java
- megameklab/src/megameklab/ui/fighterAero/ASEquipmentDatabaseView.java
- megameklab/src/megameklab/ui/largeAero/LAEquipmentDatabaseView.java
- megameklab/src/megameklab/ui/mek/BMEquipmentDatabaseView.java
- megameklab/src/megameklab/ui/mek/BMStatusBar.java
- megameklab/src/megameklab/ui/protoMek/PMEquipmentDatabaseView.java
- megameklab/src/megameklab/ui/supportVehicle/SVEquipmentDatabaseView.java
- megameklab/src/megameklab/util/UnitUtil.java
removeOneShotAmmo in UnitUtil removes all unallocated ammo but during construction all types of ammo may still be unallocated, not only OS ammo. This PR makes it so when adding an OS weapon or Infantry weapon on SV/PM only the ammo linked to that weapon is removed.
Fixes #1334
> Issue #1334: remove only specific OS/Infantry ammo

- megameklab/src/megameklab/ui/util/EquipmentDatabaseCategory.java
Fixes #1353 
Coolant Pods now show up in "Other", not "Ammo" and are no longer influenced by the "unusable ammo" filter
> Coolant Pods equipment category fix

- megameklab/src/megameklab/ui/combatVehicle/CVStatusBar.java
- megameklab/src/megameklab/ui/generalUnit/StatusBar.java
- megameklab/src/megameklab/ui/mek/BMStatusBar.java
- megameklab/src/megameklab/ui/protoMek/PMStatusBar.java
- megameklab/src/megameklab/ui/supportVehicle/SVStatusBar.java
The statusbars were showing the used slots instead of free slots when the label said "Free Slots:". Also change a button label to reduce its width.
> StatusBar: correct free slot displays

- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/StartupGUI.java
- megameklab/src/megameklab/ui/dialog/PrintQueueDialog.java
This PR fixes some ungraceful exceptions when a unit file is to be selected but the unit selector is closed without a selection.
Fixes MegaMek/megameklab#1370
> Handle no unit selection

- megameklab/src/megameklab/util/UnitUtil.java
BattleMeks may not mount cargo containers. Other unit types are not affected by the change.
Fixes #1309
> Restrict cargo containers to industrial meks

- megameklab/src/megameklab/printing/PrintInfantry.java
Adds the information mentioned in #1358 to the record sheets for beast-mounted infantry.
Some of examples of the generated record sheets:
Edit by Juliez:
Fixes #1358
> Beast-mounted infantry record sheet improvements

- megameklab/src/megameklab/printing/InventoryWriter.java
Brings the BA Bay capacity in line with the table in TM (p. 239), which shows bay weight/slots per trooper rather than per squad/point.
Fixes #1033
> Show BA Bay capacity on record sheet by troopers rather than squads.

- megameklab/src/megameklab/printing/PrintBattleArmor.java
Fixes #1377 
Will now always print Point for Sqd5 BAs and Suit for single troopers. If we have a way to distinguish IS maniples from Stars, we can update this.
> Issue 1377 BA squad types

- megameklab/src/megameklab/ui/battleArmor/BAEnhancementView.java
This removes the checkbox disabling from BA enhancements (partial wings, boosters). In other words, checkboxes are always available, incorrect selections make the unit invalid which gives the user a comment on whats wrong. This is accompanied by MegaMek/megamek#5006 that allows partial wings with mech. jump boosters.
Fixes #1289
> BA boosters/partial wing: update checks and gui

- megameklab/src/megameklab/ui/combatVehicle/CVStructureTab.java
- megameklab/src/megameklab/ui/fighterAero/ASStructureTab.java
- megameklab/src/megameklab/ui/generalUnit/summary/CockpitSummaryItem.java
- megameklab/src/megameklab/ui/generalUnit/summary/GyroSummaryItem.java
- megameklab/src/megameklab/ui/generalUnit/summary/MyomerEnhancementSummaryItem.java
- megameklab/src/megameklab/ui/generalUnit/summary/UnitTypeSummaryItem.java
- megameklab/src/megameklab/ui/largeAero/DSStructureTab.java
- megameklab/src/megameklab/ui/largeAero/WSStructureTab.java
- megameklab/src/megameklab/ui/mek/BMStructureTab.java
- megameklab/src/megameklab/ui/protoMek/PMStructureTab.java
- megameklab/src/megameklab/ui/supportVehicle/SVStructureTab.java
Adds 
- gyro and cockpit availability info for meks
- cockpit info to fighters
- unit construction availability to all units
Fixes #1081
> Summary updates

- megameklab/src/megameklab/ui/util/CritCellUtil.java
- megameklab/src/megameklab/util/UnitUtil.java
This slightly changes crit cell display (not for record sheets, only for construction) to
- not show "1 shot" for Coolant Pods (that are implemented as AmmoType)
- use the equipment short name if the standard name is longer than 22 characters (magic number). This affects only a handful of equipment like AES or HarJel III. The tooltip still shows the full equipment name
> Crit cell display improvements

- megameklab/src/megameklab/printing/InventoryWriter.java
Removes BA RS equipment overlap ... most of the time.
This PR reduces the minimum line distance and font size a bit, turns around scaling to reduce line spacing before font size and removes a line width adjustment for the location column that shouldn't be done on BA.
Edit: forgot to add what the actual change is: the scaleText() method had a logic error that would not ever let it reduce line spacing.
instead of 
Unfortunately for some equipment the calculated line count is not quite right, causing overlap, and, so far, I was unable to see why. Maybe because the line counter will only count 2 lines at most while the actual equipment may even use 3 lines.
As this affects other unit types as well, I printed an Ares Hera and it still works
> fix (partly) BA equipment text overlap

- megameklab/src/megameklab/ui/MenuBar.java
Uses the new WeightDisplayDialog.
Requires MegaMek/megamek#5061
Fixes #494
> Weight Breakdown Adaptation

- megameklab/src/megameklab/printing/PrintAero.java
- megameklab/src/megameklab/printing/PrintTank.java
> Fix record sheet label for infantry compartment

- megameklab/src/megameklab/ui/util/BayWeaponCriticalTree.java
Fixes #1086
Requires MegaMek/megamek#5081
> Allow subcapital weapons to be placed in corresponding capital weapon bay

- megameklab/src/megameklab/ui/generalUnit/StatusBar.java
Account for laser insulator, ppc capacitor, and RISC laser pulse module when calculating estimated heat.
See #1151
> Include equipment that modifies weapon heat in status bar

- megameklab/src/megameklab/ui/largeAero/DSStructureTab.java
The maximum number of doors depends on the ship tonnage and needs to update. The JS/WS/SS structure tab is already doing this correctly.
Fixes #1183
> Refresh transport tab when DS tonnage changes

- megameklab/src/megameklab/ui/mek/BMStructureTab.java
When replacing spreadable fixed equipment it is being removed from the mech while iterating over the list.
Fixes #1171
> Fix concurrent modification exception when resetting system crits

- megameklab/src/megameklab/printing/PrintBattleArmor.java
- megameklab/src/megameklab/ui/generalUnit/ArmorAllocationView.java
- megameklab/src/megameklab/ui/generalUnit/summary/ArmorSummaryItem.java
- megameklab/src/megameklab/ui/protoMek/PMStructureTab.java
- megameklab/src/megameklab/util/UnitUtil.java
MML part of MegaMek/megamek#5101
> Armor rework, part 1a

- megameklab/resources/megameklab/resources/Dialogs.properties
- megameklab/resources/megameklab/resources/Menu.properties
- megameklab/resources/megameklab/resources/Views.properties
- megameklab/src/megameklab/printing/MekChassisArrangement.java
- megameklab/src/megameklab/printing/PrintAero.java
- megameklab/src/megameklab/printing/PrintCapitalShip.java
- megameklab/src/megameklab/printing/PrintDropship.java
- megameklab/src/megameklab/printing/PrintEntity.java
- megameklab/src/megameklab/printing/PrintMech.java
- megameklab/src/megameklab/printing/PrintSmallUnitSheet.java
- megameklab/src/megameklab/printing/PrintTank.java
- megameklab/src/megameklab/ui/MegaMekLabMainUI.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/dialog/settings/ExportSettingsPanel.java
- megameklab/src/megameklab/ui/dialog/settings/SettingsDialog.java
- megameklab/src/megameklab/ui/generalUnit/BasicInfoView.java
- megameklab/src/megameklab/ui/generalUnit/StatusBar.java
- megameklab/src/megameklab/ui/listeners/BuildListener.java
- megameklab/src/megameklab/ui/mek/BMStructureTab.java
- megameklab/src/megameklab/util/CConfig.java
- megameklab/src/megameklab/util/ImageHelper.java
This has adaptations for MegaMek/megamek#5107
On Meks, there is now a field to set the clan chassis name (such as Timber Wolf)
Also, this adds a config setting for record sheets to arrange the name of Clan meks with a dual name such as Mad Cat (Timber Wolf) in various ways.
There are adaptations to MML's ImageHelper (essentially the same as MM's FluffImageHelper), most of which was not used and was adapted to reuse MM's fluff stuff more.
> Mek Clan Chassis Name - MML updates, record sheet

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/nightly-maven-ci.yml
Github action fix for Gradle JVM memory thrashing that can occur for builds the depend on megamek. 
I was able to re-create the JVM thrashing and fix by doing a clean build with a clean (not pre-compiled) dependent megamek project.
See MegaMek/mekhq#3785
> Gradle build JVM thrashing fix.

- megameklab/src/megameklab/ui/generalUnit/StatusBar.java
As the title says, adds a max weight calculation for BA to the StatusBar as entity.getWeight doesn't return the correct result.
> StatusBar: calculate the correct total max weight for BA

- megameklab/src/megameklab/printing/PrintEntity.java
- megameklab/src/megameklab/ui/battleArmor/BAStructureTab.java
- megameklab/src/megameklab/ui/generalUnit/BAProtoArmorView.java
- megameklab/src/megameklab/ui/generalUnit/summary/ArmorSummaryItem.java
- megameklab/src/megameklab/ui/listeners/ArmorAllocationListener.java
- megameklab/src/megameklab/ui/protoMek/PMMainUI.java
- megameklab/src/megameklab/ui/protoMek/PMStructureTab.java
- megameklab/src/megameklab/util/UnitUtil.java
MML part of MegaMek/megamek#5116
> Armor rework, part 1b

- megameklab/src/megameklab/printing/PrintMech.java
CGL request: Removes the unicode character 2212 (a longer dash that aligned better with a plus) from the RS heat tables.
> Revert to the normal "-" character in RS heat table movement penalties

- megameklab/data/images/recordsheets/templates_iso/tables_vtol.svg
- megameklab/data/images/recordsheets/templates_us/tables_vtol.svg
Fixes #1400 
The location table was correct (TO:AR p.203) but the subtexts were not.
> Correct vtol hit location table subtext

- megameklab/src/megameklab/ui/generalUnit/StatusBar.java
When the "Validate" button in the status bar is clicked with CTRL held, instead of the validation dialog the internal state of the entity (DebugEntity.copyEquipmentState() is copied to the clipboard for inspection in a text editor. The example shows the current problem of two different armor types currently being loaded (one should be structure). I've intentionally not added a tooltip or something; this is purely for debugging. There is an accompanying MM PR that updates a few string outputs to improve clarity.
> Debug helper update

- megameklab/src/megameklab/util/MekUtil.java
I think the recent ArmorType change made all armors unhittable and spreadable, even those without crit requirements. This updates a test so that when they don't need crits, they don't get automatically placed in locations.
Fixes #1419
> MekUtil: fix automatic placement of armors without crit requirement

- megameklab/src/megameklab/ui/generalUnit/StatusBar.java
Fixes #1421 
The explicit heat additions were unnecessary as the code below adds heat for all misc equipment
> Remove misc heat duplication in the status bar

- build.gradle
- megameklab/build.gradle
- megameklab/unittests/megameklab/ui/util/EquipmentTableModelTest.java
Fixes some problems in #1433 and cleans up test code.
The dependency block in the build file in the project root does nothing, as there is no source code there.
Mockito should use testImplementation instead of implementation because it is not needed on the classpath when running MML, and should not be added to the libraries in the packaged distribution.
> Dependency cleanup

- megameklab/src/megameklab/ui/generalUnit/TransportTab.java
When assigning the maximum value to the spinner for number of bay doors it adds the current number of doors on the bay to the number available for assignment. This works fine for aerospace units, which have maximum number based on weight, but support vehicles have no such maximum. The number of available doors is Integer.MAX_VALUE (I'm not sure what the -1 was for, but it prevented the issue from popping up as long as there was only one door). When added to the number of doors currently, it can result in integer overflow so that the maximum is a negative number. This causes an IllegalArgumentException because it doesn't meet the requirement that min <= value <= max.
Fixes #1242
> Fix integer overflow in determining maximum number of bay doors

- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/dialog/UiLoader.java
- megameklab/src/megameklab/ui/fighterAero/ASMainUI.java
This reverts some use of ETYPE_AEROSPACEFIGHTER in MML, as it was no longer calling up the ASF UI for ASF units (It was not used consistently enough). Since the etypes are, in MML, only used to signal the UI that is to be loaded and have no direct connection to the actual etype in the units I reverted to the old AERO etype.
> Revert to use ETYPE_AERO in MML

- megameklab/src/megameklab/printing/reference/ClusterHitsTable.java
Adds 2-4 columns for machine gun arrays. Also adds columns for streak launchers, since they fire as non-streak launchers when influenced by Angel ECM and the 7 column is needed when affected by an AMS.
Fixes #1283
> Add columns to cluster hits table on record sheet for MGA and streak weapons

- megameklab/src/megameklab/ui/mek/BMStructureTab.java
The trailing space on the name of industrial armor (which I still don't know the reason for, but there was a comment that says it's deliberate) is causing a failure when using a name lookup. Leaving the space out of the lookup names causes a failure when loading from mtf files, so the long term solution may be to add additional lookup names. Or remove the trailing space and see if anything breaks.
Fixes #1440
> Fix NPE in armor type lookup for industrial.

- megameklab/src/megameklab/util/UnitUtil.java
Fixes #1432 
If the weapon became illegal with the year change, it actually *wouldn't* be reset.
> Fix infantry weapon resetting on year change

- megameklab/src/megameklab/ui/generalUnit/FluffTab.java
I forgot to add a button to remove an embedded fluff image from a unit file. This PR corrects that.
> Add a button to the fluff tab to remove an embedded fluff image

- megameklab/src/megameklab/ui/dialog/MegaMekLabUnitSelectorDialog.java
Makes the obvious change of showing the unit icon in the unit selector in MML since we now have the icons there
> Show unit icon in the Unit Selector

- megameklab/src/megameklab/ui/dialog/MegaMekLabUnitSelectorDialog.java
If a game year is set and variable tech level is enabled, use that year for tech level in unit search. 
This _only_ affects the calculated tech level, it doesn't hide units that only exist after the given year.
> If 'Use game year' enabled, use that year for unit search

- megameklab/src/megameklab/ui/dialog/MegaMekLabUnitSelectorDialog.java
This is just #1465 but I missed the fact that there's a second constructor (used for the queue-print dialog).
> Use configured game year in both cases of unit search

- megameklab/src/megameklab/util/UnitUtil.java
Partially addresses #1466 by making it so MML cannot be used to create illegal units as described in that issue.
Units created before this patch which have field guns at the Standard tech level will still be considered legal and load as Standard units. I'm not sure how this could be fixed, I tried updating `Infantry::addSystemTechAdvancement` to add a tech advancement with Advanced when field guns were present, but this didn't seem to do anything at all.
> Reset CI field guns when setting tech level to Standard

- megameklab/src/megameklab/util/MekUtil.java
> Match critical slot sort order to specification

- megameklab/data/forcegenerator/factions.xml
Fix case error in Circinus Federation parent faction "WOB.pm" (should be "WOB.PM").
Testing:
- Ran all 3 projects' unit tests
- Ran MekHQ with campaign save and custom units from MegaMek/mekhq#3803 and confirmed proper operation.
> MML portion of fix for MHQ 3803: Fixed WOB.pm/PM mismatch

- megameklab/src/megameklab/printing/reference/GroundToHitMods.java
- megameklab/src/megameklab/ui/mek/BMChassisView.java
- megameklab/src/megameklab/ui/mek/BMMainUI.java
- megameklab/src/megameklab/ui/mek/BMStructureTab.java
Makes a distinction between tripod industrial mechs with and without active fire control. Also fixes a couple of bugs I noticed during testing, involving cockpit type not updating when switching an industrial mech to tripod or switching between standard weight and superheavy.
Requires Megamek/megamek#5291.
Fixes #1315
Fixes #1371
> Industrial tripod cockpit

- megameklab/src/megameklab/util/UnitUtil.java
Don't use the `.getShortName()` value for AmmoType instances in the Equipment List of the Crits tab.
Testing:
- Added offending ammo types from the bug to new units.
- Ran all three projects' unit tests.
Close MegaMek/megamek#5252
> Fix #5252: critical assignment tab eq list missing keywords like "Ammo" and "[Half]" or "[Full]"

- megameklab/src/megameklab/ui/MenuBar.java
I, and others I've heard from, occasionally make the mistake of creating a unit, forgetting to allocate some equipment or other, and then printing it, only to wonder where the equipment went. 
This change makes it so when printing the current unit, a warning is shown if it is invalid, same as if you tried to save it, because not everyone saves their units before printing them.
> Show a warning when attempting to print the invalid current unit

- megameklab/src/megameklab/ui/generalUnit/MovementView.java
Fixes the tooltip displayed for the final Jump MP box, for BA Jump MP with Partial Wing (the actual jump calc fix is in MM).
Testing:
- Ran both MM and MML unit tests (MHQ still broken)
- Verified correct tooltip value is displayed in MML
Close #1497
> Add separate handling for BA PW jump bonus tooltip

- megameklab/resources/megameklab/resources/Menu.properties
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/generalUnit/PreviewTab.java
Closes #1513 
Currently just adapts the HTML formatting to Discord by applying bold and underline as appropriate, colors are technically supported but they're only used by the HTML export when the unit has damage.
Suggestions for sprinkling in additional colors welcome in a separate issue. 
Depends on MegaMek/megamek#5533
> Add discord-formatted export support

- megameklab/src/megameklab/printing/PrintEntity.java
Now that edge abilities are all on by default, printing record sheets from a MUL looks like this:
> Don't print Edge abilities of pilots

- megameklab/resources/megameklab/printing/reference/ControlRollTable.properties
- megameklab/src/megameklab/printing/reference/AeroToHitMods.java
- megameklab/src/megameklab/printing/reference/ControlRollTable.java
The optional reference tables on aerospace record sheets shows the hit modifier for pilot/crew damage as +2, but it should be +1/hit.
> Fix to-hit modifier for pilot damage on aerospace record sheets.

- megameklab/src/megameklab/printing/PrintInfantry.java
Conventional infantry edition of #1520.
> Don't print Edge abilities of troopers

- megameklab/src/megameklab/ui/infantry/CIFieldGunView.java
Currently Arrow IV bombs are listed as a valid field artillery option for CI units (because they are, technically, artillery).
Fix filters out any artillery weapons that also have the Space Bomb flag (currently only the AIV bombs).
Testing:
- Manually checked CI field artillery options before and after fix.
- Ran all three projects' unit tests.
Close #1533
> Fix 1533: Filter out space bomb artillery (only Arrow IV Bombs for now)

- megameklab/src/megameklab/ui/generalUnit/MVFArmorView.java
MML side of fix for various NPEs and loading issues in MegaMek/megameklab#1537.
Disable the Armor Tech Rating chooser when non-BAR armor is chosen, to prevent confusion and also stop random fiddling with the chooser causing the Chassis Tech Rating (and thus weight) to fluctuate.
Testing:
- Loaded previously-failing files after adjusting them manually, then confirmed re-saving them with the patched code fixed all issues.
- Ran all three projects' unit test suites
Close #1537
> MML portion of fix for #1537: Disable Tech Rating chooser for non-BAR armor in SVs

- .github/workflows/ci.yml
- .github/workflows/nightly-ci.yml
- build.gradle
- megameklab/build.gradle
- megameklab/sentry.properties
- megameklab/src/megameklab/MMLConstants.java
- megameklab/src/megameklab/MMLOptions.java
- megameklab/src/megameklab/MMLOptionsChangedEvent.java
- megameklab/src/megameklab/MegaMekLab.java
Updated and fixed warnings in 4 files.
> Added Sentry

- megameklab/src/megameklab/ui/generalUnit/RecordSheetPreviewPanel.java
A feature I thought of right after #1553 got merged in. Lets you copy the RS to the clipboard as an image.
> Allow right-click-to-copy for RS preview

- megameklab/src/megameklab/printing/PrintRecordSheet.java
- megameklab/src/megameklab/printing/reference/AeroToHitMods.java
- megameklab/src/megameklab/printing/reference/ControlRollTable.java
- megameklab/src/megameklab/printing/reference/DrivingSkillRollMods.java
- megameklab/src/megameklab/printing/reference/GroundToHitMods.java
- megameklab/src/megameklab/printing/reference/MovementCost.java
- megameklab/src/megameklab/printing/reference/ProtomekSpecialHitLocation.java
- megameklab/src/megameklab/printing/reference/ReferenceTable.java
- megameklab/src/megameklab/printing/reference/ReferenceTableBase.java
Previously row shading only existed for tables baked into the svgs of record sheet tables. 
This pr adds row shading for all the reference tables which are proceduraly generated. 
Care was taken to ensure the more unusually laid-out tables are shaded properly, but it's possible I missed something and will likely ask the QA testers to generate record sheets for all sorts of units and make sure they look ok with shading.
Shaded rows look like this:
The example is for vehicles, but all unit types are supported.
> Row shading for procedurally generated reference tables

- megameklab/resources/megameklab/printing/reference/ClusterHitsTable.properties
- megameklab/src/megameklab/printing/PrintCompositeTankSheet.java
- megameklab/src/megameklab/printing/PrintMech.java
- megameklab/src/megameklab/printing/PrintSmallUnitSheet.java
- megameklab/src/megameklab/printing/PrintTank.java
- megameklab/src/megameklab/printing/reference/ClusterHitsTable.java
- megameklab/src/megameklab/printing/reference/MekLocationAndClusterTable.java
Similar to the current feature which replaces Mek fluff art with a table including hit location and cluster tables, this does a similar thing for vehicles.
Since vehicle sheets already come with hit location tables, this only includes cluster tables.
These look like this:
> Replace vehicle fluff art with cluster table when condensed reference tables enabled

- megameklab/data/mechfiles/mechs/3085u/Phoenix/Thunderbolt TDR-7SE.mtf
- megameklab/data/mechfiles/mechs/3085u/Phoenix/Thunderbolt TDR-9M.mtf
- megameklab/data/mechfiles/mechs/3085u/Phoenix/Thunderbolt TDR-9NAIS.mtf
- megameklab/data/mechfiles/mechs/3085u/Phoenix/Thunderbolt TDR-9Nr.mtf
- megameklab/data/mechfiles/mechs/3085u/Phoenix/Thunderbolt TDR-9T.mtf
- megameklab/data/mechfiles/mechs/Rec Guides ilClan/Vol 15/Thunderbolt TDR-7M.mtf
- megameklab/data/mechfiles/mechs/Rec Guides ilClan/Vol 15/Thunderbolt TDR-7S.mtf
- megameklab/data/mechfiles/mechs/Rec Guides ilClan/Vol 15/Thunderbolt TDR-8M.mtf
This PR adds the string `CHASSIS` to the `systemmanufacturer` key of the following MTF files:
* Thunderbolt_TDR-7M
* Thunderbolt_TDR-7S
* Thunderbolt_TDR-7SE
* Thunderbolt_TDR-8M
* Thunderbolt_TDR-9M
* Thunderbolt_TDR-9NAIS
* Thunderbolt_TDR-9Nr
* Thunderbolt_TDR-9T
I encountered this issue while working on my  [MTF to JSON converter](https://github.com/juk0de/mtf2json). Initially, I thought it was just an inconsistency, but these eight files are the only biped mech files missing the `CHASSIS` string. Therefore, I believe it is an ordinary bug, so I decided to fix it.
> Add missing 'CHASSIS' key to some Thunderbolt MTF files

- megameklab/resources/megameklab/resources/Dialogs.properties
- megameklab/src/megameklab/printing/PrintSmallUnitSheet.java
- megameklab/src/megameklab/printing/reference/ReferenceTable.java
- megameklab/src/megameklab/ui/generalUnit/RecordSheetPreviewPanel.java
- megameklab/src/megameklab/util/UnitPrintManager.java
- megameklab/unittests/megameklab/printing/PrintSmallUnitSheetTest.java
- megameklab/unittests/megameklab/testing/util/InitializeTypes.java
- megameklab/unittests/megameklab/ui/util/EquipmentTableModelTest.java
This PR collects several bug fixes and improvements that are somewhat related which I worked on at the same time.
- Row shading for tables looks better, the shading is now centered within the table.
- Record sheet preview for small units (CI/BA/Protos) was fixed to not cut off the right edge of the sheet.
- The option to replace mek fluff art with tables has been reworded to indicate it works on more than just meks.
- Small units will now include a cluster table instead of empty space when there aren't enough units to fill a whole sheet.
- The code that detects when a small unit sheet is full has been factored out into its own method and given unit tests.
> Record sheet fixes and improvements

- megameklab/src/megameklab/ui/dialog/PrintQueueDialog.java
- megameklab/src/megameklab/util/UnitPrintManager.java
Closes #1581.
This PR contains two features:
- When exporting from MUL to PDF, prefill the name of the pdf with the name of the mul file.
- Add a checkbox to the print queue dialog when printing from MUL to adjust the BV displayed on the record sheet for force modifiers like TAG and C3. BV is _always_ adjusted for pilot skill regardless of this checkbox.
> Add toggle for RS adjusted BV printing, and set default export filename

- megameklab/src/megameklab/ui/dialog/PrintQueueDialog.java
Closes #1592.
In addition to letting you reorder the units in a MUL file, this also allows you to make a MUL file directly in MML, without involving MM, although you'll still need to involve MM to set pilot data or wire C3. 
This PR also enables you to add units from cache when printing from a MUL file to add additional units to it, but the additional units won't have pilot data. 
Eventually this dialog should have a way to customize units directly, but that's a more long-term goal.
> Allow saving a MUL file from the queue-to-print dialog. 

- megameklab/src/megameklab/printing/PrintAero.java
- megameklab/unittests/megameklab/printing/PrintSmallUnitSheetTest.java
Adds a safety check for the MML print code to prevent an NPE when an Aerospace unit's Engine isn't populated.
This _shouldn't_ happen, and is nominally controlled by MM code, but if it _does_, there's no real reason not to populate the sheet:
- DropShips don't even show the Engine info line,
- ASFs do, but it's informational, not functional
Testing:
- Ran checks with provided DS .blk files
- Ran all 3 projects' unit tests
- Added a unit test to confirm proper functionality in the above case.
Close #1588
> Fix 1588: NPE printing or previewing DropShip

- megameklab/src/megameklab/ui/mek/BMBuildTab.java
Reverts an accidental resource rename that blocked MML's BM UI
> resource rename fix

- megameklab/src/megameklab/ui/dialog/PrintQueueDialog.java
Simple refactor of a previous pull request to not make the print-queue dialog depend on ClientGUI. 
Also sets the default filename of the new file to the name of the original file.
> Refactor saveUnitList() to not make a new ClientGUI

- megameklab/src/megameklab/ui/generalUnit/BasicInfoView.java
Errors introduced with flatlaf UI scaling
> Quick for tech level parsing

- megameklab/src/megameklab/printing/PrintEntity.java
Closes #1584.
Requires MegaMek/megamek#6033.
When a unit mounts optional heat sinking equipment (Coolant Pods, Radical Heat Sinks), the heat profile is unhelpful: the given Dissipation value is never actually correct, since it's an approximate average between the dissipation with the system on or off.
This PR makes the sheet display both the heat value with the system off, and with the system on.
Since official sheets do not use the Heat Profile record sheet option, this change does not affect official sheets.
Example sheets:
> Better display of radical heat sinking in RS

- megameklab/src/megameklab/util/UnitPrintManager.java
This seems to be a feature that previously existed in MML, but at some point got broken.
When including pilot data when printing from a MUL, print the unit's SPAs in the Warrior Data box.
This has no impact on official sheets, since official sheets don't include warrior data.
> Print SPAs in record sheets printed from MUL

- megameklab/src/megameklab/ui/mek/BMStructureTab.java
Requires MegaMek/megamek#6078 to produce correct mixed-tech patchwork armor mtfs.
Currently, setting the armor in one location sets the armor tech level of _every_ location, creating situations where we try to load a unit with Heavy Ferro-Fibrous (Clan) and other nonsense armors.
> Set techlevel of armor in specific location, not entire mek, when setting patchwork armor

- megameklab/src/megameklab/MegaMekLab.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/MenuBarOwner.java
This and the PRs for MM and MHQ (merge together) fix some remaining gui scaling issues.
- changes the code for the recent units in the file menu so that the path is again smaller and scales
- adaptation to MM changes
> GUI scaling fixes

- megameklab/resources/megameklab/resources/Views.properties
- megameklab/src/megameklab/printing/InventoryWriter.java
- megameklab/src/megameklab/printing/StandardInventoryEntry.java
- megameklab/src/megameklab/ui/generalUnit/HeatSinkView.java
- megameklab/src/megameklab/ui/listeners/BuildListener.java
- megameklab/src/megameklab/ui/mek/BMChassisView.java
- megameklab/src/megameklab/ui/mek/BMStructureTab.java
Depends on MegaMek/megamek#6149
Allows meks to be given a RISC Heat Sink Override Kit. Includes support for record sheets.
Checkbox to add the Kit is hidden when invalid for the current year/tech level.
> Add RISC Heat Sink Override Kit

- megameklab/src/megameklab/ui/dialog/PrintQueueDialog.java
- megameklab/src/megameklab/util/CConfig.java
If you select "Print one unit per sheet" or "Use adjusted BV" in the print-queue dialog, it will remember the state of those checkboxes for next time.
> Save print queue setup between runs

- megameklab/src/megameklab/ui/mek/BMCriticalTransferHandler.java
- megameklab/src/megameklab/ui/mek/BMCriticalView.java
- megameklab/src/megameklab/ui/mek/BMStructureTab.java
- megameklab/src/megameklab/util/MekUtil.java
- megameklab/src/megameklab/util/UnitUtil.java
Includes three related features. I implemented the latter two while failing to implement the first one.
1. See #1644. RISC Super-Cooled Myomer slots are autosorted after other equipment.
2. Changing the myomer type in the Structure tab now fully removes the previous myomer type right away, instead of leaving parts of it in the unit until something else triggered a full refresh.
3. Critical slots of fixed-location equipment (RISC SCM, Null-Sig, Partial Wing, etc) can now be moved around within a location if you want to reorder them manually:
> Various Mek crit table improvements

- megameklab/resources/megameklab/resources/Dialogs.properties
- megameklab/resources/megameklab/resources/Menu.properties
- megameklab/src/megameklab/MegaMekLab.java
- megameklab/src/megameklab/ui/MegaMekLabMainUI.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/MenuBarOwner.java
- megameklab/src/megameklab/ui/MulDndBehaviour.java
- megameklab/src/megameklab/ui/StartupGUI.java
- megameklab/src/megameklab/ui/dialog/settings/MiscSettingsPanel.java
- megameklab/src/megameklab/util/CConfig.java
- megameklab/src/megameklab/util/MMLFileDropTarget.java
- megameklab/src/megameklab/util/UnitPrintManager.java
Allows you to drag unit files (MTF/BLK) or MUL files from your OS's file explorer onto MegaMekLab:
You can drag them onto the startup GUI or almost anywhere onto the unit editing GUI.
I've tested, and crit-slot drag-and-drop still works without issues, the only thing to note there is that you cannot drag files onto a unit's crit table, which I'm sure no one will mind.
You can also ask your operating system to open these files with MML if you tell it the path to MegaMekLab.exe (or equivalent executable for your system):
Unit files will be opened to edit, while MUL files will be opened to print. 
A new setting is added to determine if dropped MUL files should be printed or exported to PDF:
> Allow opening unit and MUL files with MML by file association or drag-drop

- megameklab/src/megameklab/util/UnitPrintManager.java
Fixes #1565.
If a file with no extension is selected for pdf export, automatically add a .PDF extension.
> Add pdf extension to files selected without one

- megameklab/src/megameklab/MegaMekLab.java
You can now `megameklab.exe whatever.mul --no-startup` and it will create the print-queue dialog but not create the main MML gui.
This will allow MegaMek to print a unit list by calling MML without it looking like it's starting MML.
> Add flag to show print-mul dialog without starting the main MML gui

- megameklab/src/megameklab/ui/generalUnit/TransportTab.java
Fix for #1667, "Incorrect minimum doors required for cargo bays".
Corrects the UI elements which determine whether bays can be added, doors increased or decreased, and whether a unit with bays is valid or not, based on the matching PR for MegaMek.
NOTE: this PR will break MML until the [MM PR](https://github.com/MegaMek/megamek/pull/6322) is merged!
Testing:
- Loaded units from original issue successfully.
- Added various bays with 0 doors as default.
- Reduced existing cargo bay doors to 0 without issue.
- Saved and loaded updated units.
- Ran all 3 projects' unit tests (with MM and MML patches applied)
Close #1667
> Fix MML #1667: incorrect cargo bay minimum doors (MML side)

- megameklab/src/megameklab/ui/FileNameManager.java
- megameklab/src/megameklab/ui/MegaMekLabMainUI.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/StartupGUI.java
- megameklab/src/megameklab/ui/util/MegaMekLabFileSaver.java
Supporting code changes to allow MHQ to utilize the existing unit saving code within its MekLab tab.
Changes include:
- Moving much of the MTF / BLK file saving code from the MML menu bar UI code out to a separate class;
- Creating a new interface based on the existing save functionality to facilitate using this new class with MHQ;
- Separating the entity-related code from the file-save-related code as much as possible.
Testing:
- Ran all 3 projects' unit tests
- Loaded and saved multiple units of various kinds with the updated code.
NOTE: this PR only sets up the code needed by the MHQ PR, which will close the above RFE issue.
The other PR is [here](https://github.com/MegaMek/mekhq/pull/5632).
> MHQ RFE 5604: save refit files from MHQ MekLab tab (MML side)

- megameklab/src/megameklab/ui/MegaMekLabMainUI.java
- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/battleArmor/BABuildTab.java
- megameklab/src/megameklab/ui/battleArmor/BABuildView.java
- megameklab/src/megameklab/ui/battleArmor/BAMainUI.java
- megameklab/src/megameklab/ui/combatVehicle/CVBuildTab.java
- megameklab/src/megameklab/ui/combatVehicle/CVMainUI.java
- megameklab/src/megameklab/ui/fighterAero/ASBuildTab.java
- megameklab/src/megameklab/ui/fighterAero/ASBuildView.java
- megameklab/src/megameklab/ui/fighterAero/ASMainUI.java
- megameklab/src/megameklab/ui/generalUnit/UnallocatedView.java
- megameklab/src/megameklab/ui/infantry/CIMainUI.java
- megameklab/src/megameklab/ui/largeAero/DSMainUI.java
- megameklab/src/megameklab/ui/largeAero/LABuildTab.java
- megameklab/src/megameklab/ui/largeAero/LABuildView.java
- megameklab/src/megameklab/ui/largeAero/WSMainUI.java
- megameklab/src/megameklab/ui/mek/BMBuildTab.java
- megameklab/src/megameklab/ui/mek/BMBuildView.java
- megameklab/src/megameklab/ui/mek/BMMainUI.java
- megameklab/src/megameklab/ui/protoMek/PMBuildTab.java
- megameklab/src/megameklab/ui/protoMek/PMBuildView.java
- megameklab/src/megameklab/ui/protoMek/PMMainUI.java
- megameklab/src/megameklab/ui/supportVehicle/SVBuildTab.java
- megameklab/src/megameklab/ui/supportVehicle/SVMainUI.java
- megameklab/src/megameklab/ui/util/TabStateUtil.java
Minor improvement to the new Tabs UI.
First, when tabs are restored, equipment not allocated to a location is no longer lost, making that feature more reliable.
Second, new ways to open a new tab:
The old + button can now be right-clicked to select a unit type:
The new ⌸ button will load a unit from cache, and can be right clicked to load a unit from a file:
> Tabbed UI Improvements

- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
You can't switch unit type to the unit type of the current unit, but if the menu bar isn't refreshed, it'll use the unit type of the _first_ unit, not the _current_ unit, to determine which unit kind you can't switch to.
Refreshing the menu bar when you switch to a new tab solves this (and likely some other problems as well).
> Refresh menu bar to new current unit when new tab is selected

- megameklab/src/megameklab/EntityChangedUtil.java
- megameklab/src/megameklab/ui/MegaMekLabMainUI.java
- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/util/MegaMekLabFileSaver.java
- megameklab/src/megameklab/util/EntityChangedUtil.java
This enables MML to determine if a unit has unsaved changes, offering us two features: First, tabs now show a little * next to the unit name if the tab has unsaved work, and second, we don't show the "would you like to save your work" safety prompt for units which don't have any work to save.
This PR also contains a very small extra feature, which allows you to middle click tabs to close them, which might cause merge conflicts if it was in a separate PR.
> Detect unsaved work

- megameklab/src/megameklab/ui/StartupGUI.java
Yeah, that function you're supposed to call on a unit before loading it in the editor? Turns out it exists for a reason.
Fixes #1687.
> Fix loading of FMU slots

- megameklab/testresources/ui/generalUnit/BasicInfoViewTest/Puma Assault Tank PAT-001.blk
- megameklab/unittests/megameklab/ui/generalUnit/BasicInfoViewTest.java
Unit test to verify updating and saving BLK files from MML code will maintain IS Unofficial tech base and level.
Confirms fix for #1686
Note: must be merged following [this PR](https://github.com/MegaMek/megamek/pull/6386) or the test will fail.
> Fix 1686: Add unit test to verify IS Unofficial tech base and level can be saved and loaded

- megameklab/src/megameklab/ui/generalUnit/BasicInfoView.java
- megameklab/src/megameklab/ui/util/AbstractEquipmentDatabaseView.java
While exploring our Equipment filtering code as part of #1696 , I found that we are incorrectly applying the "Introductory" tech level filter in such a way that it always shows up to Standard-level equipment instead.
The fix is to use an existing function in SimpleTechLevel to get the correct enum value from the Tech Level combobox, which prevents the exception that defaults to Standard tech level.
Testing:
- Ran all 3 projects' unit tests
- Confirmed Tech Level selection now works correctly in the UI
- Confirmed non-VTL tech advancement follows the process outlined in #1696 comments
Close #1696
>  Fix for Introductory tech level also showing Standard equipment in non-VTL mode.

- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
- megameklab/src/megameklab/ui/MenuBar.java
Lots of small fixes and QOL improvements:
- Ensure that renaming a unit renames its tab, even after switching unit type.
- Only show the "Are you sure" prompt for operations where it makes sense, i.e. not loading a unit in a new tab.
- Fix "Load from file" not working from the startup GUI.
- Allow you to close tabs by middle-clicking them.
> Tabbed UI Polish Pass

- megameklab/src/megameklab/ui/util/ITab.java
Fixes #1699, `getAero` is used by some methods that work with any kind of aerospace unit, not necessary an ASF.
> Fix "Reset crits" on DropShip/SmallCraft not working

- megameklab/src/megameklab/printing/InventoryWriter.java
- megameklab/src/megameklab/printing/PrintTank.java
Closes #1701.
Support Vee transport bays should show how many doors they have, similar to DropShips and Small Craft.
> Include door count for SV transport bays

- megameklab/src/megameklab/ui/generalUnit/TransportTab.java
I think this fixes #1661 
Infantry Bays multiplied their own weight by their intrinsic weight (e.g. 5 for foot inf) every time they were re-created. I suppose this led to the weird crew calculation. The MASH bug is fixed by unit data changes in MM.
> fix transport tab weight inflation on infantry bays

- megameklab/docs/history.txt
- megameklab/src/megameklab/ui/MegaMekLabMainUI.java
- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
- megameklab/src/megameklab/ui/combatVehicle/CVStructureTab.java
- megameklab/src/megameklab/ui/fighterAero/ASMainUI.java
- megameklab/src/megameklab/ui/fighterAero/ASStructureTab.java
- megameklab/src/megameklab/ui/infantry/CIMainUI.java
- megameklab/src/megameklab/ui/largeAero/DSMainUI.java
- megameklab/src/megameklab/ui/largeAero/DSStructureTab.java
- megameklab/src/megameklab/ui/largeAero/WSMainUI.java
- megameklab/src/megameklab/ui/largeAero/WSStructureTab.java
- megameklab/src/megameklab/ui/mek/BMMainUI.java
- megameklab/src/megameklab/ui/mek/BMStructureTab.java
- megameklab/src/megameklab/ui/protoMek/PMMainUI.java
- megameklab/src/megameklab/ui/supportVehicle/SVStructureTab.java
Changing the type of an entity (e.g., from biped mek to quad mek) now properly updates the tab title instead of setting it to "null".
This bug actually existed before tabs, where it would improperly set the window title.
> Prevent tab names from being messed up by entity type change

- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
Fixes #1714. 
Same thing as #1689.
> Missed an updateLoadedUnit

- megameklab/src/megameklab/printing/PrintRecordSheet.java
This fixes font tag replacement for PDF printing. Still, this only works with printing. For PDF export it has no effect but the cause is elsewhere (Apache FOP, apparently, that cannot use OS-installed fonts)
fixes #1695
> Restore font replacement for pdf printing

- megameklab/src/megameklab/ui/util/AbstractEquipmentDatabaseView.java
According to TO:AUE p217 and p96, artillery cannot be mounted on capital craft at all; this PR hides the "Arty" equipment filter button on those units.
> Hide Arty equipment filter button on capital craft

- megameklab/src/megameklab/ui/battleArmor/BABuildView.java
fixes #1363
I am not sure what effects removing the F_MISSILE tag from Tube Arty would have and it is a missile weapon, therefore this allows mounting BA Tube in DWP explicitly.
> #1363: Allow BA Tube Arty in DWP

- megameklab/src/megameklab/ui/generalUnit/HeatSinkView.java
Fixes #1575
Also fixes #1649 which I think was caused by a mismatch of the unit having CHS and the MML UI having selected Single HS
2 CHS packed in 1 slot is its own MiscType. The UI didnt find the Compact HS combobox entry for it though. This happened only when the CHS needed to be assigned to slots (more than the engine free).
history entry: The MML heat sink GUI section will now correctly identify compact heat sinks on a freshly-loaded mek even if it has some of them assigned to crit slots
> Issue #1575: correctly identify compact heat sinks

- megameklab/src/megameklab/ui/util/BAASBMDropTargetCriticalList.java
- megameklab/src/megameklab/ui/util/DropTargetCriticalList.java
- megameklab/src/megameklab/util/UnitUtil.java
Fixes #1536
Requires MegaMek/megamek#6541
This moves tests for armorable components (TO:AUE p95) from MML to MM to unify them. 
Also removes some armoring code from DropTargetCritList as that class is not used for Meks and armoring is not allowed elsewhere.
history entry: + Fix #1536: Mek shields can now be armored
> #1536: Unify armorable equipment tests in MM

- megameklab/src/megameklab/printing/PrintUtil.java
- megameklab/src/megameklab/printing/StandardInventoryEntry.java
- megameklab/src/megameklab/util/StringUtils.java
Previously Laser Insulators and RISC Laser Pulse Modules would be listed as ordinary equipment in the RS inventory readout.
This adjusts them to be displayed together with the weapon they're associated with, similar to how Artemis and PPC Capacitors work.
Additionally, since these enhancements (plus the capacitor) affect the weapon's basic stats and they take up a second line on the sheet, we can use that second line to display the new stats for for the weapon with that enhancement. 
Example sheet:
In the future it would be nice to also update the value shown in the heat profile, but that's a separate (and more complex) issue that I won't be addressing for now.
> Improve RS display of information for Insulators/Pulse Modules/Capacitors

- megameklab/src/megameklab/util/MekUtil.java
- megameklab/src/megameklab/util/UnitUtil.java
Chain Drape from Arcade Operations: UrbanFest.
Closes #1222.
Requires MegaMek/megamek#6594, see there for more information.
There are a couple differences between the published UrbanKnight sheet and this recreated one.
First, the printed MP is reduced to be consistent with Modular Armor reducing the MP listed on the record sheet.
Second, the BV doesn't match. There is no published information on calculating BV for the chain drape, so I don't know how to make it line up.
> Chain Drape

- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
Fixes #1716: When switching unit type, the menubar is now refreshed to reflect to the new unit type.
Fixes #1718: When closing the last tab, create a new blank mek tab instead of entering a broken tabless state.
> Fixes for tabbed UI

- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/dialog/UiLoader.java
- megameklab/src/megameklab/ui/util/TabUtil.java
- megameklab/src/megameklab/util/MMLFileDropTransferHandler.java
Closes #1745.
Allows dragging multiple files onto MML (either the splash screen or the tabbed UI) to open all the files, with a progress bar: https://i.imgur.com/MbmR9ch.gif
> Allow loading multiple unit files by drag-and-drop

- megameklab/build.gradle
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/StartupGUI.java
- megameklab/src/megameklab/ui/dialog/MegaMekLabUnitSelectorDialog.java
- megameklab/src/megameklab/ui/dialog/PrintQueueDialog.java
- megameklab/src/megameklab/ui/generalUnit/FluffTab.java
- megameklab/src/megameklab/ui/generalUnit/IconView.java
- megameklab/src/megameklab/ui/util/TabUtil.java
- megameklab/src/megameklab/util/UnitPrintManager.java
Closes #1744.
Leverages the new multiselect capability of the unit select dialog to allow loading multiple units at a time in MegaMekLab. 
You can now select unit(s) without closing from the tabbed UI, or drag select multiple units in one go.
This required rewiring quite a bit of code, I've mentioned this before but MML was _not_ setup to make it easy to have multiple units open at once.
> Load multiple units from cache at a time

- megameklab/data/images/recordsheets/templates_iso/advaero_reverse.svg
- megameklab/data/images/recordsheets/templates_us/advaero_reverse.svg
- megameklab/src/megameklab/printing/IdConstants.java
- megameklab/src/megameklab/printing/PrintDropship.java
- megameklab/src/megameklab/printing/PrintEntity.java
- megameklab/src/megameklab/ui/dialog/MegaMekLabUnitSelectorDialog.java
- megameklab/src/megameklab/ui/generalUnit/RecordSheetPreviewPanel.java
- megameklab/src/megameklab/util/UnitPrintManager.java
- Added support for viewing record sheets of units with multiple pages ("Leviathan II" for example)
- Fix for AdvAero units that had a broken label on their 2nd page (%s)
- Optimized record sheet preview (no rendering if not visible)
- Implemented record sheets visible directly from the unit selection list
- Limited multi-unit visualization to 10
> Multipage preview and adv aero fix

- megameklab/src/megameklab/ui/mek/BMStructureTab.java
Fixes #1761.
By setting the mek's tonnage _before_ resetting it's gyro, we prevent the mek's gyro type from being set back to Superheavy Gyro after we set it to Standard Gyro.
> Don't keep superheavy gyro when moving to 100 tons or below

- megameklab/src/megameklab/ui/dialog/settings/SettingsDialog.java
There are now enough settings that they don't fit into the default window size, which pack fixes.
> pack() configuration dialog

- megameklab/resources/megameklab/resources/Menu.properties
- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
- megameklab/src/megameklab/ui/MenuBar.java
Updates the File->Switch Unit Type menu and the New Tab right click context menu to include Handheld Weapons, now that HHWs have record sheets and someone might actually want to build one.
Also fixes a bug where switching unit type wouldn't update the tab name.
> Add HHW to new unit/switch unit type menus

- megameklab/src/megameklab/printing/PrintInfantry.java
- megameklab/src/megameklab/ui/infantry/CIArmorView.java
Depends on MegaMek/megamek#6832.
Fixes #1808.
When setting a custom armor kit, it is now included in the record sheet:
Also adds a warning that if you enable both DEST and Sneak, things may break. The record sheet will not properly display both DEST and Sneak because you really _shouldn't_ do that, even though we're not stopping you.
> Custom armor kit in Record Sheets

- megameklab/src/megameklab/ui/battleArmor/BAMainUI.java
- megameklab/src/megameklab/ui/combatVehicle/CVMainUI.java
- megameklab/src/megameklab/ui/fighterAero/ASMainUI.java
- megameklab/src/megameklab/ui/generalUnit/QuirksTab.java
- megameklab/src/megameklab/ui/generalUnit/RecordSheetPreviewPanel.java
- megameklab/src/megameklab/ui/largeAero/DSMainUI.java
- megameklab/src/megameklab/ui/largeAero/WSMainUI.java
- megameklab/src/megameklab/ui/mek/BMMainUI.java
- megameklab/src/megameklab/ui/protoMek/PMMainUI.java
- megameklab/src/megameklab/ui/supportVehicle/SVMainUI.java
- megameklab/src/megameklab/ui/util/EnhancedTabbedPane.java
- changed setEntities to use wildcard type
- corrected a debounce call to use the proper method
- during inplace updates we get the updated sheets in EDT (prevents CME)
- fixed hand cursor not properly reset to default when leaving a tabbed pane
- fixed NPE caused by UnitMemento when opening multiple units
> Fixes for RS preview and enhanced tabbed pane

- megameklab/src/megameklab/printing/PrintUtil.java
Fixes #1807.
The BA Camo System used to have a special section just for it in old sheets, and no longer does, so we want to include it in the main inventory.
> Include BA Camo System in record sheets

- megameklab/src/megameklab/ui/mek/BMStructureTab.java
Requires MegaMek/megamek#6893.
Fixes #1815.
Re-add the Mek's armor slots when it becomes or stops being a Superheavy Mek to ensure the correct armor slot count.
> Update armor slot count on superheavy status change

- megameklab/src/megameklab/ui/dialog/PrintQueueDialog.java
- megameklab/src/megameklab/ui/dialog/settings/SettingsDialog.java
- megameklab/src/megameklab/util/MULManager.java
- megameklab/src/megameklab/util/UnitPrintManager.java
this PR is a variant of #1857
- instead of using a System.exit(0) it fixes the closing of the the application by fixing the memory leak in the dialogs (they are never released).
- the dummy frame is implemented directly in the MULManager
- canceling a system print dialog will bring you back to the print queue dialog with closing it
> fixes MUL print from console and memory leaks on dialogs

- megameklab/docs/history.txt
- megameklab/resources/megameklab/resources/Menu.properties
- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/MenuBarOwner.java
- megameklab/src/megameklab/ui/StartupGUI.java
this PR:
- fixes the misleading methods of newUnit() and implements proper createNewUnit() and switchUnit()
- add a new File->New... menu structure where you can directly choose what type of unit you want (solves the need to create a mek unit first and then switch it to another type)
- CTRL+N accelerator is kept as before, will create a new mek as before
> fixed misleading switch and create unit methods

- megameklab/src/megameklab/ui/supportVehicle/SVStructureTab.java
This fix makes sure that if you are creating a trailer with no engine it will set the walk MP to zero.
If you set an SV as a trailer, the minWalk MP is set to 0, meaning you can set the MP of the unit to 0, but if you change the engine to `None` right after you set the SV as a trailer, then both minWalk and maxWalk becomes 0, making it impossible to set in the entity a new walkMP value, this means that any value it had before it will keep on having. It will then persist the cruising MP and will always be considered a valid unit.
To avoid this situation, whenever the engine is set as `None`, this will also reset the originalWalkMP of the unit to 0, if there are any cases which would allow you to increaase your walkMP to anything different, this won't interfere, as it just forces the reset …
> fix: resets walk MP to 0 when setting an SV engine as None

- megameklab/resources/megameklab/resources/Menu.properties
- megameklab/src/megameklab/printing/InventoryWriter.java
- megameklab/src/megameklab/printing/WeaponBayInventoryEntry.java
- megameklab/src/megameklab/printing/WeaponBayText.java
- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/generalUnit/FluffTab.java
This PR contains few fixes for Aero stuffs:
- fixed columns for AR10 Munition Table
- fixed multi-ammo weapons in bays (AR10 specifically) by adding "multi-ammo to single weapon" support to bays
- fixed visualization of LBX weapons damage on Aero (this comes from the linked MM PR)
- fixed visualization of the IATM weapons damage on Aero
Fixes #1810
Fixes #1811
Linked to https://github.com/MegaMek/megamek/pull/6972
extra minor fixes:
- help->about and help->images have now clickable links, no need to type them manually...
- fluff page have the textarea fields showing the first line
> Aero fixes

- megameklab/src/megameklab/printing/InventoryWriter.java
- megameklab/src/megameklab/printing/reference/ClusterHitsTable.java
- megameklab/src/megameklab/ui/battleArmor/BABuildTab.java
- megameklab/src/megameklab/ui/battleArmor/BAMainUI.java
- megameklab/src/megameklab/ui/battleArmor/BAStructureTab.java
- megameklab/src/megameklab/ui/combatVehicle/CVBuildTab.java
- megameklab/src/megameklab/ui/combatVehicle/CVMainUI.java
- megameklab/src/megameklab/ui/fighterAero/ASCriticalView.java
- megameklab/src/megameklab/ui/fighterAero/ASMainUI.java
- megameklab/src/megameklab/ui/handheldWeapon/HHWMainUI.java
- megameklab/src/megameklab/ui/infantry/CIMainUI.java
- megameklab/src/megameklab/ui/largeAero/DSMainUI.java
- megameklab/src/megameklab/ui/largeAero/LABuildTab.java
- megameklab/src/megameklab/ui/largeAero/WSMainUI.java
- megameklab/src/megameklab/ui/mek/BMBuildTab.java
- megameklab/src/megameklab/ui/mek/BMCriticalTransferHandler.java
- megameklab/src/megameklab/ui/mek/BMMainUI.java
- megameklab/src/megameklab/ui/protoMek/PMBuildTab.java
- megameklab/src/megameklab/ui/protoMek/PMMainUI.java
- megameklab/src/megameklab/ui/supportVehicle/SVMainUI.java
- megameklab/src/megameklab/ui/supportVehicle/SVStructureTab.java
- megameklab/src/megameklab/util/UnitUtil.java
This PR fixes various bugs with Critical Slots:
- after switching Aerospace chassis Aerospace Fighter<->Conventional Fighter: no more bugged Critical Slots with wrong entries after adding new equipment
- when switching BattleArmor chassis humanoid<->quad: the equipment on the arms and turret will be dismounted (no more hidden equipment)
- BattleArmor equipment that should be assigned to critical slots but is not yet assigned, will not appear in the record sheets and will not count for the columns to use for the Cluster Hit Table.
- add proper call, where missing, to changeMountStatus() after removing a mount from a critical slot
- fixed issue with new units requiring a "refresh ui" to see new critical slots assignments after drag'n'drop
- Unifies the [reset] of critical slots for all …
> fixes on critical slots and unified reset of criticals

- megameklab/resources/megameklab/resources/Views.properties
- megameklab/src/megameklab/printing/PrintEntity.java
- megameklab/src/megameklab/ui/fighterAero/ASStructureTab.java
- megameklab/src/megameklab/ui/generalUnit/HeatSinkView.java
- megameklab/src/megameklab/ui/largeAero/DSStructureTab.java
- megameklab/src/megameklab/ui/largeAero/WSStructureTab.java
- megameklab/src/megameklab/util/UnitUtil.java
With this, all units that are tracking heat/heatsinks will now display, in the HeatSink group of the Structure Tab, also how much they are dissipating and the total heat generated by all the equipment.
Closes #568
> heat view now displays also total dissipation and total heat

- megameklab/src/megameklab/ui/generalUnit/MovementView.java
Currently, we include the state of speed enhancers in the Run MP box, which looks bad: 
Cut this out to go back to the old way of just showing 9(15) or whatever. 
Requires MegaMek/megamek#6993.
> Don't include game state in run mp display

- megameklab/src/megameklab/ui/MenuBar.java
Fixes #1875.
When the menu bar is refreshed, the list of unit types valid for the switch-unit-type menu should now be regenerated.
> Refresh the available switch-unit-type targets of edit menu

- megameklab/src/megameklab/printing/InventoryWriter.java
Fixes #1874.
Uses the same approach as the RISC Override Kit.
> Include full-head ejection system in record sheets.

- megameklab/src/megameklab/printing/InventoryEntry.java
- megameklab/src/megameklab/printing/WeaponBayInventoryEntry.java
- megameklab/src/megameklab/ui/generalUnit/HeatSinkView.java
Fixes the display of the dissipation capacity of a mech in the Heatsink group (Structure Tab).
Now will show only the dissipation (heatsink capacity)
extra: moved aero mod calculation to MM.
> Fixes display of dissipation

- megameklab/src/megameklab/ui/handheldWeapon/HHWEquipmentDatabaseView.java
- megameklab/src/megameklab/util/MekUtil.java
Because despite being a WeaponType MML considers TAG to be Equipment and not a Weapon.
> Allow TAG on HHWs

- megameklab/src/megameklab/ui/MenuBar.java
- megameklab/src/megameklab/ui/util/OSUtil.java
On MegaMekLab the "Recent files" in the menu bar appear with a bunch of html tags written in raw text. Apparently when adapting the look and feel of the OS it also gains some of its quirks, mac in particular is not able or not willing to render HTML on the menu bar in the way we setup it right now.
This PR checks if the OS is mac or not, and if it is mac it won't load the html tags 
Before:
After:
> fix: checks if OS is mac and dont load the html for the recent files in the menu bar

- megameklab/src/megameklab/ui/MegaMekLabTabbedUI.java
- megameklab/src/megameklab/util/CConfig.java
This PR adds a simple check to prevent read the content of a setting if is empty.
> Don't read the config if the setting is empty

- megameklab/build.gradle
Adjust build scripts to first sync the license files to the build area then copy to the staging area.
> Fix: Adjusted to sync then copy the license files.

- megameklab/src/megameklab/ui/util/BayWeaponCriticalTree.java
Fixes #1953.
Equipment which doesn't need a location (remote sensor dispensers, for example) shouldn't be placed in locations other than the Hull. The equipment would be moved to the Hull on load anyway (see MegaMek/megamek#7297) so there's no reason to allow the drop in other locations.
> Don't allow hull-only equipment to be dropped in locations other than the hull.

- megameklab/src/megameklab/ui/util/EquipmentTableModel.java
Fixes #1952.
Turns out some items weigh less than 1kg, bump up the number of decimal places from 0 to 2 for them.
> Increase precision of weight display for sub-kg items

- megameklab/src/megameklab/util/UnitUtil.java
Fixes #1965.
`isExplosive` can be told to ignore charge state. Capacitors are off during some staged of record sheet rendering, but locations with PPC capacitors should be drawn with clan CASE.
> Treat capacitors as explosive when giving clan case

- megameklab/src/megameklab/printing/PrintEntity.java
- megameklab/src/megameklab/util/UnitUtil.java
Improves the record sheet heat readout line to factor in capacitors, insulators, rapid-fire weapons, and include one-shot weapons separately. 
Example:
> Improve heat readout for RS

- megameklab/src/megameklab/printing/PrintUtil.java
The BA Modular Weapon Mount is a construction detail which should not be present on record sheets.
Requires MegaMek/megamek#7312 to be merged first.
> Exclude BA MWM from RS

- megameklab/src/megameklab/printing/InventoryWriter.java
Handheld Weapons have a special section on their record sheet dedicated to just ammo, therefore the ammo count does not need to also be included in the Weapons & Equipment Inventory section.
Before:
After:
> Don't include ammo twice on HHW RS

- megameklab/data/images/recordsheets/templates_iso/handheld_weapon_large.svg
- megameklab/data/images/recordsheets/templates_iso/handheld_weapon_standard.svg
- megameklab/data/images/recordsheets/templates_us/handheld_weapon_large.svg
- megameklab/data/images/recordsheets/templates_us/handheld_weapon_standard.svg
- megameklab/src/megameklab/printing/PrintHandheldWeapon.java
Instead of needing to count pips to see how much ammo you have, also include a number. 
Single bin:
Multiple bins:
> Include ammo count in HHW ammo display
